### ISSUE TITLE
Shortcuts for filters and releated tools

### ISSUE THREAD

**Issue by Disaster2life** [jliljebl/flowblade#1019]
I remember seeing some documentation for how to help with contributions, but I can't seem to find it now, but I wondered if there was anyway to make it so that pressing a specific key for example "Shift+M" would automatically allow for you to apply a chroma key filter or something to the currently selected clip? I would love to contribute, not that great with python but would love to try.

**Comment by jliljebl** [comment]
Hi, so for code contributions the workflow is to fork Flowblade repo, create a feature branch and code in that. While your working you need to keep you master branch updated and merge it to your feature branch before doing pull request so that pull request only has your feature changes. There is Github documentation available on the process.

Its also good to start with an Issue here - like you did - so that we are in agreement on the need for feature before doing coding work. The contributing doc you mentioned is https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/CONTRIBUTING.md

--- 

I looked at big commercial editors for this feature. Seems that FCX has some version of this, but Avid and Premiere do not, see here: https://community.avid.com/forums/t/183581.aspx, https://adobe-video.uservoice.com/forums/911233-premiere-pro/suggestions/33844213-keyboard-shortcut-for-effects-presets-pleeeeease

There does seem to be demand for a feature making possible to map adding effects to clips using keyboard shortcuts, so if you can contribute this it would be great.

On doing this in Flowblade I can give outline here on how to do it.

**1) Choosing keys** I think keycombos *Control + F1-F12* would be the most logical mapping for this feature. Doing e.g.  *Control + M* would only allow for filters with M to be added and we would like this to be user configurable, not hard coded for just some effects.

**2) Detecting key presses** This would happen in *keyevents.py*, the code there should be quite readable on how to do this.

**3) Adding Effects** We should probably add new module like *effectshortcuts.py* and call that from *keyevents.py* on keypresses.  *effectshortcuts.py* would have some mapping *keycode -> filter* and use data *movemodes.selected_track, movemodes.selected_range_in, movemodes.selected_range_out* to get selected clips that the effect will be added to, and then call *edit.add_filter_multi_action*, see *clipmenuaction._add_filter_multi* for info.

**4) Saving user mappings** These should be added to *editorpersistance.EditorPreferences*, existing *shortcuts.py* won't work here, it maps in the wrong direction (keys to actions).

**5) User GUI for creating the mapping** New module should create a panel that's added to **Keyboard Shortcuts** dialog in *dialogs.py* to provide GUI for setting these. A function similar to *guicomponets._get_filters_add_menu_item* would provide menu to select filter for each function key. This is likely the hard part.

---

Overall this should not be super difficult, and if you provide a pull request adding this, I'll be more then happy to merge it.

**Comment by DisasterRunnner** [comment]
> I looked at big commercial editors for this feature. Seems that FCX has some version of this, but Avid and Premiere do not, see here

I actually got inspired for this by a premier user who had to hack together multiple hours worth of work to make a solution for it, but I realized it would be very efficient in my workflow and I could help natively add it in flowblade.

> Overall this should not be super difficult, and if you provide a pull request adding this, I'll be more then happy to merge it.

I see, I think I would be able to pull most of it, except the GUI part since I have never really worked with GUI related stuff.

I'll get started on it and will let you know on updates

**Comment by jliljebl** [comment]
Hi, I went ahead and added this, it was just two short sessions, so I thought I'll get this for 2.10. Thanks for the idea and feature request.
