### ISSUE TITLE
Request/Enhancement: Keep or Show Render Duration after completed

### ISSUE THREAD

**Issue by DroWnThePoor** [jliljebl/flowblade#1029]
I hope this isn't the wrong way to request something like this, but I can't figure out how to add labels to issues.

Just a simple request, but it would be nice if we could start and render and walk away/leave, but then be able to see the time it took to render the video after it's completed. 
I realize the dialogue closes entirely on completion so maybe more effort than it's worth but it's present in Kdenlive.

Thank you for all of your hard work.
I often will mention Flowblade in videos I make, and praise the quality of work with only one full-time developer(that I'm aware of).

**Comment by jliljebl** [comment]
Repo owner - so here me - adds labels to categorize them somehow and give feedback on status of particular issues, so don't worry about that, you *can't* add labels.

I see utility in this request, so we can try to find a way to add this. The main question is what is the best way to do it, there are multiple reasonable approaches here. Once I decide on a solution, I'll add this, but this might not make into next release.

Thanks for your kind words and support. There are no "full-time" devs on this but I do try to give my maximum attention to this when possible.

**Comment by jliljebl** [comment]
I just realized when going through the Issues that there is a reasonable way to achieve this, namely to render program in *Batch Render Queue* tool.

So **the workaround is to press 'To Queue' button instead of 'Render' when wishing to start rendering.** The  *Batch Render Queue* tool remembers render times after renders are completed.

I think this is good enough, and we don't need to add another way to do this, so I'm closing this as 'wontfix'.
