### ISSUE TITLE
INFO: FLOWBLADE DEVELOPMENT WILL CONTINUE IN THE BEGINNING OF AUGUST,

### ISSUE THREAD

**Issue by welon68** [jliljebl/flowblade#1073]
what year?

**Comment by jliljebl** [comment]
Well not 2022 ;)

Project is coming fully back now with resumed communications on Issues etc. I decided to just do patches until I have 2.10 release because it turned out that I was really unable to know when I would able to release, and frankly got a bit frustrated.

Moving on I have a new set of practices like always working on branches, and dropping doing .deb packages that will prevent dropping down in this hole again. 2.10 coming in few weeks after I have gone through the issues and done a bit more testing.
