### ISSUE TITLE
Feature request: mute video in place

### ISSUE THREAD

**Issue by Levitanus** [jliljebl/flowblade#1085]
Please include the following information.
1) Flowblade version (Help->About): 2.8
2) MLT version (Help->Runtime Environment): 6.24.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Manjaro

I have synced footages of live musical performance, and, for me it's quite natural to at first, cut them through and look, which angles I want to use.
![изображение](https://user-images.githubusercontent.com/29713891/215326424-52e1fdb9-30b8-4b28-9f2e-bafa35b25530.png)

As I'm not sure what to keep and what to lose, especially in team work, I want to keep all the clips, but just mute them at need. In case of the final removing of clips it would be hard to place it back to the place, if suddenly we want to change the angle. 

I think, that straightforward solution is just to make it possible to mute the clip in place (currently only audio can be muted). A more complex solution is to make some sort of takes system as in audio DAWs (I believe there is something similar in FinalCut). But I do not feel this a big necessary. But muting looks not very complex and quite usable for me.

**Comment by Levitanus** [comment]
That's how it looks in Reaper DAW now, and I'm very happy with the usability. But it has not got MLT and G'Mic under the hood....
![изображение](https://user-images.githubusercontent.com/29713891/215328460-f1b97232-7cd5-4a74-8759-ffafd2c18bd8.png)

**Comment by jliljebl** [comment]
Thanks, use case seems a useful feature when editing video synchronized with audio. I'll add this into feature queue.

**Comment by jliljebl** [comment]
Unfortunately turns out that this an extremely difficult feature to add without taking major risks with code base stability. 

Only way to make this video muting work in MLT (and this is how KDEnlive does it) is to replace clip with a blank clip and then replace blank clip with original clip when clip is enabled.

The problem is that Flowblade removes all trailing blanks and consolidates all sequential blanks into one after each edit. This means that the blank representing the disabled clip has to be tagged as a non-blank clip. This in turn breaks editing code all over the place because there are tens of code points handling blanks and media producing clips differently.

Making everything work would require carefully editing and testing all those code points and that cannot be done given the realities of available band with for the project.

KDEnlive probably has different way of handling blank clips which makes it possible for them to do the placement with smaller risk, or they have some subtle bugs because of this.

I'll add a keyboard shortcut to toggle track video visibility which should help at least somewhat with the use described here.
