### ISSUE TITLE
Licence for blade.svg

### ISSUE THREAD

**Issue by Disaster2life** [jliljebl/flowblade#1089]
I had a question regarding the licence for the file called blade.svg, I think it was the logo for the old google space website? I am contributing to an icon pack and I think that icon fits pretty well already, just wondering if I am free to use it for that purpose.

**Comment by jliljebl** [comment]
No, that image is something I created in Inkscape and it has been the defining visual element of Flowblade branding since the beginning of the project. 

If this was a commercial program, it absolutely would have been officially trademarked, and if someone tries to do trademark it for themselves, I believe I have a case to establish a trademark for it myself if needed. So, please don't use it in any context not related to the Flowblade project.

It has zero connection to anything that could be described as "old google space website".

**Comment by Disaster2life** [comment]
Apologies, I made my point badly, I don't plan on using it for some Commerical project, only to use it in an [icon pack](https://github.com/Delta-Icons/Linux), I do not wish to tread any trademark laws, just to use it as a replacement for the flowblade application icon itself, not for anything else, and I know that the SVG file has history with the project, so I planned on using that instead of basically tracing it over again because blade.svg already fits the style of the Delta Icon Pack, and I meant the [google code website](https://code.google.com/archive/p/flowblade/issues) though my memory seems to be failing, I thought the icon there was blade.svg not the application icon
