### ISSUE TITLE
[feature] Replace media in project.

### ISSUE THREAD

**Issue by gegoxaren** [jliljebl/flowblade#1102]
Please include the following information.
1) Flowblade version (Help->About): 2.10
2) MLT version (Help->Runtime Environment): 7.17.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Flatpak on Debian 12

Hello!

I was wondering if it would be possible to (add support to) replace media in the "library" of a project. I tried to edit the `.flb` file, but that is no longer human-readable.

(I was using a transport stream (`.ts`) video, but that did not really work, as there seems to not be any way for Flowblade to (properly) back-traverse to get valid image data per frame, thus making the video not correct when rendered or viewed, so I wanted to replace it with an `m4v` file without having to re-edit the video again).

Thank you in advance, and thank you for your very useful editor!
Gego.

**Comment by jliljebl** [comment]
There is a workaround for doing this already:

1) Save the Project you are working on.
2) Rename the file you want to replace, something like *videofile.mpg* -> *Xvideofile.mpg*.
3) Open project file. You'll get info that that file is missing and prompt to open file in  Media Relinker.
4) Go to Media Relinker and select the file you want to use instead of the old one, and then save as directed.
5) Open the created Project file.

Seems at least an occasionally useful feature to be able to do this directly using dedicated GUI, so I'll add this into feature queue.

**Comment by gegoxaren** [comment]
Ah, that's so obvious! why did I not think of that.

the project I was working on only had one cut, so it was not a big deal, but thank you, I'll try and remember that workaround for the future.

**Comment by Disaster2life** [comment]
I think this would be really useful to have as a dedicated GUI feature, I remember seeing an issue regarding how to deal with Camera generated proxy clips in flowblade, can't seem to find it now, this would also solve that.
