### ISSUE TITLE
install from source on linux Void

### ISSUE THREAD

**Issue by welon68** [jliljebl/flowblade#1123]
I have linux void. When I run the installation script "flowblade-trunk]$ ./flowblade" I get information that mlt7 is missing. But I have mlt7 installed. How should I update the script to know about available dependencies?

[welon@void flowblade-trunk]$ ./flowblade 
FLOWBLADE MOVIE EDITOR 2.10.0.4
-------------------------------
Launch script dir: /home/welon/tmp/flowblade-2.10.0.4/flowblade-trunk
Running from filesystem...
MLT not found, exiting...
ERROR: No module named 'mlt7'
[welon@void flowblade-trunk]$ sudo xbps-install -Sy mlt7
[*] Updating repository `https://repo-fi.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://repo-fi.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://repo-fi.voidlinux.org/current/nonfree/x86_64-repodata' ...
Package `mlt7' already installed.
[welon@void flowblade-trunk]$

**Comment by jliljebl** [comment]
> I have linux void. When I run the installation script "flowblade-trunk]$ ./flowblade" 

"flowblade-trunk]$ ./flowblade" is not install script, it is launch script.

Unfortunately I haave no knwledge on installing applications on linux Void and cannot say why supposesedly installed 'mlt7' package is not found whenrunning flowblade launch script.

Flowblade is available via Flathub, here are instructions on setting up Flathub on Void Linux: https://flathub.org/setup/Void%20Linux

I'm closing this as 'not an issue' because there are no source code changes that can be to Flowblade to help with the issue described here.
