### ISSUE TITLE
Insert clips at locator/mark position

### ISSUE THREAD

**Issue by cassiel74** [jliljebl/flowblade#114]
This would be really useful. 
A spacer clip could be added by default and the clip being inserted at any position on the timeline.

**Comment by jliljebl** [comment]
I believe this use case can be satisfactorily achieved using "Range Overwrite" functionality as follows:

1. Drag source Clip in to monitor
2. Set "Mark In" on the monitor clip using I key or button 
3. Set the track you want the material to be placed on as the top most active track
4. Set current frame on timeline to the desired frame and press set "Mark In" using button or I key
5. Set "Mark Out" on timeline using button or O key
6. Press Range Overwrite -button or select from menu "Edit->Add Monitor Clip->Range Overwrite"

This can be done on empy timeline but onemtytile user can simply press "Append Clip" button or U

**Comment by cassiel74** [comment]
Not really, if the clip is shorter than the mark in/out interval that workflow doesn't work and if I want to do some compositing (V1 + V2) I can't set the marker out beyond the last clip end on the timeline.

**Comment by jliljebl** [comment]
If I understood correctly what is wanted here is to avoid moving clips manually into correct position when building compositions at the end of the timeline.

Something that can done is to make current 'Insert Clip' from monitor functionality work so that when frame pointer is after the last clip of the top most active track a spacer clip is added from last clip end frame pointer position and clip is inserted at frame pointer as the new last clip.

This allows for the following workflow:

1. Move frame pointer to the end of the timeline
2. Insert clip on the track that has last active frame (mostly V1)
3. Change active track to be another track that has last clip end before the current frame pointer position
4. Press Insert Clip button
5. Spacer is added from clip and to frame pointer and clips is inserted at frame pointer.

Does this sound like what is looked for here?

Flowblade doesn't currently allow moving frame pointer beyond the end of the last clip on the timeline and that wont be changed. So if a composition is needed to exist after the end of the timeline, then first one has to created at the end of the timeline and moved with spacer tool.

**Comment by cassiel74** [comment]
It doesn't work here, the inserted clip (point 4) is being inserted after the last clip end (point 3) and no spacer is added.
I try to sort it out:

1. insert a 20s clip in V1
2. insert a 10s clip in V2
3. move frame pointer at 15s on the timeline 
4. load a 15s in clip monitor (or from "Range Log" items) with V2 being the active track, press "Insert Clip" 

Result: the clip is inserted but no spacer is added, ie the clip is not inserted at frame pointer but after the last clip end (on V2 of course).

Spacer is added only if I press "Overwrite range" and by using mark in/out, but if the mark in/out interval is larger than the clip duration (or viceversa) that doesn't work.
Hope this is clear.

Am I doing something wrong?

**Comment by jliljebl** [comment]
No, you are not doing anything wrong.

The workflow I described is the SUGGESTED workflow that will exist IN THE FUTURE after I DO THE PATCH that actually does the changes to how "Insert Clip" button works. 

The question is: Does this sound like that it would satisfy your use case?  If so, I'll add this to 1.4 milestone.

I thought that saying "Something that can done is to..." would make clear that this is not yet done, but it would probably have been better to start with "I propose i do a patch that changes Insert Clip..."

The "Overwrite Range" won't work for this and will not be changed.

**Comment by cassiel74** [comment]
Ok, I missed your point and thought it was my fault or a bug.
BTW yes, the patch you suggested does exactly what I meant.

**Comment by jliljebl** [comment]
Great, I'll take this on for milestone 1.4.

**Comment by cassiel74** [comment]
I post here a couple of things noticed during the past weeks that IMHO could be of some interest to face with (if you have not already done).

1. Sorting. When dealing with range logs, groups and bins for "large" projects as one attempts to use alphabetically significant names for those entities and having the sorting capability would be really useful.

2. Removing fades preserving clip length, ie just restore the original frames. 

3. Default filename when rendering. I think would be better to use sequence name as default filename instead of "movie" to avoid the overwriting of batch rendered sequences (when changed, the default filename becomes the last one used).

**Comment by jliljebl** [comment]
Fairly good points all, and actually quite feasible too. I can do these for 1.4. 

For point 2 it is a bit against my approach to make this the default delete option, because delete is delete, but I can make it a menu item in pop-up menu for fades and dissolves. It is also possible to give user the explicit Preferences option to select which kind delete is applied by default (when used presses Delete -key on fades and dissolves) so that if user wants this type delete to be default then it is possible.

**Comment by cassiel74** [comment]
For point 2,  IMO if you think about fades as an effect/filter most of the times users want to preserve clip length. You want to delete the effect not the frames it acts on, anyway, a preference option would cover both cases.

I am actually working on a "bigger" project (~1h length, 14 sequences), if you appreciate I can provide other feedbacks about overall usability.

**Comment by jliljebl** [comment]
Yes, feedback based on observations when using the tool is always valuable. The design is based almost entirely on my own test editing and knowledge of similar tools, and is therefore always necessarily  one sided.

You can file one or more Issues here, depending on the complexity and amount of observations and suggestions you wish to discuss.

**Comment by jliljebl** [comment]
> 2.Removing fades preserving clip length, ie just restore the original frames. 

Fades and transitions do this now, feature will be in 1.4

**Comment by jliljebl** [comment]
>Sorting. When dealing with range logs, groups and bins for "large" projects as one attempts to use 
> alphabetically significant names...

I added a separate Issue for this.

**Comment by jliljebl** [comment]
The original Issue "Insert clips at locator/mark position" will not be done because:

1) The new drag'n'drop overwrite on blank/empty functionality that will be in 1.4 will in my view mostly satisfy this use case. So you can:
- put clip in monitor
- set mark in, mark out
- drag'n'drop clip _from monitor_ to timeline on empty space/blank any non-V1 track and it will overwrite available blank/empty space

2)   "Overwrite Range" is quite close to the request, and we already have 4 different actions to put material on timeline from monitor, I do not wish to add another.

Closing this as fixed.
