### ISSUE TITLE
Scrolling Text [enhancement]

### ISSUE THREAD

**Issue by denjello** [jliljebl/flowblade#115]
I would love to be able to contribute a scrolling text (X,Y,Z) method. Any thoughts on this?

**Comment by jliljebl** [comment]
Hi danjello,

Sorry for the delay on this. There are a few possibilities do texts on flowblade.

You can use the http://www.mltframework.org/bin/view/MLT/ProducerPango#outline Pango producer and add it as a 'Pattern Producer' in Flowblade speak, you can examine file  https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/Flowblade/patternproducer.py for more info on how to do this.

Another possibility is use Titler code as a starting point, see: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/Flowblade/tools/titler.py

Do you mean like end texts scroll because that probably does not have a Z component in it, or do think of some animated text thing where texts fly in to the frame etc?

**Comment by denjello** [comment]
For the record, I ended up using the following ffmpeg command (to scroll the text from right to left at the top of the screen on a premade white mp4 file:

```
ffmpeg -i white.mp4 -vf "drawtext=fontsize=20:fontfile=~/.fonts/truetype/msttcorefonts/Arial_Bold.ttf:textfile=scroller.txt:fontcolor=black@1.0:fontsize=40:y=line_h-5:x=-50*t+1350" -y text.mp4
```

I'll look into the titler.py code and see what I can come up with.

**Comment by jliljebl** [comment]
This does not seem to be going forward, closing.
