### ISSUE TITLE
Out marker in wrong position

### ISSUE THREAD

**Issue by cassiel74** [jliljebl/flowblade#123]
Working on a simple project with latest git code (actually commit 94f69ce9d4af47df1f4d1dcbff5bdc844a98f6eb).

Placing "In" marker works fine but "Out" marker is wrongly placed on the timeline:
1. set the current frame at 1:00
2. press "O"
3. the "Out" marker is placed at 1:01

**Comment by jliljebl** [comment]
This Issue is invalid, Mark Out  works as designed.

The reasoning is as follows:

1) When user sets Mark Out, the user wants the select and see displayed the last frame that is part of the range/clip created. This last frame is _inclusive_, part of the range created.

2) When displayed on Timeline/Monitor the Mark Out has to be _after_ the last frame that is part of the range to show that this last frame is part of the frame. So Mark Out  is _exclusive_ when displayed on GUI,  meaning not part of the selected range

3) To satisfy equation length = out - in, then Mark Out frame number has to be _exclusive_.

All and all this leads to the way things currently function. When user selects frame X on timeline, and hits Mark Out there, the frame for Mark Out gets set as X + 1.
