### ISSUE TITLE
Filters do not work

### ISSUE THREAD

**Issue by cassiel74** [jliljebl/flowblade#124]
Latest git (commit 94f69ce9d4af47df1f4d1dcbff5bdc844a98f6eb)
None of the Alpha filters are working except for "Spill suppress".

**Comment by jliljebl** [comment]
This Issue is invalid.

Alpha channel in images exits for the sole purpose of compositing two images. If image is not part of a composite, the data in alpha channel has no purpose and does not affect output.

In Flowblade Alpha filters write into images alpha channel and has no effect unless used in combination with Compositors to combine two images.

Select "Add Compositor" -> "Dissolve" from clip popup menu to composite e.g. clip on track V2 on a clip on track V1 and add Alpha filter into clip on track V2 to see Alpha filters working.

**Comment by Efenstor** [comment]
I think this must be added into the FAQ. Spent half an hour today myself struggling to understand how to "turn on" alpha processing (I tried to do cropping).

**Comment by jliljebl** [comment]
Ok, I updated the F.A.Q.

**Comment by All-The-Foxes** [comment]
Is it not possible to crop massive black bars off of a video? The crop filter does nothing at all and the position scale tries to stretch the video out. I don't want to zoom the video, I want to cut off the massive black spaces on the sides of a vertical video. I've spent an hour now trying to figure it out and there doesn't seem to be a crop option.
