### ISSUE TITLE
live sound support

### ISSUE THREAD

**Issue by Reaper10** [jliljebl/flowblade#132]
I don't know if this is being worked on or not but live sound support would be good  to have, ie.
At the bottom of the Mixer could have a sound input menu on every audio track this way a user can hook up a hardware mixer to a flowblade audio track and record the sound form their hardware mixer without a DAW software. The folwblade mixer's faders and pan knob should be able to read & write volume  and pan automation on the track. A the top of the mixer there should be a output menu on every audio track this way a user can hook up a audio output from the flowblade mixer out to a jack audio input.
![a0f9a__flowblade-audio-mixer_thumb 1](https://cloud.githubusercontent.com/assets/8137561/8599707/aee1c5e8-2627-11e5-816a-e11f26c200e3.png)

**Comment by Reaper10** [comment]
I know I'm not much help because I don't how to code if I did I would be working on a windows port for you.

**Comment by jliljebl** [comment]
I'm marking this as wontfix for now, not because I don't think the feature would not be useful, but because this is definitely something that is not considered a priority at this moment. Even patches will not be accepted at this time, working on this would shift focus from other areas of development.

To Reaper10: The windows port would very likely be a quite difficult project requiring expert level knowledge on the subject of porting GTK applications to windows, so don't be sorry that you can't help, there are very few people who actually could help here.

**Comment by Reaper10** [comment]
that sad could It help to port it to qt

**Comment by Reaper10** [comment]
or https://www.youtube.com/watch?v=hFyszYbAJnM
