### ISSUE TITLE
Edit the length of parts by rightclicking [enhancement]

### ISSUE THREAD

**Issue by Miniellipse** [jliljebl/flowblade#138]
I somehow miss the possibility to change the length of parts by typing in the length in seconds. When using still images it will be a very useable thing. The possibility to put a part to a starting position by editing a value will also be appreciated ... :)
Or did i miss something and this is all possible and i have not fund it yet? :)

**Comment by jliljebl** [comment]
Are suggesting the following workflow?

1. Clip exists on timeline.
2. User right clicks on the clip and a popup menu is displayed
3. User selects item "Set Length" (or maybe "Trim Length")
4. Dialog window is displayed and user enters length as timecode like "3:01" or "301" for three seconds and one frame (It would be easier to do if length is given in frames instead of timecode)
5. Maybe there is dropdown menu with option "Trim end" and "Trim beginning" displayed in the dialog
6. User selects "Ok" (or "Set Length") and the length of the clip is changed as if a Trim was performed.

**Comment by Miniellipse** [comment]
Yes, i am lokking for something like that. 
It would also be nice (perhaps there is a function to do this, i am a flowblade-newbie and more in openshot and media studio) to have a delete-function and trim-function that leaves the clips right to that editing untouched. Its hard to have a video scene almost ready and one delete and all is shiftet to the left. There are not many youtube-videos really dealing with flowblade-tutorials, when i am better in flowblade i surely will do the one or another... :)
Thanks ...

**Comment by jliljebl** [comment]
> to have a delete-function and trim-function that leaves the clips right editing untouched. 

These do exist: 
* Use tool "Roll" to trim so that clips to right stay in the same position (select from tool selector or press 4 when timeline has keyboard focus)
* Use "Lift" button (or Edit -menu item) to remove clips so that  clip area is replaced with a blank clip

On the subject of the original feature request, I'm undecided if your suggestion is the correct way to move forward.

I think I'll eventually add some way to just drag the clips ends in such a way that you can only lengthen the clip on top of blank clip, but can't overwrite other clips or cause them to move to the right. This is not idiomatic to Flowblade workflow, but might be accepatble if presented as a separate tool of mode. I'm not going to do a mouse cursor that changes at clip ends to indicate available drag.

I'll leave this open unlabelled for now.

**Comment by jliljebl** [comment]
Release 1.4 will introduce a feature enabling user to drag clip ends in move modes by CTRL + Mouse Right, that will at least partially satisfy the request here, I'm closing the issue.
