### ISSUE TITLE
Flowblade renders pictures other way when using different codecs

### ISSUE THREAD

**Issue by Miniellipse** [jliljebl/flowblade#152]
When creating a flowblade-file with a still image in portrait the use of different codecs brings different results with these images.

I have put this together in a youtube-file

https://youtu.be/uoeVv-LS5qI

**Comment by jliljebl** [comment]
Ok, I see the difference, will investigate.

**Comment by jliljebl** [comment]
Only "Encoding Format" displaying the problem was "MPEG-4 / .mp4" and I was able to fix it by removing arg "s=%SCREENSIZE%" from my encoding definition.

You can test the solution immediately:

1. Select  "MPEG-4 / .mp4" as Encoding format
2. Check "Render using args" check box
3. Click "Load Selection" button
4. Remove line "s=1280x720"(this is w x h so actual values may be different) from list that appears in the text editor panel
5. Render

**Comment by Miniellipse** [comment]
Yes, works, thanks a lot! To use the "render using args", is there a "load selection" always needed and what exactly does this "loading selection" do?

**Comment by jliljebl** [comment]
> To use the "render using args", is there a "load selection" 
No, you can write any ffmpeg arguments you want.

>what exactly does this "loading selection" do
Load selection loads into editor the ffmpeg arguments that will used for rendering with current rendering settings.
