### ISSUE TITLE
Make filter, compositor or blend follow clips

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#156]
If you add a filter|compositor|blend to a clip and then move the clip the effect should follow the clip and not stay in its place...

**Comment by jliljebl** [comment]
After some thought I've decided to mark this wontfix, but I will add an application menu item *Sync all Compositors* that syncs all compositor with their origin clips in one action.

So currently filters are attached to clips, but compositors are independent timeline objects. Compositors do remember their creator clip, and can be synched with it by doing *Mouse Right* on compositor and selecting from pop-up menu item: *Sync with Origin Clip*.

I have however decided to not make Compositors move with clips in the 1.X series of releases. I could state a lot of reasons but all reasons can be divided into 2 categories:a) I don't think this would be in line with the UX and logical design of application as it is, b) it would require a lot of work that I believe could be used better on other issues.

**Comment by jliljebl** [comment]
Reopen for  Sync all Compositors feature. I'm trying this for 1.4.

**Comment by jliljebl** [comment]
Close again, and open a separate Issue.

**Comment by ftrotter** [comment]
You have chosen to address what is clearly a violation of user expectations by creating an undocumented fix. So now there is a "sync" feature whose results are impossible to interpret in the interface, which is a fix for a problem that is created by counter-intuitive interface design. 

This bug should be reopened, because it was not fixed. It was not even "notfixed" it was just "muddied"

-FT
