### ISSUE TITLE
Render inverted clip

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#158]
hi

would it be possible to add to the roadmap motion effect tools like speed and invert (playbackwards)?

thanks

**Comment by jliljebl** [comment]
This can added as a rendered clip functionality at some point.

**Comment by bergamote** [comment]
I just needed this feature and instead of re-rendering my clip reversed with avidemux, I followed the framebuffer method mentioned in [MLT's FAQ](http://www.mltframework.org/bin/view/MLT/Questions#How_to_reverse_a_movie_e_g_have):

    melt framebuffer:/path/to/video reverse=1 -consumer xml:reverse.mlt

It only took a couple of seconds and to my surprise, I could then import the *.mlt* file directly in flowblade!
So what I'm saying is, having the speed slider going all the way back to -100% and beyond would indeed be great. But when doing a straightforward reverse, not having to re-encode the whole video seems like a massive advantage.

**Comment by jliljebl** [comment]
We will have rendered inverted clips feature available in 1.14. 

The "-consumer xml:reverse.mlt" solution mentioned by @bergamote has a massive down side with "overwrite profile" behavior in current available MLT versions, see here https://github.com/mltframework/mlt/issues/212

A long time in the future it could be used, but not now, because option to avoid profile overwrite was added.
