### ISSUE TITLE
integrate movit into flowblade

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#165]
would this be possible? it seems you will need a git version of mlt and configure it with --enable-opengl as it says in the developers website. http://movit.sesse.net/

more info about movit:
http://movit.sesse.net/movit-fosdem2014.pdf

**Comment by jliljebl** [comment]
Yes this is possible, eventually.

For this to work the application needs to use the MLT OpenGL display consumer instead of the SDL consumer Flowblade uses. And I understand that to get the OpenGL consumer working on Flowblade, the Python Swig bindings would need a way to do calllback from MLT to application, and this is not supported currently.

Also, on my system the Shotcut GPU rendering has been very crashy, and I'm not willing to do changes that carry clear threat of of destabilizing Flowblade. 

So this will be attempted eventually, but not in the immediate future.

**Comment by faridosc** [comment]
maybe for 1.8 or 2.0

**Comment by jliljebl** [comment]
Probably earliest 1.12. I think I'll go on with 1.X series to maybe 1.18 or more.

**Comment by faridosc** [comment]
probably by then things will be more mature and stable.

**Comment by jliljebl** [comment]
I'm closing this for now, will reopen when issue is more current

**Comment by jliljebl** [comment]
This is will be worked on eventually.
