### ISSUE TITLE
Add option to render as image sequence

### ISSUE THREAD

**Issue by faridosc** [jliljebl/flowblade#169]
Also would be nice to choose format (png or jpg) and compression/quality. If you'd like to take blender as reference. I can elaborate on this if interested.

**Comment by jliljebl** [comment]
So you can already render image sequences if you select in render panel from "Type:" option "Preset File Type" and then from "Presets:" for example "Image Sequence PNG".

There are no quality options available, but I will look into what kind of preset quality choices could made available to users. It may be that  MLT does not provide the needed functionality. I'm leaving this open until I have looked into this a bit more.

I'm not willing to do any conceptual changes to rendering GUI atm, only additions, any changes here will come with big work cost.

**Comment by faridosc** [comment]
if you wanna close it and open it later that is fine.

cheers

**Comment by jliljebl** [comment]
I'm closing this as wontfix because it sees that it is not possible to affect encoding quality when using MLT/Ffpeg to render output as frame sequences. 

Series of internet searches offered no examples of anyone setting any quality parameters using ffmpeg command line parameters, only some other attributes were found to be settable, see here: https://www.ffmpeg.org/ffmpeg-codecs.html#png

Blender must use some other method for frame sequence encoding that makes possible to control quality parameters of rendered frames.

**Comment by fuxoft** [comment]
When I try to render movie as "Image sequence PNG", the rendering starts but never ends, while "Estimated left" time keeps going up and progress indicator stays at 1% (while processor load is zero). Only 1 image ("movie.png") is created in my render directory. What am I doing wrong? This is version 1.12 on Linux.

**Comment by jliljebl** [comment]
Ok, seems that this has broken. I opened a new issue on this. Fucking hell, stuff breaks upstream, it is difficult to keep an eye on all the possible changes.

**Comment by jliljebl** [comment]
Ok, fixed now. Upstream stopped accepting under specified render consumers, had to provide better info.
