### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by xXSIGXx** [jliljebl/flowblade#171]
I looked around and didn't find any documentation on this issue, so I decided to report it. Flowblade worked fine before, but for some reason has stopped. I've tried uninstalling and reinstalling it multiple times and can't get it to work. I have no idea what the issue could be. I've tried running it as root and running it with a terminal in /usr/share/flowblade/Flowblade but it all gives the same text as shown. Help would be appreciated.
![flowbladeerror](https://cloud.githubusercontent.com/assets/15224065/10628330/2a023454-7792-11e5-8166-733a16e1f7ee.png)

**Comment by jliljebl** [comment]
This seems like install/environment related issue. The version 0.14 was released over a year ago, it still uses GTK2, and cannot be supported with available resources after the application was ported to GTK3.

I'm marking this wontfix because there is no reasonable course of action that can be taken on this that also moves the project forward.
