### ISSUE TITLE
No tone rendered

### ISSUE THREAD

**Issue by schuessm** [jliljebl/flowblade#180]
I can only render with the mpg2 profile, all other profile genereate the video without tone. When i use the "render using args" option and set the audio codec to mp2 it work also e.g. with mpeg4. otherwise not. All depencies are installed.

That my options:
f=mp4
acodec=mp2
ab=384k
vcodec=mpeg4
minrate=0
vb=12000k
bf=2
b_strategy=1
trellis=1

the mpeg4 standard uses:
f=mp4
hq=1
acodec=mp2
ab=192k
vcodec=mpeg4
minrate=0
vb=3000k

**Comment by jliljebl** [comment]
Based on another issue it is assumed that this is displayed on Linux Mint 17.2 and the problem is related to that environment, not Flowblade code.

Anyway Ubuntu 14.04 LTS is not supported, if Mint 17.2 is based on that, then your OS is not supported. I have to drop Linux Mint 17.x from supported OSes.
