### ISSUE TITLE
Version 1.0 as deb

### ISSUE THREAD

**Issue by schuessm** [jliljebl/flowblade#181]
@jliljebl  it is possible to download the Version 1.0-DEB File? Because I'm on mint 17.2/Ubuntu14.04 and I won't change because of LTS .

Thank you!

**Comment by schuessm** [comment]
I found. But there is nothing different to 1.4. Some videos are shown some not. Look at the attached screenshot
![bildschirmfoto vom 2015-12-03 19 39 11](https://cloud.githubusercontent.com/assets/16079397/11570086/a14f8ba8-99f5-11e5-8677-3c936f615be9.png)

**Comment by jliljebl** [comment]
Seems you still have the same problem, so the problem is not GTK version related. I am sure that this is a problem in the Linux Mint OS, because the problem is that swascaler complained about frames that very delivered to it by MLT/ffmpeg. All Flowblade does is to use MLT to accomplice the task of creating thumbnails and for some files it works and others it doesn't. Upgrading to latest versions in all relevant libraries should fix this. I hope that the next version of Linux Mint will work in this regard.
