### ISSUE TITLE
(awesome WM bug) Selecting clip in timeline often blocks ability to drag / move / select tracks

### ISSUE THREAD

**Issue by qubodup** [jliljebl/flowblade#188]
When I try to work with the timeline, I often have problems dragging clips in it while a clip is selected. Instead of moving the clip, an icon appears and is moved. Often I am unable to de-select the clip by clickin it as well.

Instead of the desired action, a File move or file copy icon appears.

Video: https://youtu.be/1Fclom9NUKU

flowblade-git v1.0.r228.ga4656a1-1

OS: arch linux 64bit
WM: awesome wm

**Comment by jliljebl** [comment]
This happens if you drag the the mouse outside of timeline, and a clip drag to "Range Log" is initiated. You are very likely dragging with a semicircular motion that briefly leaves the timeline area.

Please do a test, 1) first carefully drag clips so that the mouse surely stays inside the timeline, 2) next do a drag that briefly leaves the timelime, and you will see the drag icon appers.

If the icons appears when mouse stays inside the timeline, add a comment here. 

I will attempt to add a mechanism that stops the drag and returns clip dragging when mouse returns to timelime. Meanwhile you will need to adjust your mouse movement to always stay inside timeline when dragging, it becomes second nature after a while.

**Comment by jliljebl** [comment]
Ok, didn't watch the video before writing the earlier now deleted comment because i didn't notice the video link, sorry if you got the mail notification. 

1) Does this happen when you use other WMs
2) Does terminal print anything when you do the drag.

This seems very strange to me, I'm not yet able to understand the possible mechanism for this to appear. Thanks for the video, I didn't believe this to be possible without the video evidence.

**Comment by jliljebl** [comment]
The file icon is only programmed to appear if 'leave-notify-event' is fired on a Gtk.DrawingArea when mouse leaves the widget. I'm really curious if this happens on Gnome3/Unity/Cinnamon, please test.

**Comment by jliljebl** [comment]
I remembered that I actually had awesome installed and yes, the bug appered just like in your video.

I'm inclined to believe that this is an awesome bug, it is not reporting mouse events correctly.

If you can find Flowblade file 'tlineaction.py' comment out lines near line 771 and add word 'pass' as shown below for quick fix:

def mouse_dragged_out(event):
    pass
    #if movemodes.selected_range_in != -1:
    #    movemodes.clips_drag_out_started(event)

I'm not going to remove functionality to appease buggy WMs

**Comment by qubodup** [comment]
Thanks for clarifying. Can you conclude what the bug in awesome might be? I could then report upstream https://awesome.naquadah.org/bugs/

**Comment by jliljebl** [comment]
The problem causing the bug you are experiencing is that  'leave-notify-event' signal is fired on a Gtk.DrawingArea widget used to display the timeline even when the mouse pointer does not leave the area of the widget. It also may be relevant here that Flowblade uses Python gindings to GTK3 toolkit.

**Comment by jliljebl** [comment]
I'm closing this as a known issue.
