### ISSUE TITLE
One processor working at 100 percent only for showing workbench

### ISSUE THREAD

**Issue by Miniellipse** [jliljebl/flowblade#194]
I have loaded an old project, looked a bit, and the processor is at 100 percent (one core) without any needed calculations. I have recognized this in other videoedit-programs as well (Open Shot), it makes the computer loud and uses energy. Any ways to avoid that?
What is while rendering, is the one core blocked for the calculation then being used for something on the gui?

**Comment by Miniellipse** [comment]
Here an video showing it. Please note: The processor is used for recording this video with ffmpeg, too. In "normal life" its one core at 100 percent.

https://www.youtube.com/watch?v=BETOM9jW8Z4

**Comment by jliljebl** [comment]
Basically as soon as you launch the application it starts displaying frames at current profile frame rate, it does not matter whether or not the playback is on. I've made an attempt to change this a few years a go, but results were not satisfactory, there was a noticeable loss of responsiveness.

Closing this as wontfix as I'm currently not planning to visit this again because this has a potential to cause a multitude of bugs and behaviour changes.
