### ISSUE TITLE
import media error

### ISSUE THREAD

**Issue by lsnd** [jliljebl/flowblade#201]
Hi I've just installed flowblade 1.4 on linux mint 17.2 and I'm really impressed by it, really good and easy to use  at the same time not heavy. 
I first installed it on same distro but the hard disk happened to be damaged and started to give a lot of unprovoked crashed so i had to replace it. And when I tried to proceed from where i left it the flowblade wouldn't load the mp4 file I was working with before the reinstall.
The message says:
![untitled](https://cloud.githubusercontent.com/assets/17046828/12784771/c7ea8412-ca91-11e5-8e77-7c2c12f201d7.png)
The only difference I could think of was that on the previous system I've installed some codec for vlc player i frankly don't remember witch one as there was some unsuccessful ones.
So is there some universal video codec or a way to import mp4 file?

**Comment by jliljebl** [comment]
Some pointers that might help:

1)Give command: 

sudo apt-get install -f      

on terminal, for some reason Linux Mint fails to install dependencies when the .deb distributed here is used, this was said in the install instructions page.

2) Install Kdenlive which may should bring in some dependencies needed. Also installing all possible media programs may help. 

I unfortunately have to close this as 'invalid' because the Issues here are meant only for problems that can be fixed by changing the Flowblade source code. Codec installation on different Linux OSes is a huge topic and cannot be covered within the scope of this project.

**Comment by lsnd** [comment]
I couldn't figure out what exactly was the reason causing it but found out that installing couple others video editors from the software manager seems to fix the issue.
