### ISSUE TITLE
Enable changing sequence parameters

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#209]
Currently, sequence parameters (video resolution, aspect ratio, framerate) can only be set when creating a new project. It is not possible to change the parameters once the project is created. The problem is not resolved by unchecking the _Use project's profile_ option at render and selecting another standard because the setting is not honored (see the next issue).

**Comment by jliljebl** [comment]
It will not be possible to have separate profiles for different sequences in the same project. It is considered logically wrong as profile is firmly established as an attribute of the project. 

What will be attempted for 1.8 is a _special project save operation_ that makes possible to change profile for  the _saved_ project. This is however not guaranteed to succeed, let's see how it goes.

Changing profile at runtime for the currently open project is essentially impossible, all clips hold references to MLT profile C-structs, and cannot be  touched while data is in memory.

The mentioned bug was fixed. Closing this as _wontfix_ because sequences will not get separate profiles.
