### ISSUE TITLE
Communicate that "log range" only works on clips

### ISSUE THREAD

**Issue by protonenfalter** [jliljebl/flowblade#239]
environment:
flowblade 1.6.0 on Ubuntu 14.04 and Ubuntu 16.04 (as standalone and through .deb)

workflow:
- add medium (video as .mp4)
- put medium on video track
- add begin and end marker at some points in time
- chose tab "range"
- press button "log range" or press ctrl+l

expected result:
newly logged range in list of ranges

actual result:
nothing, neither button nor keys seem to do anything, list of ranges stays empty, no message in gui nor in console

**Comment by mclaudt** [comment]
Yes, that's quite misleading. In fact, there are two mutually exclusive modes of mark placement: "Display Current Sequence On Timeline" (1) and "Display Monitor Clip" (2).
![pic](https://cloud.githubusercontent.com/assets/8770359/16180449/8ff5590c-368d-11e6-87fc-f59baa21b23f.png)
 "Log range" works only for the latter, namely when it is active.

That is reasonable because you should be able to mark immutable source clips only, not your mutable sequence.

Of course, the interface could be improved to make it more explicit and visually intuitive.

**Comment by jliljebl** [comment]
Yes, the UI could communicate better that "Range Log" is actually "Clip Range Log", only meant to log media item ranges. I changed the item title.

 Actually in my my view logging timeline ranges is nonsensical and I didn't anticipate that someone would attempt that. Well, this a bit GUI Murphy's law, if it can be tried someone will try it.

**Comment by jliljebl** [comment]
I have no ideas on how to improve this, and I'm closing this as wontfix. If I get some better ideas I will return to issue.
