### ISSUE TITLE
Tool integration

### ISSUE THREAD

**Issue by sozap** [jliljebl/flowblade#252]
Hello,

I've seen in the roadmap that there is interest in integrating Natron in Flowblade.
I think it's a great idea and there are many people waiting for Natron integration inside some NLE to act like a kind of Nuke Studio.
So maybe rather than having some kind of an headless control of Natron inside Flowblade (like a title generator) it would be way more useful to let user create custom workflows and associate some application + some python scripts to a clip in the timeline. Maybe it could be like applying an effect to a clip. Then it would be great to be able to open Natron from the timeline , apply some effects to the shot and render it outside or inside Flowblade. Then having the result inside the Flowblade timeline.
The best would be to be able to lauch some scripts when opening a Natron project , and/or at render time. That way it open the door to great customisation for integration in some professional open-source pipeline.
If this system is generic enough , it may allow to plug other applications than Natron, like Blender or other commercial application, or for instance some imagemagick process on a image sequence.  
I've looked into several open-source NLE and none of them allow this kind of workflow that is very useful for animation or VFX work. Only blender with the VSE is able to do some scripting stuff and let the user link any applications to some shots.
If you think that idea is useful I can make a real proposal and better design on how this could work.

**Comment by akhilman** [comment]
Take a look how BorisFX integrates to Adobe Premiere
https://youtu.be/wNxxlOg2B6w
In Natron side Flowblade could create input nodes for and a kind of time source to control transition timing.
Such workflow not limited to transitions, any compositing can be made like this.

**Comment by sozap** [comment]
Hey, that's illustrate perfectly what I had in mind !

**Comment by akhilman** [comment]
Possible implementation:

1. Implement clip hash
2. Integration API / Abstract implementation
3. Plug-in using integration API for Natron

### Clip hash
Each clip could have hash calculated from all variables associated with this clip. So we will know is clip moved, trimmed or is any associated filter parameters changed. This also will help to implement preview caching to speed-up playback.

### Integration API
Provides abstract implementation for:
- Compositing filter
- Video filter
- Audio filter

Abstract Implementation should:
- Watch if hash of input clips changed
- Prepare/render input clips (only parts of clips required to make transition)
- Generate scene file for third party compositor
- Launch third party compositor with generated scene
- Update scene for third party compositor if input clips or timing changed
- Launch background rendering with third party compositor
- Show rendered clip in Flowblade preview or big red cross if compositing should be re-rendered

With such API will be easy to implement plug-ins for Natron, Blender and also for Synfig.
Synfig is a nice tool for videographics.

Clip hashes will also open wide possibilities to integrate external audio editors like Ardour or RosenGarden. Main idea it to keep clips in sync between Flowblade and external editor.

**Comment by jliljebl** [comment]
Thanks for your input one this. I'm just ending the summer break and reactivating on the project, and started out by looking at your ideas today.

In my view the situation is that the exact work flow described in the BorisFX video is not doable currently because on my initial inspection Natron does not provide an IPC mechanism to request renders or change parameters on a scene that is open in the GUI .

So I cannot communicate changes in clip lengths or parameters and request re-renders from Flowblade side to Natron. The BorisFX people have obviously created such a mechanism for the exact purpose of deep editor integration, and if such a interface is provided by Natron in the future I will certainly try to use it. 

But Natron API does provide a startup script functionality with a lot of control of scene parameters and callback functions for render completion events, so it is possible to communicate from Natron side to Flowblade to request updates.

http://natron.readthedocs.io/en/master/devel/startupscripts.html

This enables *some level* of integration between the two applications. The question is what is the most that can be done if it is possible to:

* create and open any kind of scene from Flowblade side to Natron GUI app
* work on this scene and render it on Natron side
* do updates on Flowblade side on Natron render completion events.

I'll have to think this over. If you have any ideas I will glad to hear them. I'm sure something can be achieved here.

As stated before, the headless NatronEngineAPI obivously makes it possible to add rendered effects on Flowblade timeline clips that can be updated on request. 

The catch is that the clip will always need to point to a hidden rendered image sequence instead of the original material, but this can be done even thought it gets a bit complex. So adding a Natron effect to a clip changes the clip from normal video clip to a hidden image sequence here, but this still may be done in a usable way. 

Also using a "Natron effect" together with normal clip effects is one of those things that even thought possible in principle are probably not worth the major effort.

After writing this  I have come to believe that some form of integration with the GUI app instead of the headless rendering thing may provide more utility to users and might actually be easier to do, so I will be looking at that first.

**Comment by akhilman** [comment]
Some more background.
I have no experience in Natron but I done some video with VFX in Blender's sequencer and compositor.

Work flow in my case looks like:
1. Do NLE and setup timing
2. Insert same clips into compositor and set clip start/stop timecode to be same as in NLE sequencer
3. Do compositing
4. Render composition and replace original clip with composed one.
in case if later decide to change timing I'll have to:
5. replace composed clip by original clip
6. Redo again steps 1-4

In this scenario I never need to do job in NLE and Compositor same time. So steps 2 and 4 could be automated. NLE could prepare/update composition and fire up compositor. When composition will be complete it will update clip by rendered result. Also optionally NLE could start background render with compositor if composition file newer then rendered composition.

It's more like editing same document in two different editors. Vim for example pops warning if open document changed by another process and asks is it should load new version.

> Natron does not provide an IPC mechanism to request renders or change parameters on a scene that is open in the GUI .

> But Natron API does provide a startup script functionality with a lot of control of scene parameters

Blender also have rich API and startup script. Actually I have experience to implement IPC using blender 2.3*'s API (old one). We can generate script which will create template for composition with prepared input and output nodes or update exist composition to reflect changes in timing and then execute compositor with this script.

Synfig AFAIK has no API, but composition is a simple XML file and could be easily generated and updated. I wrote GIMP to Synfig exporter plug-in long time ago.


> • do updates on Flowblade side on Natron render completion events

We can watch output file changes.

> Also using a "Natron effect" together with normal clip effects is one of those things that even thought possible in principle are probably not worth the major effort.

We can restrict more then one external compositing effect. All Flowblade filters before this effect will be rendered to composition source clips, all filters after this effect will be applied to rendered composition.

PS: please do not consider this feature more important then any another.

**Comment by jliljebl** [comment]
>Work flow in my case looks like:
>1. Do NLE and setup timing
>2. Insert same clips into compositor and set clip start/stop timecode to be same as in NLE >sequencer
>3. Do compositing
>4. Render composition and replace original clip with composed one.
>in case if later decide to change timing I'll have to:
>5. replace composed clip by original clip
>6. Redo again steps 1-4

Yes, this boils down to using each tool for the task it is best suited for, and now we are looking for ways to improve users workflow by offering some kind of integration mechanism between the two applications, the NLE and the Compositor.

I think there are three levels of integration here:

1) *Shallow Integration a.k.a clip sequence export.* Here we simply offer user the options like "Open Timeline Range in Natron" or "Open Selected Clips in Natron", and leave it up to the user to do compositing, render output and open results in Flowblade to replace to exported sequnce. This is basically your step 2. This can be done now and is cognitively easy for the user.

2) *Midlevel Integration a.k.a  clip sequence export and automated import of results on request or on render completion event* Some form of this can be done with available NatronAPI. The main design problem is to solve the following problem: *1)User exports clip sequence, 2) User changes timeline after export, 3) User does composition and renders it 4)How will the result now be imported?* This is actually a very difficult problem to solve conclusively if user is allowed to do arbitrary modifications, for example what if user moves the sequence to another track and deletes a single clip from middle of it, what is the correct import action now? Trying to cover all the possible cases here can easily require tens of hours. The only simple solution is to refuse to do automatic import if any modifications are done, and leave user to do the import manually. Maybe the case where the exported sequence is found to be moved but otherwise unmodified  could be allowed. 

3) "Deep integration" This is basically the BorisFX video from above. If an IPC mechanism is available this can be done, but doing it would be a major undertaking as all possible types of timeline modifications need to be covered.

There are other possible forms of integration too:

4) *Rendered effects for clips*. You had an approach for this:

>All Flowblade filters before this effect will be rendered to composition source clips, all filters after >this effect will be applied to rendered composition.

After some consideration I think that due to internal architecture of the application this is a practical impossibility

5) *Rendered Composition effects" These would be selectable from current rendered transitions functionality. This would use headless Natron to render effect transitions using resource file compositions. From application architecture point of view this quite easy.

6) *Stand alone effects tool* This would be in some ways like the current "GMIC Effects" tool and would share a lot of code with it. The major draw for me would be to provide users with the ability to create animated texts and export them as image sequnces. Unfortunately importing results as clips is currently not possible.

>Blender also have rich API and startup script. Actually I have experience to implement IPC using >blender 2.3*'s API (old one). We can generate script which will create template for composition with >prepared input and output nodes or update exist composition to reflect changes in timing and then >execute compositor with this script.

Ok I'll give it another look, but last time checked I seem to recall that they actually removed some stuff from the API, but maybe I'm wrong.

One thing that is relevant her is that I'm going to re-activate on the EDL export feature.

I worked on it a few years go and got it sort of working, but the problem was that the only import target was Blender and there were some problems and in my view Blenders EDL import functionality was buggy. I may have been wrong, but didn't have an easy way of knowing, so I just sort a gave up. Now the situation has changed:

* Blackmagic Fusion (former Eyeon Fusion) has been released as free download for Linux (still closed source). I have it installed and working, so now I have two export targets, and will be able to to see which are my bugs and which are problems in the target application
* Shotcut released a EDL export feature which I will be able to exploit in some way when implementing the feature.

So now I have a related feature:

7) *Implement EDL export*

> PS: please do not consider this feature more important then any another.

I have two criteria to decide "what is important" a.k.a "what I will work on next": utility to user and the required work. I actually wrote at length here to help me asses just these factors for each way of doing integration with Natron, and it worked, I now have a roadmap.

*Category 1: These features  will be worked on first*

1) *Shallow Integration a.k.a clip sequence export.* This will be useful on its own, is needed before trying 2) or 3) and is relatively easy to program.

6) *Stand alone effects tool* I really want those animated texts, and I'm quite sure that my "casual editors" users want them too. This is also much easier to do now that "GMIC Effects" code can be used as a starting point

7) *Implement EDL export* I sort of ran out of excuses to not doing this, this eventually will be needed to do as sort of basic functionality and might be more fun this time around with more available context

*Category 2: Will attempted at some point after completion of Category 1*

2) *Midlevel Integration a.k.a  clip sequence export and automated import of results on request or on render completion event* This needs to be before trying 3) anyway, and it is not guaranteed that any IPC mechanism will become available

*Category 3: Maybe down the line*

3) "Deep integration" Needs functionality not currently available, and needs 2) to be done first
5) *Rendered Composition effects" Can be done, but not hugely useful in my view.

*Category 4: Not feasible*

4) *Rendered effects for clips*. This is very difficult and in my view not that useful

I think reasonable esimate for how long it will take to do *Category 1* is 2-4 release cycles, which means probably "done by sometime 2017", so I'm only marking this with "Future" milestone now.

**Comment by jliljebl** [comment]
The previous comment was quite lengthy, so here is a tl;dr of central information.
 
**Natron integration roadmap**

First:
*  **Open Selected Clips in Natron** feature that launches the Natron GUI with clips imported
*   **Natron Effects tool** A stand alone effects tool like "GMIC Effects" with particular focus on text animations
* **EDL export** This is both easier and more beneficial to do now

Second:
* **Auto import rendered result from Natron** After the Natron composition from exported clip sequence has been rendered it is automatically imported on the timeline if feasible.

ETA for tasks in group *First* is second half of 2017, maybe even earlier.

Other considered tasks will be re-evaluated later.

**Comment by akhilman** [comment]
I played a little bit with GMIC Effects and rendered transitions and now have some ideas.

GMIC Effects in current implementation is actually stand alone tool. If I would like to apply such effect I have to:
* Every time select where to store rendered file
* Every time put rendered clip to timeline
* And most of all I have to do it and setup effects again if I decide to change something.

Same with rendered transitions. I have to set duration and video codec each time I change something.

And here is my suggestion.

What if we make special kind of video clip, for example `GMIC Effect`. It stores how to produce effect, which video tracks use as source and as any clip has start and stop time. Now we can disable this clip, re-time underlaid video clips and re-render result with updated sources. Same workflow can by applied to external compositing tools with only one difference – we can provide multiple input tracks. This special video clip sits above source sequence and simply replaces it with rendered result as expected.

Same work flow can be used even for titling or just for `Cache clip` which will provide ability to pre-render slow effects, compositions and transitions.

Rendered transition works almost like that. It restores original clips after deletion. But we can not change something and re-render result without removing transition.

Also Flowblade bothers me by ask video codec each time as I add new transition and when asks me were to store titiles. Codec could be defined in preferences. All temporary files could be stored in to project directory and removed as soon as I remove it's representation in timeline..

**Comment by tin2tin** [comment]
On EDL export, it has now ben added to Shotcut: https://github.com/mltframework/shotcut/search?utf8=%E2%9C%93&q=edl
Which is quite nifty, since Davinci supports EDL import, so your grade your edits there and through importing edl files in blender and exporting them with this script: (http://blendervelvets.org/en/blue-velvet/) you can import your sound edits to Ardour and edit your sounds to a videoclip in sync. I'm not sure EDL reading in Natron would be beneficial for Natron, but using it as assisting application might be. This is how that stuff is done in Lightworks: https://www.lwks.com/index.php?option=com_kunena&func=view&catid=7&id=108049&Itemid=81#111018

**Comment by jliljebl** [comment]
@akhilman 

> What if we make special kind of video clip, for example GMIC Effect....

Here's the approach I'm thinking, it adheres to the model of shallow-midlevel-deep integration describeded above.

**Before effects rendering**
* Clips offer options like **Open in Natron** or **Open in GMIC Effects tool** that opens clips in tools with in/out data preserved

This is level *shallow integration*.

**During effects rendering**
* On *shallow integration* and *midlevel integration* nothing, on *deep integration* IPC or file polling could be used to display progress bar

**After effects rendering**
* On *shallow integration*, nothing.
* On  *midlevel integration* and *deep integration* levels timeline is automatically updated with render results
* The  *midlevel integration* can be improved in a way similar to your suggestion by:
  * saving the in/out data and original media path as properties of the new rendered clip
  * saving the render transform data, e.g. GMIC Script or Natron project file as properties of the new rendered clip
  * this improves the editing experience in two ways:
    1. User can go back to original media in a single edit at anytime, without first doing  1- n undo actions
    2. User can do an updated version of the effect, without first doing  1- n undo actions to go back to original media
* On *deep integration* levels lengthening clip beyond available rendered media would automatically initiate re-render

I believe the prudent approach is to add features with increasing level of integration while maintaining stability, e.g. we currently cannot even open a clip in GMIC Effects editor with in/out data preserved.

Going on an abstraction, API,  or type creating programming rampage is in my view ill advised from code quality and stability POV.

Your suggestion of essentially container clips with multiple inputs, internal state and heavy serialization needs can only be assessed down the line after at least the *midlevel integration* level discussed here has been achieved.

@tin2tin 

> On EDL export, it has now ben added to Shotcut: https://github.com/mltframework/shotcut/search?utf8=%E2%9C%93&q=edl

Ok, 6K lines Javasccript...so doing a straight port is out of the question. A lot of the code seems to be boilerplate caused by the approach taken, which has probably been dictated by cross platform compatibility needs.

As a first try I will see if I can run the code as is or with slight modifications to do the MLT XML to EDL conversion. After that if needed I will return to my original code, which does not and will not support transitions and use this as a reference.

> https://www.lwks.com/index.php?option=com_kunena&func=view&catid=7&id=108049&Itemid=81#111018

This can in my view characterized as "container clips light" without much integration, similar to approach by @akhilman. Doing something like this will thought about at a later date.

**Comment by tin2tin** [comment]
I think Dan ported mlt2edl to node.js(and corrected errors along the way). https://github.com/mltframework/shotcut/blob/172e2e020bba1d75bebedce84633f049d14bead9/src/qml/export-edl/mlt2edl.js
Most of the script is reading the mlt file and it's less that 300 lines of code, but you have already been working on an edl export solution, if I remember correctly, where did you hit a dead end?

**Comment by jliljebl** [comment]
My code seems to already be port of mlt2edl.js or some similar earlier code:

https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/Flowblade/exporting.py

I don't remember what the exact problem was but I think I was experincing some off-by-one errors when opening the EDL in Blender.

I'll probably continue from my own existing code.

**Comment by tin2tin** [comment]
If you want ME to test a flowblade exported edl against various programs , just post it here and perhaps a link to the footage you edited.

**Comment by sozap** [comment]
Hello,
That's taking shape, that's cool to have a bridge between FlowBlade and Natron, and EDL import/export can be nice to have also.
Thank you for taking all that into consideration !

**Comment by jliljebl** [comment]
@tin2tin Ok, thanks, I did few EDL patches and will do a few more next week. After that I should have something that can be tested, I'll comment here then.

@sozap yes, this has started moving but will take probably a year to reach the midlevel integration target, let's see how it goes.

**Comment by jliljebl** [comment]
@tin2tin Flowblade is now exporting exactly like Shotcut, but Blender does not in my view import correctly from either.

Could you test if you get the same output when you import media and EDL into some other programs, required files below.

Video file ANGEL:
https://www.dropbox.com/s/fopx2nlef8nl567/angel_24.mp4?dl=0

Video file NIGHT:
https://www.dropbox.com/s/x3ijhh1x93g0hxm/night_24.mp4?dl=0

Test project EDL:
https://www.dropbox.com/s/6s50xs0kvau7yft/edl_1080p_24fps_test.edl?dl=0

Test project render:
https://www.dropbox.com/s/bgy036j1qhgfgfg/edl_1080p_24fps_test.mp4?dl=0

Project profile was 1080p, 24fps. Do you get the same output after importing EDL and media,  and rendering project?

**Comment by tin2tin** [comment]
Just looking at your edl file, I think you should check that each column is the exact number of characters and there is the exact number of characters between them as mentioned in this document on page 12: http://xmil.biz/EDL-X/CMX3600.pdf

The trouble with importing in Blender is that your source files contains space/underscore and that is not an allowed character and an X inserted, so now the reel name in the edl doesn't match the file name (Blender is not using the "* FROM CLIP NAME: night_24.mp4" line for import, but other softwares do - like Davinci). Only A -> 9 are valid characters for reel/file names.

I do not have to to test it right now(until the weekend), but if anyone else feels up for it, here's how to do it:

IMPORT AN EDL IN BLENDER:
1. Open Blender.
2. File > User preferences > Addons > Categories > Import – Export > Import – Export Import EDL > Check it.
3. Click button > Save user settings (so that setting will be used each time you start Blender).
4. Close the user preferences window.
5. Render settings(Camera menu to the right) > Frame Rate > Set it to your Flowblade setting. 
6. Change the combo box in the top bar saying Default to Video Editing.
7. To the right of the time line you’ll see EDL import (if not, maybe Blender needs a restart after enabling the addon?)
8. Click the open folder button under the offset line and select your edl file.
9. Click ‘Refresh Reels’.
10. Add paths to the missing reels using the open folder buttons.
11. When all is set click ‘Import video sequence (.edl)
12. The time line should now show your Shotcut project.
13. A+alt is play/pause.

**Comment by tin2tin** [comment]
Ah, I checked the Blender import and it appears to work fine. 

[https://s22.postimg.org/kyhvcrjq9/Flowblade_edl.jpg](Screendump)

**Comment by jliljebl** [comment]
Yes, the Blender import works and seems reasonable on first view, but there are issues:
* short timeslines with short clips work well
* when using longer clips (or maybe the problem is using longer timelines), then the renders from Blender EDL imported timeline start to differ by a few frames when compared to programs rendered by Shotcut or Flowblade.

Here is some media and an EDL (from Shotcut this time) to demonstrate the problem. The EDL uses the ANGEL and NIGHT clips from comment above with one additional longer clip.

Video file BIRDS
https://www.dropbox.com/s/z7mxbu2g2wfpbgd/birds_24.mp4?dl=0

Shotcut EDL export:
https://www.dropbox.com/s/m8m4lsy28uscu28/shotcut_24_full.edl?dl=0

Shotcut render:
https://www.dropbox.com/s/8kke9xkdcuerzei/shotcut_24_full.mp4?dl=0

The problem is that when you import the Shotcut EDL into Blender and render the timeline, there are differences of a few frames after about a minute or so.

So if anyone can import and render the Shotcut EDL in *other program then Blender* then we would know where the problem lies.

Anyway, I think the problem is with Blender  and I will release the EDL export functionality and improve on it if it is shown to be wrong.

**Comment by tin2tin** [comment]
Did you set the frame rate in Blender, before importing the edl? If not, that will change the timings.

In this pdf you can see how to import in Davinci:
[shotcut2davinciEDL.pdf.zip](https://github.com/jliljebl/flowblade/files/446741/shotcut2davinciEDL.pdf.zip)

**Comment by jliljebl** [comment]
Ok, I made sure that fps was 24 before EDL import, and before render, and all the files are 24fps...still differences of few frames. I'm going to give up now.

Da Vinci seemed to only work on CentOS, so maybe I can try that later on VirtualBox, but for now I can't check with that either.

I'm going to just make sure that I get same results as Shotcut for EDL export, and leave it at that for now,

**Comment by tin2tin** [comment]
Unfortunately Lightworks also show missing frames(comparing the end of v1 and v2):
![image](https://cloud.githubusercontent.com/assets/1322593/18145228/908383f0-6fca-11e6-9885-9597e4710b3d.png)
V1 is the rendered version(from your upload).
v2 is the edl imported file.
I guess it must be related to the mlt2edl ported code somehow.

BTW. it is very difficult to import an edl in Lightworks, because it demands embedded reel names and timecodes (00:00:00:00) in the source files(I used [Eyeframe Converter](https://eyeframeconverter.wordpress.com/) for this - it runs in Linux with Wine/it's a gui for ffmbc) and it is case sensitive, so the reel names can't be changed to caps and also the spacing is different:
[edl_1080p_24fps_corrected.txt](https://github.com/jliljebl/flowblade/files/448214/edl_1080p_24fps_corrected.txt)

**Comment by jliljebl** [comment]
Thanks for testing on Lightworks. 

I'm not sure that either Dan or myself are willing to spend huge amounts of time on this; EDL is a horrible exchange format, and in my view Dan and Shotcut is already doing the EDL export right and the others are missing something. Maybe differences are because the "drop frame" concept, but that should not be an issue here as fps is 24 even, not 23.97.

The good thing is that even a so-and-so working EDL is useful to the user, so I will release the Flowblade EDL export even if the questions of frame perfect correctness remain unanswered.

**Comment by jliljebl** [comment]
I'll  drop the all uppercase reel names thing for EDL export, it seems that it is not required even thought the cmx 3600 paper I've seen seems to indicate that and Avid does that too.

**Comment by tin2tin** [comment]
I've tested your edls against Davinci and they also seems a few frames off:
![image](https://cloud.githubusercontent.com/assets/1322593/18161085/aaeb22d2-7030-11e6-9db7-b30c3f804540.png)
![image](https://cloud.githubusercontent.com/assets/1322593/18161138/f3965916-7030-11e6-813d-e3ce6ff0ae5f.png)

Maybe it is a rounding issue in the timecode to frames conversion?

NB. The spacing between columns are not the same in Flowblad and Shotcut export:

FB:
001  ANGELX24  AA/V  C    00:00:00:00 00:00:15:21 00:00:00:00 00:00:15:21

SC:
001  wildlife AA/V  C        00:00:00:02 00:00:04:05 00:00:00:00 00:00:04:03

There's only one space between  "AA/V" and  "C" and 8 characters between "C" and "00:00:00:02" (which is space for transition durations). Each column must be an exact number of characters with an exact number of spaces in between.

**Comment by jliljebl** [comment]
Thank you for the test 

Can you do one more thing for me, and answer the following question: 

Do Da Vinvi, Blender and Lightworks all agree perfectly on the interpretation of my exported EDLs? If you have imported the EDL to all these, you can just render output from all and see if they are exactly the same.

If this is the case, then I can use Blender as target, and read its import code for more info.

**Comment by tin2tin** [comment]
All of them had a difference of 2-3 frames, so I believe, that the issue isn't on the Blender side of things. It might even be introduced as far back as in my old mlt2edl.py script... I didn't do this test back then.

**Comment by jliljebl** [comment]
From my point of view the situation is that if all export targets disagree on the interpretation, I have no way of knowing who is right and cannot move forward.

I think the fundamental cause of all these problems is this: https://documentation.apple.com/en/finalcutpro/usermanual/index.html#chapter=D%26section=6%26tasks=true

I'm just going to release my code as is, and consider EDL export as useful but ultimately unspecified functionality.

**Comment by tin2tin** [comment]
Ok, but please consider matching the spacing etc. mentioned above with the Shotcut layout, or else the edls will not import in Lightworks and Davinci, Blender looks for space as separators, and you won't see the error.

 When I get the time, I'll do the renders you're asking for and let you know what I find. 

The Shotcut thread can be found here(Dan just opened up the closed forum): [forum.shotcut.org/](https://forum.shotcut.org/t/mlt2edl-script-error-fix/55)

**Comment by jliljebl** [comment]
That thread link was useful and interesting, thanks.

 If Lightworks and Davinci import Shotcut layout I will certainly do a patch to match that as closely as I can before  the first release.

**Comment by tin2tin** [comment]
@sozap 
What's the status on EDL import in Natron?

**Comment by tin2tin** [comment]
I've rendered the imported edl from Davinci and Blender and compared it to your exported file:
![edl_difference](https://cloud.githubusercontent.com/assets/1322593/18225625/5b8db22c-71f7-11e6-95ed-008b097f1919.jpg)

So the duration of the edl imported & exported files seems consistent, but comparing it to your exported files there is a 3 frames difference. 

I came across this python edl parsing lib, maybe it can be used to shed som light on the import process(if the Blender edl import script can't)?

**Comment by tin2tin** [comment]
I've been investigating this problem of missing frames in edl exports.

The following two edls are the same video file split, at the same frames and exported as edl. (The first two time codes are player time codes and the next two are recorder time codes.)

Notice that Resolve reuses the same frame "21" in the player time codes, where as SC/FB adds one frame pr. cut. 

Resolve:
001  001      V     C        00:00:00:00 00:00:15:21 00:00:00:00 00:00:15:21  
002  001      V     C        00:00:15:21 00:01:15:21 00:00:15:21 00:01:15:21  
003  001      V     C        00:01:15:21 00:01:29:01 00:01:15:21 00:01:29:01  

Shotcut/Flowblade:
001  shotcut_ AA/V  C        00:00:00:00 00:00:15:20 00:00:00:00 00:00:15:20
002  shotcut_ AA/V  C        00:00:15:21 00:01:15:21 00:00:15:20 00:01:15:20
003  shotcut_ AA/V  C        00:01:15:22 00:01:29:01 00:01:15:20 00:01:28:23
(NB spacing is off thanks to forum posting restyle the text)

In Shotcut UI the cut is at 00:00:15:21, but exported in the edl as 00:00:15:20.
In Shotcut UI the cut is at 00:01:15:22, but exported in the edl as 00:01:15:20.

So it seems like a frame is missing pr. cut - which is also what I count when importing an sc edl in Blender and compare it to a sc rendered file.

**Comment by jliljebl** [comment]
This is all useful information and allows me to give this another shot. The quick points I see here:

* Davinci and Blender agree on the import, so I can use Blender as an export target after all. I doubted this because it has been unclear to me what went wrong
* The direction of error is in the same in both tests, Sc/Flb exports too short (compared to Resolve), and Blender/Davinci renders are too short from Sc/Flb point of view, Basically Blender/Davinci expect longer EDLs to render the same output as on Sc/Flb, Sc/Flb need to add frames for their EDLs somewhere
* Resolves in/out frames are inclusive/exclusive where as Sc/Flb do inclusive/inclusive, so that has to change first

If get results on fixing this, I'll post here a new EDL on the same clips. Might take some time as there are other things requiring attention before release.

**Comment by tin2tin** [comment]
The coder of Shotcut, Dan, wrote: In MLT, the out point is the time at beginning of the last frame - not the time at the end of it. In terms of frame numbers (and the last field of timecode), MLT's out point is the frame number of the last frame such that duration = out - in + 1.

**Comment by tin2tin** [comment]
I added a time code in picture to a 5 minutes long clip and exported it from Shotcut. FromShotcut.mp4

Then I imported the file into Shotcut.
And made split cuts at 15:15 16:16 17:17 and 18:18

Then I exported that file(OneMinutteTC.mlt) and there was not missing frames at the cuts. See FromShotcut.mp4

Then I exported an edl. OneMinutteTC.edl.

I imported the edl and the SC exported clip(no missing frames) in Blender.
And one or two frames where missing before the cut. See FromBlender.avi

Then I imported the same clip and the edl in Davinci Resolve.
And one frame is missing before each cut. See FromResolve.mov

Then I corrected the edl so the video runs continuously. OneMinutteTC_corrected (Resolve).edl

I then imported that edl in Blender and it shows that Blender doubles the frame at the cut. Two times frame 14. 

So Davinci is not importing the edl the same way as Blender is importing it... 

Files (13.3 MB total) 
OneMinutteTC.zip 
Will be deleted on 
13 September, 2016
Download link 
[https://we.tl/IKFZ1dDDMq](https://we.tl/IKFZ1dDDMq)

**Comment by tin2tin** [comment]
Just checked with Lightworks edl import and it behaves like Davinci: One frame is missing before the cut. So the conclusion is that there is some rounding issue with Blender, so occasionally two frames are missing, but Davinci and Lwks are in line when importing an Shotcut EDL: one frame is missing just before each cut.

**Comment by jliljebl** [comment]
Thank you for further information. So your experience was the same as mine with Blender which originally stopped the EDL work. I wasn't able to come up with a clear rule on how frames were lost and didn't feel I could move forward.

If the situation is clear with Davinci and Lwks - always one frame missing - then I will follow that even if I get some small differences in Blender.

**Comment by jliljebl** [comment]
@tin2tin 

I fixed the EDL in a way  that should work on Resolve: changed the layout, stopped making reel names  all caps and most importantly changed the clips lengths to inclusive/exclusive.

The EDL uses the FromShotcut.mp4 file you uploaded, has 3  clips of length 4 frames, and should display frames 00:00 -> 00:11 continuously. New EDL file below, could you see if it works on Resolve.

[fixed_edl.edl]( https://www.dropbox.com/s/e8tjw15yqgtf9c7/fixed_edl.edl?dl=0)

Blender is clearly broken, it repeats the fist frame even in first clip of EDL, which clearly cannot be caused by timecode values of imported EDLs.

**Comment by tin2tin** [comment]
Yes it is working now in both Davinci and Lightworks. Congrats!

Too bad with the Blender importer, because the coder of the EDL import script, Ideasman, quit Blender and is now working on OpenToonz. It doesn't make sense to use Blender as a bridge to Ardour anymore. And importing EDL in Ardour not possible yet: [Ardour forum](https://community.ardour.org/node/13913)

Anyhow I think it is great you now give your users the opportunity to color grade and finalize their projects in Davinci. And I hope more open source project will follow the EDL implementation. If Natron would implement it, the color grading, effects and final output could be done with open source all the way.

(Btw. really annoying importer in Lightworks, which insists on the filename must be exactly like the reel name in order to succeed).

**Comment by jliljebl** [comment]
Great! Thanks for testing this last one too. Maybe someone will fix Blender some time, but at least now users can export from Flowblade to some other programs. The next release is coming in the next two weeks, and this be available then in the version 1.8.

**Comment by jliljebl** [comment]
Container Clips are coming for 2.6, this will be our approach to integration with different tools.
