### ISSUE TITLE
Filter playback is slow

### ISSUE THREAD

**Issue by akhilman** [jliljebl/flowblade#256]
Currently filters makes playback slow. To work with timing I have to disable filters one by one. 
Will be nice to have checkbox that temporary disables filter preview.
Another solution is button to pre-render all filtered and composed clips.

**Comment by jliljebl** [comment]
Closing this as invalid because there are no actionable items in this issue.

* Filters in Flowblade are same as in e.g. KDEnlive and Shotcut and are provided by MLT and Frei0r projects
* There already exists a button to toggle all filters on and at once in the **Filters** editor, its next to the **Delete** button

Filters performance will eventually be improved in the future by employing the Movit OpenGL filters that run on graphics card. These are already available in the MLT, but have been a)source of a lot of crashes b) Python bindings will need to be updated with callback handling to utilize these

First attempts to get OpenGL filters will probably be earliest first half 2018, unless major help is contributed here

**Comment by jliljebl** [comment]
@akhilman 

I realized that you probably proposed a **global** switch for all the filters in current sequence. This would indeed be useful, so I added a Issue for it:

https://github.com/jliljebl/flowblade/issues/257

**Comment by akhilman** [comment]
@jliljebl yes I mean global switch. Thank you.
