### ISSUE TITLE
Create a package for Fedora distro.

### ISSUE THREAD

**Issue by catafest** [jliljebl/flowblade#261]
Can you make a package for Fedroa distro?
I tested with Fedora 25 alpha but I'm not Fedora developer.

**Comment by jliljebl** [comment]
I did a Google search and found that they already have packaged 1.8 for 24: https://www.rpmfind.net/linux/rpm2html/search.php?query=flowblade

I unfortunately going *wontfix* for this Issue because:
- Fedora seems to follow releases quite well, 1.8 is only about month old
- I do not wish to increase the release workload for myself
