### ISSUE TITLE
How to display the frames in the preview?

### ISSUE THREAD

**Issue by Feichtmeier** [jliljebl/flowblade#263]
Hi and thanks for the awesome work!

Sorry if this is the wrong channel but I didn't find any better:

How can I display frame previews inside of the video clip for example a clip that I have dragged into video 5? I would like to see the frames when I zoom.

Thanks in advance! And sorry again for the spam.

**Comment by dvdlvr** [comment]
Questions about how to use Flowblade or find features can be asked in the Flowblade Community website:
https://plus.google.com/communities/103860400113389238474

As far as I know you cannot see the actual frames, but if you zoom in max on the timeline you can see markers for each individual frame along the times displayed in the timeline. You can use the keyboard left and right arrow to navigate between frames (Displayed in the monitor). You can also use the prev frame/next frame arrows just below the monitor (The first two buttons).

**Comment by jliljebl** [comment]
After given this some thought I have decided to closs this as wontfix because the asked feature is not available in Flowblade and I do not have any short to medium term plans to add that feature. I will gladly accept pull request that does this in some clean way, but for now this will not be worked on.
