### ISSUE TITLE
ERROR: /usr/lib/python2.7/dist-packages/_mlt.x86_64-linux-gnu.so: undefined symbol: _ZNK3Mlt7Profile8is_validEv

### ISSUE THREAD

**Issue by orschiro** [jliljebl/flowblade#264]
Dear all, 

I would like to run Flowblade 1.8 on Ubuntu 16.04 but it produces the following error message. 

Do you have any advice for me?

Thankfully,

-Robert

```
orschiro@x230:~$ flowblade 
FLOWBLADE MOVIE EDITOR repository 1.8
-------------------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT not found, exiting...
ERROR: /usr/lib/python2.7/dist-packages/_mlt.x86_64-linux-gnu.so: undefined symbol: _ZNK3Mlt7Profile8is_validEv
orschiro@x230:~$ 
```

**Comment by jliljebl** [comment]
Running newer MLT then provided by Ubuntu 16.04 repository causes this. This can happen if you have for. e.g. KDEnlive PPA active.

**Comment by orschiro** [comment]
Dear @jliljebl,

Yes, indeed, I am running KDEnlive as well. 

What do you suggest me to do?

Can I run both application aside?

Warmly,

-Robert

**Comment by jliljebl** [comment]
KDEnlive from Ubuntu 16.04 repos does not break Flowblade, but KDElive from PPA will because it installs newewr ABI incompatible MLT and Flowblade's MLT Python bindings stop working.

The people in the wrong here are the creators of KDEnlive PPA, and they should stop breaking other applications on systems that have KDEnlive PPA is installed. You need to uninstall KDENlive and purge the PPA and install Flowblade after that to get Flowblade working.

**Comment by orschiro** [comment]
Thanks for your advice! 

It solved my problem and I will consider your steps for removing KDEnlive's special repository.

-Robert

**Comment by orschiro** [comment]
Solved my

**Comment by jliljebl** [comment]
Great. I have informed KDEnlive people of the situation, but unfortunately have not so far received information that the situation has been fixed. They did promise to look into this.

I'm actually re-opening this for the time being to provide information for users with the same problem.

**Comment by jliljebl** [comment]
**The fix here is to install hotfix release MLT 6.4.1.**

* MLT 6.4.0 is indeed broken for Python bindigs and Flowblade
* I thought that the issue was with mismatching installed versions of MLT, but I was wrong and that was not the case
* adding new methods should not break the bindings but unfortunately there was just one "const" missing from where it was needed. This has now been fixed.
* the breaking commit was done on July 21, so MLT is broken for Flowblade from that point until 6.4.1

**Please inform your OS maintainer to upgrade MLT to 6.4.1 to fix this**

**Comment by alexb3d** [comment]
If you can not install it on Ubuntu 16.04, please put a notice on the installation page, so you do not lose time.

**Comment by jliljebl** [comment]
@alexb3d Ubuntu 16.04 comes with MLT 6.0.0 which WORKS with Flowblade. I know because this version of Ubuntu is my development system!

To get the error message you describe you will have needed in some way to have installed a version of MLT available from MLT repository between July 2016 and the November release of MLT 6.4.1.

July 2016 is when the breaking commit was put in MLT, and as you can see July 2016 is after the release of Ubuntu 16.04. July comes after April. Ubuntu 16.04 has not updated MLT from 6.0.0.

Are you running KDEnlive PPA? This installs random versions of MLT and can break Flowblade. If this the case, you will need to uninstall and purge KDEnlive PPA and then reinstall Flowblade from deb file.

**Comment by jliljebl** [comment]
Google+ post:

https://plus.google.com/u/0/102624418925189345577/posts/7ANDDW3hzHB?sfc=true

**Comment by alexb3d** [comment]
"Are you running KDEnlive PPA?" 
Yes, I am currently doing tutorials. When I finish purging the Kdenlive PPA.
I am interested in trying Flowblade. Thank you

**Comment by jliljebl** [comment]
Added a known issue item with info links, closing .
