### ISSUE TITLE
Width parameter in filters not working always

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#280]
The width parameter is not working in special konstelations. It can be reproduced.

Add a video file and drag it do v1. Add filter translate from the transform section. picture 1
![1](https://cloud.githubusercontent.com/assets/23220631/20179921/8b179684-a758-11e6-84a1-831005321b8d.png)

Change width and you will see the zoom. picture 2
![2](https://cloud.githubusercontent.com/assets/23220631/20179963/bf95e03c-a758-11e6-997d-3d22051aa096.png)

Add a video or picture file with different resolution and add the translate filter. picture 3
![3](https://cloud.githubusercontent.com/assets/23220631/20180015/e9d735ee-a758-11e6-8be0-68d38f36b4ed.png)

Now change the width parameter and you see that the picture/video dosnt zoom elese turn to left or right. picture 4
![4](https://cloud.githubusercontent.com/assets/23220631/20180063/11351372-a759-11e6-94b2-73e82fd1d6ea.png)

This also happens with text and i think its a bug.

Regards, Mario!

**Comment by dvdlvr** [comment]
I'm on Ubuntu 16.10 and I couldn't get the zoom part to work at all. The width parameter just doesn't work for me (Other than moving the image left or right as in the example above).
I wonder if this is linked to the mlt version?
MLT found, version: 6.2.0
OS: Ubuntu 16.10
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 

From a technical point of view:
It's the 'geometry' part of the filter that seems to ignore the width parameter altogether. Changing the height parameter will zoom in on the picture.
Changing the geometry editors in the filters.xml from v2 to the first version (Which shows Size/Height instead of width) will zoom in on the picture.
i.e. replace this line
<property name="transition.geometry" args="editor=affine_filt_geom_slider_2 exptype=geom_in_affine_filt_v2">0=0/0:SCREENSIZE:100</property>

with this line
<property name="transition.geometry" args="editor=affine_filt_geom_slider exptype=geom_in_affine_filt">0=0/0:SCREENSIZE:100</property>

I haven't done it because I don't know why the version 2 was originally put in place.
I hope this helps.

**Comment by jliljebl** [comment]
Ok...this fix I would have never found...because the v2 versions move was done for the exact same reason that the change to earlier versions I just pushed was done: to get the zoom working!

I would have with 99% probability just removed the the ability to change size height and called it a fix.

The avfilter.zoompan still has much better performance, so I will remove "Translate" if "Zoom Pan" is present from user available filters.

I don't know the happenings here...maybe some changes in MLT that i was unable to pay attention to enought, but now it again works, thanks, good job.

Ficex in repository, will be in 1.12.
