### ISSUE TITLE
flowblade in archlinux

### ISSUE THREAD

**Issue by uranio-235** [jliljebl/flowblade#283]
Even the AUR 1.6 version having the following error

```
[lazaro@artema` ~]$ flowblade 
FLOWBLADE MOVIE EDITOR repository 1.8
-------------------------------------
Launch script dir: /usr/bin
Running from installation...
modules path: /usr/share/pyshared/Flowblade
MLT not found, exiting...
ERROR: /usr/lib/python2.7/_mlt.so: undefined symbol: _ZNK3Mlt7Profile8is_validEv
```

**Comment by uranio-235** [comment]
Answer to myself, downgrading to MLT 6.2 solve it

**Comment by spsf64** [comment]
Same error here, hope it gets fixed because downgrading is not an option here...

**Comment by jliljebl** [comment]
**The fix here is to install hotfix release MLT 6.4.1.**

* MLT 6.4.0 is indeed broken for Python bindigs and Flowblade
* I thought that the issue was with mismatching installed versions of MLT, but I was wrong and that was not the case
* adding new methods should not break the bindings but unfortunately there was just one "const" missing from where it was needed. This has now been fixed.
* the breaking commit was done on July 21, so MLT is broken for Flowblade from that point until 6.4.1

**Please inform your OS maintainer to upgrade MLT to 6.4.1 to fix this**

**Comment by spsf64** [comment]
@jliljebl 
MLT has been updated in archlinux and flowblade is working ok.
You can close issue. Thanks for this great project!

**Comment by jliljebl** [comment]
Thanks, closing. Fixed in MLT and Archlinux.
