### ISSUE TITLE
Feature request copy compositor

### ISSUE THREAD

**Issue by oluja1973** [jliljebl/flowblade#289]
Hello,

theres  nice feature to copy an effect from previous or next clip. This would be also usefull for compositors as picture in picture aso.
As example if you have something like a slideshow you can use the same compositor for all pictures.

Regards, Mario!

**Comment by jliljebl** [comment]
This would work so that position and opacity keyframes are copied from one Compositor to another.

I agree that this would be useful.

**Comment by jliljebl** [comment]
This is in repository now, and will be in 1.12

Because different compositors have different data it is now only possible to copy-paste to compositors of same type: "Affine Blend" ->"Affine Blend" , "Dissolve"-> "Dissolve" etc.

It is in principal possible to do computation to copy-paste applicable data between different types of compositors, but this is not done for now

**Comment by andykais** [comment]
can you explain how to use this feature? I don't see a way to copy my compositor in my timeline
