### ISSUE TITLE
Wrong FPS on import

### ISSUE THREAD

**Issue by qubodup** [jliljebl/flowblade#290]
Hello, when I drag in a 720p 30fps video file, I get suggested to switch to 720p, 29.97fps.

Video demonstration: https://youtu.be/Qqqp0R3ay_I

**Comment by jliljebl** [comment]
Seem to be the case.

**Comment by jliljebl** [comment]
This is related to Issue #284.

**Comment by dvdlvr** [comment]
It looks like the problem is caused by utils.py -> get_file_producer_info.
On a test file I get fps_num = 74.0 and fps_den = 3.0, giving a calculated fps of 24.7.
However, using clip.get_fps() I get 25.0 and with clip.get_speed() I get 1.0 which are also the values I get in Mplayer.
This was a file recorded from TV, so it should be at 25 fps.

Because of the incorrectly calculated fps the function mltprofiles.py -> get_closest_matching_profile_index cannot find an exact match as it is using 24.7 fps instead of 25. 
Also, the function doesn't really find the closest matching profile if there is no matching fps. In fact, on my test file I get a proposed profile at 23.98 fps, though profiles at 25 fps are closer to 24.7 fps.

This is because the profile framerate is only tested against an exact match of the file framerate.
Maybe, after fixing getting the right fps from the file, the match_score should be calculated something like this:
if fps == prof_fps:
   match_score = match_score + 100
else:
  match_score = match_score + (100 * (fps - abs(fps - prof_fps)))
That should, if my math is correct, get the closest prof_fps to the file fps. On my test file this proposes a profile @25 fps.

**Comment by jliljebl** [comment]
Fixed in repo, will be in 1.14.

**Comment by dietyyli** [comment]
I have 1080p 59.94fps file and flowblade suggest 23.98fps. (Yes, 23.98 and not 23.97.)
Flowblade 1.14.0 from rpmfusion on Fedora 27.

**Comment by jliljebl** [comment]
OK, needs investigating.

6.1.2018 7.33 ip. "dietyyli" <notifications@github.com> kirjoitti:

I have 1080p 59.94fps file and flowblade suggest 23.98fps. (Yes, 23.98 and
not 23.97.)
Flowblade 1.14.0 from rpmfusion on Fedora 27.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/jliljebl/flowblade/issues/290#issuecomment-355762209>,
or mute the thread
