### ISSUE TITLE
Flatkpak for flowblade?

### ISSUE THREAD

**Issue by sramkrishna** [jliljebl/flowblade#297]
Any chance we can have flowblade published as flatpaks so that we can just download them and run them on any distribution?

**Comment by oluja1973** [comment]
See this thread -> https://github.com/jliljebl/flowblade/issues/273

There will be an appimage in the future. You can also download appimages and start them without installation.

**Comment by jliljebl** [comment]
The current marching order for the new package formats is:

1. Appimage
2. Snap
3. Flatpack

Flatpack seems like most difficult to do, and requires source code modifications, so we will attemp it last. I have no clear date when we get around to it yet.

**Comment by sramkrishna** [comment]
Thanks for the response!  Much appreciated.  I have asked the flatpak community to see if they can come up with a manifest for you.  It doesn't seem correct that you would need to modify your source code to make it work.

Secondly, would it be not be simpler to just pick appimage or flatpak?  The entire point of snap/appimage/flatpak  is that it runs anywhere.  I assume that I can use appimage and it will run on any distro.   It seems better to encourage distros to include one of them everywhere so you don't have to have multiple targets otherwise we are not solving the problem of packaging.

I picked flatpak simply because I work for the GNOME Foundation and have an interest in solving the distribution problem.

**Comment by sramkrishna** [comment]
One last comment, I checked with flatpak folks and what you said is correct if you want to do have sandboxed application, but if you just want to distribute it then no source code modification is required.  Thank you for being so open to my bug report.  I appreciate it.  I know that sometimes working these issues can be a thankless task.  Best wishes.

**Comment by sramkrishna** [comment]
OK, no worries.  But it is looking like GNOME will be using flatpak and KDE moving in that direction as well.  SolusOS will be moving to flatpak as part of overall support for Steam.  Steam is not quite moving to flatpak but using some parts of it like bubblewrap.  We just recently added GL support within the sandbox.  Something to think about. :-)

**Comment by probonopd** [comment]
Flatpak comes from the GNOME camp. KDE is looking into all sorts of bundles right now, and I don't think Ubuntu is going Flatpak anytime soon. AppImages run on most systems out-of-the-box today.

**Comment by jliljebl** [comment]
@probonopd @sramkrishna I'm going to do one of Appimage, Flatpack and Snap. The one I will do is the one I complete - and hopefully not feel like I should stab my self in the eye.

I just spend 3 hours trying to do Appimage and I'm feeling stabbing myself in the eye. The main document 

The fundamental problem is that the authors of the documentation are completely unable to write to audience with no prior knowledge of Appimage. All I got was a lot questions, questions, questions:

- How do I combine binaries from distributions (for stuff like numpy, python-dbus etc.) with the latest MLT and Frei0r that I have compiled myself
- the whole idea is to (mostly) piggypack on existing distribution binaries?
- I must(can) do this on Ubuntu 14.04 on Virtualbox?
- I can do this on Ubuntu 16.04 and then use the same script to create Appimage on 14.04?
- Can I convert Flowlade.yml + my .deb to appimage in some easy way and combine it with some stuff I compiled my self.
- "cd recipes/meta/ && bash -ex ./Recipe XXX.yml" -  how do I make this work? What do I need to make this work.
- should I modify some appimage.sh script to do this or is that some TravisCI special thing
- The whole TravisCI aspect is just confusing...do I need to join to create appimages?
- NO STEP-BY-STEP INSTRUCTIONS ANYWHERE in official documentation
- are AppDirAssistant and AppImageAssistant current or not and is AppImageKit and appimagetool the new hotness. Do I need these?
- etc, etc.

Step-by-step guides and FAQs are needed here. The zero prior knowledge developer experience of trying to create Appimage is horrible.

Anyway i'm giving up on Appimage for now and next I'll try Snap.
...if that fails next I'll try Flatpack..
..if that fails I'll try Appimage again
...until I succeed with one of these...and this is one I will be distributing.

You can check on my progress in https://github.com/jliljebl/flowblade-packaging   I'll keeping a l. stream of thought file on all called questions a one like this: https://github.com/jliljebl/flowblade-packaging/blob/master/Appimage/questions

**Comment by probonopd** [comment]
I think you are making it harder for yourself than need be, since I have already written a working yml file for Flowblade some time ago that can be used to convert the latest deb from https://github.com/jliljebl/flowblade/releases to an AppImage:

https://github.com/probonopd/AppImages/blob/master/recipes/meta/Flowblade.yml

To use this, run on any debian or Ubuntu system (the exact version does not matter, it just needs to have the apt/dpkg tools installed):

```
wget "https://github.com/probonopd/AppImages/raw/master/recipes/meta/Recipe"
bash -ex Recipe Flowblade
```

Please let me know if you run into any kind of trouble.

**Comment by probonopd** [comment]
This being said, let me answer your questions one-on-one:

> How do I combine binaries from distributions (for stuff like numpy, python-dbus etc.) with the latest MLT and Frei0r that I have compiled myself

AppImage is really just a self-mounting filesystem that executes the file called `AppRun` inside. So if you can arrange your application in a directory so that by executing a file called `AppRun` is able to run your application from within this directory, then you're basically there.

So your question about "how do I combine different Python libraries from different sources" is really not about AppImage, but about how Python handles libraries. I know from experience that this can be a bit tough.

**Comment by jliljebl** [comment]
Thanks, i will continue on this, I will post info on how I'm doing later. If I can get this working I can surely consider contributing some step-by-step instructions for others  to follow. I will continue to keep a log on how I'm doing since I have now committed to getting 1-2 container packages out I might as well, and that info may be useful to creating some step-by-step later.

**Comment by jliljebl** [comment]
Ok, now I was able to build an Appimage, but the included MLT was ancient 0.9.0  from 14.04 so I can't distribute this yet.

However once I get MLT 6.4.1 with latest versions of dependencies in , then were cooking.

**Comment by probonopd** [comment]
Are you on IRC? join #AppImage :-)

**Comment by jliljebl** [comment]
Not on IRC but I might join later sometime when I come back to this. About to call it a night, but now it is definitely looking doable.

**Comment by jliljebl** [comment]
@probonopd 
Did 'Recipe' change somehow because commands:

wget "https://github.com/probonopd/AppImages/raw/master/recipes/meta/Recipe"
bash -ex Recipe Flowblade

stopped working?

Earlier they created a working AppImage, now you get when running in terminal:

janne@janne-Lenovo-G50-80:~/test/apptest/out$ ./Flowblade_Movie_Editor-1.10.0.glibc2.15-x86_64.AppImage
/bin/bash: /tmp/.mount_jVOla2/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
FLOWBLADE MOVIE EDITOR 1.10
---------------------------
Launch script dir: /tmp/.mount_jVOla2/usr/bin
Running from installation...
modules path: /usr/share/flowblade/Flowblade
MLT not found, exiting...
ERROR: No module named mlt

It can't find mlt python bindings now.  'Recipe' was earlier something like 11.3kB, now it's 12kB so that has changed.

**Comment by probonopd** [comment]
@jliljebl https://github.com/probonopd/AppImages/commits/master/recipes/meta/Recipe

**Comment by jliljebl** [comment]
@probonopd 

I found old 11.7 kB 'Recipe' from Trash which creates a working AppImage: 

    $ ./Flowblade_Movie_Editor-1.10.0.glibc2.15-x86_64.AppImage
    /bin/bash: /tmp/.mount_s4hQSf/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available    (required by /bin/bash)
    FLOWBLADE MOVIE EDITOR 1.10
    ---------------------------
    Launch script dir: /tmp/.mount_s4hQSf/usr/bin
    Running from installation...
    modules path: /usr/share/flowblade/Flowblade
    MLT found, version: 0.9.0
   etc...

The new 12.0 kB 'Recipe' does not work. What should I do? The encouraged workflow is to rely on remote resources. Is AppImage broken for Python applications at the moment?

**Comment by jliljebl** [comment]
@probonopd 

I was now able to make a working AppImage of Flowblade with MLT 6.5.0 just by copying libs and one Python file into AppDir, so I can now very likely create a script I can run in Ubuntu.14.04 to create a widely working AppImage.

 Hopefully a working "Recipe' script comes back online, but I use old working one for now.

**Comment by probonopd** [comment]
Hi @jliljebl thanks for reporting the issue about Recipe, can you narrow down from the working to the non-working one what broke it for you?

**Comment by jliljebl** [comment]
@probonopd I'll clone the repo tomorrow and try to find the breaking commit.

**Comment by jliljebl** [comment]
@probonopd 

Ok, I tested HEAD and the commits on Recipe:

4f98b181455c936b4e5404aefc2c88d81a0c1270 BAD (HEAD at tiem of testing)
8c3bb1286607c9a2f7b119df2112b0eb885e4bf8 GOOD
a931caadd68db72411a197f720e1a53b3a72a9f0 BAD

The breaking commit is a931caa, https://github.com/probonopd/AppImages/commit/a931caadd68db72411a197f720e1a53b3a72a9f0

**Comment by sramkrishna** [comment]
Some great progress there. :)  I'll see if I can help you with a flatpak version as well if you are amiable to it.

**Comment by probonopd** [comment]
@jliljebl 

> The breaking commit is a931caa, probonopd/AppImages@a931caa

Now this is really strange. This commit is supposed to make Python load modules only from the inside, rather than from the outside, of the AppImage. Are you sure you are bundling all needed Python modules inside the AppImage?

**Comment by jliljebl** [comment]
@sramkrishna Still working the AppImage. I think it is the only one that I'll do for 1.12, for 1.14 in August I will look into adding Flatpack or Snap, I'll get back to you then. Flatpack seems more likely just now.

Sorry bout hijacking the Issue for AppImage discussion, but once it got going we will keep here for simplicity's sake.

**Comment by jliljebl** [comment]
@probonopd 

> Are you sure you are bundling all needed Python modules inside the AppImage?

So you mean that my .deb assumes something Python related to be present in the OS, and I'm not getting bug reports because in Debian/Ubuntu/Mint it always is, and if AppImage can get it from OS it is running it also works on those systems, but if it cannot then it stops working?

I gues this is possible, but I'm not sure where to look, python-mlt is definitely packaged and that is what it is complaining is missing.

    FLOWBLADE MOVIE EDITOR 1.10
    ---------------------------
    Launch script dir: /tmp/.mount_F1v505/usr/bin
    Running from installation...
    modules path: /usr/share/flowblade/Flowblade
    MLT not found, exiting...
    ERROR: No module named mlt

mlt is not suppposed be in 'modules path' obivously, juat my app modules.

**Comment by probonopd** [comment]
Looks like the error is that it is looking in the _system's_ `/usr/share/flowblade/Flowblade` rather than the _AppImage's_ _/tmp/.mount_F1v505/usr/share/flowblade/Flowblade`...

**Comment by jliljebl** [comment]
I do not seem to be able to compile MLT 6.4.1 in such a way that I can mix it with rest of binaries to create a working AppImage so I'm giving up on this now.

**Comment by probonopd** [comment]
@jliljebl what do you want to "mix" and which build system are you building on?

**Comment by jliljebl** [comment]
@probonopd MLT 6.4.1 and repository Frei0r, I've tried to compile them and copy binaries in AppDir on top of existing ones from recipe. AppImage from debs makes MLT 0.9.0 which is too old. i'm not using any build system,  just using scripts here: https://github.com/jliljebl/flowblade-packaging/tree/master/Appimage
:

**Comment by probonopd** [comment]
@jliljebl if you forget about Recipe and AppImage, can you build and install to PREFIX=/usr on a Ubuntu precise or trusty system, preferably e.g., on Travis CI?

If you can do that, I think I could take it from there.

**Comment by jliljebl** [comment]
This now part of issue #453 and is closed as independent Issue.
