### ISSUE TITLE
Change Sequence Tracks Count...

### ISSUE THREAD

**Issue by ptrg** [jliljebl/flowblade#332]
The "tracks_combo" in "Change Sequence Tracks Count..." dialog holds the list of predefined combinations of video and audio tracks. This list contains only a subset of all possible combinations.

It would be a better solution (and more user friendly) to have two separated list to set the number of video and audio tracks... of course not to allow the sum to be more than the max number of tracks.

**Comment by jliljebl** [comment]
A few points.

1) Giving users the ability to select the number of video and audio tracks individually is the kind of feature that gives users a feeling of being fully in control of the application, and makes them more sympathetic towards the application. It improves the UX more then then capability.

2) The GUI for doing this is a bit problematic because the max. number of available video and audio tracks depend on the number of tracks of the other kind. This necessitates dynamic updating of the selections when combined track count exceeds 9. This makes ComboBox a bad widget for doing this.

3) The best option might be using SpinBoxes and info label:

*Layout:*
Number of tracks:  | Video   **5** <>    | Audio **4** <>  |   total:** 9**, max. 9

*Widgets:*
Label | SpinBox  | SpinBox | Label

I agree that this would be an improvement but not probably something that will worke first on. I'm adding it to queue, but probably won't work on it for a while.

**Comment by jliljebl** [comment]
I decided to do this right away, will be in 1.12, If we're getting improvement on user perception of application, we should probably do the change in question right away.
