### ISSUE TITLE
Cannot use trim tool to equal the length of an image with the audio file

### ISSUE THREAD

**Issue by orschiro** [jliljebl/flowblade#340]
Dear all, 

I was trying to use the trim tool to extend the length of an image to match the length of an audio file.

However, I can only trim to a certain extent but not further. 

I am using version 1.10.

Can anyone help me understand why I cannot make it the same length as the audio?

Yours,

Robert

![peek 2017-02-17 09-58-flowblade](https://cloud.githubusercontent.com/assets/170947/23060216/147d2a50-f4fd-11e6-9fea-8b4509c40e37.gif)

**Comment by dvdlvr** [comment]
@orschiro This is because the length reported by mlt for an image is always the same and limited at 15000.

@janne From what I see there IS a small bug in that you cannot extend beyond 5 minutes where the max. size should be 10 minutes (As reported in clip length).

@orschiro If you set the Graphics default length in the Preferences -> Edit tab to 15000 (Which is the max. value) you should be able to extend it to 10 minutes (Need to restart your application to have this applied).

There are a few workarounds:
1) Add the image multiple times to your timeline and only adapt the length of the last image to coincide with the end of the audio file. The downside of this is that if you wish to have some movement in your image it is a bit of a hassle.
2) First create a video file of the required length (Or longer) using multiple instances of your image, then use your video file as source. This will allow filters/compositors to be used properly for the length of the clip. Obvious drawback is you have to create a video file first.

**Comment by orschiro** [comment]
Dear @dvdlvr,

I appreciate your response!

Let me ask, why is there a limit to extend image files in the first place?

**Comment by dvdlvr** [comment]
This is a limitation of mlt, the framework used by Flowblade to render the result.I don't know why mlt has this limitation.

Sent from Samsung tablet

-------- Original message --------

**Comment by orschiro** [comment]
Is it worth to have a conversation over this with the mlt developers?

**Comment by jliljebl** [comment]
@orschiro Probably not, they had same technical reason for it originally, and there is the simple workaround of adding multiple clips. I'm closing tis as *wontfix*, I will add add an item in know issues document when I get around to it.

**Comment by orschiro** [comment]
OK, fine. Thank you! :+1:

**Comment by jarvis-huang** [comment]
I seriously hope flowblade finds a workaround for this. This can easily shut out many applications where a static image needs to be displayed for a long period of time.
