### ISSUE TITLE
Increase Audio Volume

### ISSUE THREAD

**Issue by symptog** [jliljebl/flowblade#354]
Is it possible to increase and/or normalize the audio volume through the filters?

**Comment by jliljebl** [comment]
Currently, no.

Normalize is a rendered filter that needs a bit of structure, but it exists and will be added.

Current audio "Volume" filter only supports dropping audio level, but Shotcut has same way to push level up, so that should probably be doable too. This will be looked at.

Audio production should mostly work in such a way that high quality audio material is at almost max. volume to begin with and the mix is created by bringing down all audio so that their relative levels are correct for the desired mix.

**Comment by jliljebl** [comment]
Ok, I was wrong: mlt serveice "volume" can increase audio level too. I pushed a patch that enables increasing audio volume 6db. The service can do more, but that would require special non-linear editor for it, which will probably be added at some point. but for now I'm closing this as fixed, Feature will be in 1.14.

**Comment by bigalgeorge** [comment]
Hi there I wonder if there is any development on the normalize function. Today I had occasion to use normalize as I was in a church, up a ladder and audio was very low, but on localised talk, was great. I realize I can normalize using external editors but this would be a nice feature.

**Comment by Erudition** [comment]
I too would love to be able to increase the volume  of a clip. Currently I made it work with a "Volume" filter that lets you set keyframes, but not an overall gain. So I set keyframes throughout the video to 200% and now it's a little bit louder.
