### ISSUE TITLE
My first use feedback

### ISSUE THREAD

**Issue by slarta** [jliljebl/flowblade#355]
Thank you very much for this video editing program!
I have created a clip for a first use and the following things are noticeable to me.
Excuse me when I see something wrong or overlooked.

Flowblade 1.10
Lubuntu 16.04.2

1.) crash window plop up.
- click shutdown = Flowblade don't shut down. crash window will restart and restart in few minutes.
- click to let cose = Flowblade don't shut down. crash window don't restart. Flowblade works.
(it's often by double click in the Flowblade window)

2.) Image Sequence
a) The generated clip is not syncron to the images for a loop. better set the first picture for the first frame and a input field for the clip lenght [in frames]. when i have 16 pictures and set 1 per frame in 50frames/minute and set [edit-old: time to 1 minute 14 seconds] [edit-new:] 64 frames i have a 4 loops clip. Or i can set 1 loop and use Roll.
b) Roll don't work for expand the lenght. Trim works for this.
c) Swip dont't work for swip a clip in the video track. Overwrite works for this.

3.) Composite
a) Picture in Picture
PNG with transparence:
without Filter Crop pictures have a black Border or black letterbox (by other format). same by Image Sequence.

4.) Composite
a) Region
better with input fields for x/y and width/height. for a next clip in the timeline with same x/y and width/height with same position. same by rotate. it's too difficult to bring two clips in the same position.

5.) Letterbox in the preview-window not so good.

6.) It's realized to set a video background color, or a background image? otherwise everytime 1 video track is for the background color/image blocked.

7.) max 7 video tracks is too little. it's realized for a vertical scroll in the timeline? it's beside better for expand more video tracks (not a mickey-mouse working).

8.) It's realized in the loaded media window only show file details? by many loaded media files are not clearly arranged.

Edit:
9.) When i load a project-file directly from file manager, than plop-up the auto-save window, and when not load a auto-save, open a default window, not load the project.

**Comment by jliljebl** [comment]
Hi,

I'm closing this as invalid because it has multiple issues most of which are not actionable. A valid Issue describes single actionable thing like crash or feature request. I will however post a few on your points.

> 1.) crash window plop up.

This is not happening on my system. If you start Flowblade in terminal with command 'flowblade' what is the output?

> 3.) Composite
> a) Picture in Picture

That's the way it works and i don't believe they will accept patches in MLT to change it.

> 4.) Composite
> a) Region
> better with input fields for x/y and width/height.

This has been thought about, I think these will be added maybe even for next release.

> 7.) max 7 video tracks is too little. it's realized for a vertical scroll in the timeline? 

You can get 8 video tracks, but no vertical scroll will be added to Flowblade ever, so 8 is as good as it is going to get. If you need more then that you will need to use a compositing program like Natron.

For the other issues I was unable to formulate a clear response.

Thank you for your feedback
