### ISSUE TITLE
Add Way To Animate Transform

### ISSUE THREAD

**Issue by benrob0329** [jliljebl/flowblade#372]
Problem: When dealing with large images (such as webpage renders) you cannot have a nice scroll because:

1) You cannot animate a transform filter
2) The Affine compositer only grabs what is currently visible
3) There is no way to render a transform animation

The effect probably could be done in Gmic, but that only works with video clips.

**Comment by dvdlvr** [comment]
Try putting your image in V2, putting a black colour clip in V1 beneath it and using the Affine Blend Compositor between them. Then enter the start / stop keyframes and the desired size / position / rotation for each.
The preview window will show you the result as you slide across the timeline.
NB: You MUST have a clip in V1 to see the result and the clip you want to show in V2.
See attached render and project backup.

[Strawberries.mpg.zip](https://github.com/jliljebl/flowblade/files/946639/Strawberries.mpg.zip)
[Strawberries-project.zip](https://github.com/jliljebl/flowblade/files/946645/Strawberries-project.zip)

**Comment by benrob0329** [comment]
> The Affine compositer only grabs what is currently visible

If you blow the image up with a compositer (for a credits scroll and the like) it wont be at the full resolution of the original image, and thus be unreadable/unusable.

**Comment by jliljebl** [comment]
I agree that this feature is needed.

In my understanding that this is not doable in MLT at all currently because all imported image data (video and graphics) will be passed on as project screen size images.

One would need a new MLT producer that does the affine transform *before* passing image data onwards. This is perfectly doable in principle, read and keep data graphics data in memory, do transform per frame and pass it on.

I will be moving my attention towards MLT in the autumn as it is becoming clear that further improvements in stability and features will increasing be found there rather then in Flowblade code, and this is one of the possible areas of attention.

I also have the Phantom2D codebase that does this, and there may eventually be some developments from that direction too.

**Comment by jliljebl** [comment]
This is now fixed for 2.4, I just did credits roll test from 1920 x 5376 size PNG image and it worked just fine.

The new filter coming in 2.4 to use for this use case is called "Position Scale".
