### ISSUE TITLE
how to determine what gets rendered

### ISSUE THREAD

**Issue by ftrotter** [jliljebl/flowblade#383]
It is not possible to tell what gets rendered. I did a picture in picture composition that plays correctly in the "Display Current Sequence in Timeline" window. But when exporting, only the "in picture" "Track" is exported. 

Previous help posts have indicated that the "render dialog" has options to determine what is being exported, but there are no options on that page that help determine what is, or is not, being exported to the render.

I expect there is a 75% chance that there is a secret combination of key presses or menu item selection that resolve this problem somehow, but in that case, this is a usability bug. Understanding and controlling what video and audio tracks are exported is a central feature of the software. The interface should be obvious enough to make it clear what happens. 

-FT

**Comment by jliljebl** [comment]
This is straight out invalid. No one has over the years ever given similar report on the software. When you press "Render" button in "Render" panel it renders everything as displayed on timeline.

I'm not closing this immediately because I'm want to understand how it is possible for this report to exist at all.

1) Which version on software you are using?
2) Which version of MLT you are using? (Select "Help"->"Runtime Environment" for info)
3) Which OS you are using?
4) Please post a screenshot of timeline of the sequence you have trouble rendering.
.

**Comment by jliljebl** [comment]
This is not looking valid, will reopen if more reports come.
