### ISSUE TITLE
the cut icon stops working 

### ISSUE THREAD

**Issue by ftrotter** [jliljebl/flowblade#386]
This is an actual bug, as opposed to interface complaints.

After using the program for a while, the cut icon just simply stopped working at all. 

No idea why. 

-FT

**Comment by jliljebl** [comment]
Are you aware of the activity switches that are on the left side of the timeline that control which tracks are affected by the 'Cut' button? Did you accidentally turn on of them off?

**Comment by jliljebl** [comment]
This is not looking a valid, I'll reopen if further reports come in.

**Comment by cefn** [comment]
Accept this is probably invalid given it's related to a feature rather than a bug, but worth noting that this is pretty much the only hit on Google for 'flowblade activity switch' so this issue could perhaps be refocused on documentation. 

I encountered the same feature with half an hour of experimenting trying to work out how to cut a segment of video within the timeline, but still none the wiser how 'activity switch' and 'selection' relate to each other, or even what the graphical or logical presentation of an activity switch even is.
