### ISSUE TITLE
 Timeline overlay for trim delta + timecode

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#397]
I think it's absolutely needed for professional editing to have a more enhanced timecode indicator. I suggest it consisting of three parts instead of just one:

1. Current cursor position inside the timeline;

2. Current cursor position inside the currently selected clip. It is good for synchronizing some visual event in a particular clip, known by its timecode, to soundtrack events or events in other clips.

3. Relative position of the currently performed operation (move, trim, roll, etc.). It is absolutely needed to perform precise transitions and trimming.

**Comment by Efenstor** [comment]
Sorry, didn't noticed the "Trim view", just discovered it. The docs obviously require updating. Anyway, putting the same data in the form of a complete timecode, not just number of frames, as I suggested, would be much easier to understand, and also usable for creating compositors, not just trimming.

**Comment by jliljebl** [comment]
After looking at this I do not have any clear design ideas on if/how to move forward.

Maybe providing a screenshot of a commercial application with this feature existing (and clearly pointed out) as desired by Issue opener or giving a wireframe GUI design idea would make clear the exact nature of the experienced problem and the desired solution.

**Comment by Efenstor** [comment]
May be like this?

![timecode_v1](https://user-images.githubusercontent.com/11175574/26837746-6fee9fe8-4b08-11e7-84a7-861e79766ad0.jpg)

![timecode_v2](https://user-images.githubusercontent.com/11175574/26837744-6fd5126c-4b08-11e7-9cf5-d4eac7c9891f.jpg)

![timecode_v3](https://user-images.githubusercontent.com/11175574/26837745-6fd5dba2-4b08-11e7-969c-1da2816e4294.jpg)

**Comment by jliljebl** [comment]
Ok, I get it. 

Here's Final Cut X with similar functionality:
https://www.youtube.com/watch?v=FQx6BQmMFLY

They have TC display under monitor so trim deltas and TC are appropriate there, but in Flowblade the TC display can be anywhere. They also display trim information as overlay on timeline.

Premiere also has this kind of information under monitor:
https://www.youtube.com/watch?v=V0HvsqHPTPI

Some points:

1) I can pretty much guarantee that your proposed solutions would not be doable if we wish to continue supporting vertical 768px  and horizontal 1151px monitors, the needed extra pixels just are not there.

2) The "Trim view" required some pretty complex hacks to get shoveled into the program and I clearly remember that trying to get timecode displayed correctly on all trim types - Trrim, Roll,  and Slip - instead of just delta display was somehow extra difficult. I think "Trim" was doable but "Roll" and "Slip" just didn't play ball and I dropped the feature.

3) Premiere type multi timecode display will not be doable with 768px  and horizontal 1151px minimal requirements, we do not have movable panels (and will not have ever) like Premiere (and KDEnlive).

4) If I could require 1080px minimum vertical pixels I could do basically anything, being able to require 1360px minimum horizontal would also simplify the design process greatly, but I'm stuck to supporting current minimum screen size requirements for the foreseeable future because many users seem to run older hardware.

With these points in mind I consider Final Cut X type timeline overlay for delta + timecode the only viable solution. I'll add this to feature queue, but I'm' unsure when I get around to attempting it.

**Comment by Efenstor** [comment]
You're right about the Final Cut X style, support for small screens is a good thing, e.g. for quick on-the-go editing on a netbook. By the way, I think the second indicator (clip-space position) should have a sign as well, as it represents a relative position as well, only this time of the clip start (media start, not the in-mark) relative to the timeline cursor.

**Comment by jliljebl** [comment]
Edit delta info timeline overlays for all tools and modes (except Insert) will be in 1.14.

Closing this as *feature added*. We may later display some additional information in info overlays but that will be a separate issue.

**Comment by Efenstor** [comment]
It works just great! Thanks!
