### ISSUE TITLE
Minor feature request: Conventionalize usage of the mouse+modifier keys

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#406]
It is a bit unconventional (and therefore inconvenient) how FlowBlade uses the modifier keys. The typical usage convention used in many programs with the timeline concept (e.g. audio editors and sequencers) is this:

Left Click = select one item, deselecting the others
Ctrl+Left Click = add one item to selection
Shift+Left Click = select a range of items starting with the one last clicked, others are deselected
Wheel = zoom or scroll (there is no singular convention, usually there's an option in Preferences)
Ctrl+Wheel = zoom
Shift+Wheel = scroll

**Comment by jliljebl** [comment]
This can be fixed done if:

 1) Current behavior is preserved and stays default. The new requested behavior should be optional using preferences.
2) The code for this is contributed by a pull request, I have no intention on spending time on this.

**Comment by jliljebl** [comment]
Ok, so I my changed position somewhat here.

> Shift+Left Click = select a range of items starting with the one last clicked, others are deselected

This already works like this.

>Wheel = zoom or scroll (there is no singular convention, usually there's an option in Preferences)
>Ctrl+Wheel = zoom
>Shift+Wheel = scroll

Premiere and Final Cut have *Alt+Wheel = zoom* so there are differences here, and we have Ctrl+Wheel   doing opposite zoom if wheel set to do 

All and but making all this user settable would be desirable, because this is exactly the kind of stuff where user preferences differ, and none of the options can make claim to being more right then others.

So these will be made user settable options.

> Ctrl+Left Click = add one item to selection

In the sense that this implies user being able to do non-continuous selections, this is going hard *wontfix* from me, its 400+ lines of frame perfect code and I do not think the use case is important.

**Comment by jliljebl** [comment]
After further deliberation I have decided that this does not offer enough added benefits for user to justify added complications in GUI/code.

Basically, we have decided on our approach here and will stick with it.
