### ISSUE TITLE
Track size way too small on HiDPI display

### ISSUE THREAD

**Issue by TerranceH** [jliljebl/flowblade#416]
Track size is still way too small on HiDPI display, even at "large hight".

version: 1.12.0
Linux 4.4 and XFCE 4.12 (xubuntu 16.04)

![screenshot_2017-06-29_11-22-34_transformers_4](https://user-images.githubusercontent.com/951537/27738590-54d5cbee-5dde-11e7-8701-915762e720bf.png)

**Comment by jliljebl** [comment]
I can easily add one more track height option.

Which of 1.5x, 2.0x or 3.0x times current max track height you believe would be best?

**Comment by TerranceH** [comment]
can we have all 2x, 3x and 4x available?
and you can see some other controls/text are also very tiny, how about let's add some UI scale factor option?

**Comment by jliljebl** [comment]
No, the internal code structure does not support free scale factor for track heights (and I do not want to spend develoopment time resources on changing it) and for this approach 3 options is max.

I'll add option "Double" with 2.0x. Based on your screen shot that should be tall enough.

**Comment by jliljebl** [comment]
Fixed in repo, will be in 1.14.

Preferences dialog "View" panel now has drop down menu "Tracks Heights:" with options "Normal" and "Double for HiDPI".

I don't have a HiDPI monitor so if someone with such monitor could test the repo version before release, that would be great., instructions here: https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md.
