### ISSUE TITLE
Zoom / Pan doesn't work

### ISSUE THREAD

**Issue by lyn1337** [jliljebl/flowblade#421]
Greetings,

today I experienced an issue using the Zoom / Pan filter on a clip.

- The preview seemed to be completely unaffected by the set filter.
- Other filters worked just fine.

When starting flowblade via terminal, the output looked like this:
`[filter avfilter.zoompan] Unexpected return format`

flowblade 1.12

**Comment by jliljebl** [comment]
The reason seems to be MLT <-> AVFilter compatibility, MLT maintainer Dan Dennedy on the subject:

"Well, basically, many avfilters are simply incompatible.... In this case, the error occurs because the output
width and height do not match the width and height that MLT needs..." (https://www.mail-archive.com/mlt-devel@lists.sourceforge.net/msg04892.html)

This didn't come up when I created the filter because the test files I used it on worked. Currently I have no (sane) way of knowing from Flowblade which files work and which files do not.

I'm not sure how to move forward. This could be fixed in MLT by forcing some conversion heuristic to make frames compatible. 

I don't want to remove the filter but that may be necessary.

**Comment by lyn1337** [comment]
Sad to hear, that didn't come to my mind.

I've tried it on a couple of projects without success but I remember it working at some point.

Is there any alternative working for flowblade at the moment?

Am 09.07.2017 um 12:11 schrieb jliljebl <notifications@github.com<mailto:notifications@github.com>>:


The reason seems to be MLT <-> AVFilter compatibility, MLT maintainer Dan Dennedy on the subject:

"Well, basically, many avfilters are simply incompatible.... In this case, the error occurs because the output
width and height do not match the width and height that MLT needs..." (https://www.mail-archive.com/mlt-devel@lists.sourceforge.net/msg04892.html)

This didn't come up when I created the filter because the test files I used it on worked. Currently I have no (sane) way of knowing from Flowblade which files work and which files do not.

I'm not sure how to move forward. This could be fixed in MLT by forcing some conversion heuristic to make frames compatible.

I don't want to remove the filter but that may be necessary.

**Comment by jliljebl** [comment]
Does filter "Transform->Affine" work for your use case? It's much slower but offers similar functionality.

**Comment by lyn1337** [comment]
I might be wrong about this, but I think I couldn't crop the frames with that one; having a screencast movie file that I only want a certain window picked from.

Am 09.07.2017 um 13:45 schrieb jliljebl <notifications@github.com<mailto:notifications@github.com>>:


Does filter "Transform->Affine" work for your use case? It's much slower but offers similar functionality.

**Comment by jliljebl** [comment]
Use "Size/Height" and "X", "Y" , did you try it? It works here.

**Comment by jliljebl** [comment]
I fixed this by dropping "Zoom Pan" filter. Fixes in MLT will be difficult to make and take a long time to become available, so dropping this for now is the only correct thing to do.

**Comment by lyn1337** [comment]
> Use "Size/Height" and "X", "Y" , did you try it? It works here.
Indeed, my bad - **it's a working alternative**.

**Comment by dvdlvr** [comment]
This issue seems to be fixed somewhere between MLT 6.6.0 and 6.16.0. The 6.6.0 version just does not report the correct framesize for the output where the filter actually does. In 6.16.0 the correct framesize is reported and it worked for 3 different project settings (DV/DVD. 1080p and 720p) using the same 1080p source file.
The Transform->Affine does not zoom. The Size/Height filter only actually changes the y position of the frame.
I will check when the issue was fixed and see if we can limit filters to a specifically used MLT version easily.

**Comment by jliljebl** [comment]
There seems to be some developments, reopening for further testing.

**Comment by jliljebl** [comment]
We have new improved filters for this coming in 2.4 that will cover this use case. Open new Issue after release if new filters are not working satisfactorily.
