### ISSUE TITLE
Possible minor issue: Trim drags only the edge first clicked

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#424]
Not sure whether it's a bug or a feature, if it's a feature then it's not too convenient. When I use the Trim tool and click, for example, the right edge (i.e. out point) of the clip then only that edge is being dragged and there is no way to switch to the left edge (in point) except for to deselect and re-select the clip, or just click "3" again to re-enable Trim.

**Comment by jliljebl** [comment]
This is something I have wondered if I should take into some other direction, but it IS a very complex design issue e.g. if we always deselect clip after edit then it is not possible to offer keyboard control for trimming because selecting clip will always init mouse edit and it becomes impossible to enter keyboard trimming mode etc.

I will look into making cursor sensitive to clip edges on the next cycle which could be a possible way to combine always exiting active trim with keyboard control.

**Comment by jliljebl** [comment]
However the far more frequent case is when after trim you edit the opposing clips edge.

I'm not sure I will address this, but I'll leave it open for now. User experiencing of not being able to get out of something  is always a legit concern.

**Comment by Efenstor** [comment]
> if we always deselect clip after edit
Ehm, why? It should remain selected. It's just about how clip reacts to mouse clicks. Sorry, I don't quite understand the programming obstacles for implementing something, I'm just a user.

Anyway, I expect it to be like this: if I click or drag anywhere in the left half of a clip then it switches to editing the left edge and either just selects it (if I clicked) or moves it (if I dragged). If I click in the right half then it does the same for right edge. When an edge is selected I can use keyboard keys to move it. And surely there must be a keyboard shortcut to do the same edge switching thing.

**Comment by jliljebl** [comment]
> if we always deselect clip after edit
>          Ehm, why?

This design approach is by no means the only way to go, it is just the most simple way to help with the particular problem of having to exit trim selection to trim the other end.

> Anyway, I expect it to be like this: if I click or drag anywhere in the left half of a clip then it switches to editing the left edge and either just selects it ...

Yes, and this would work much better if cursor was sensitive to timeline position in a way that would communicate to user which end will trimmed when mouse is pressed/clicked. something like cursor switching at 6:20ish in:  https://www.youtube.com/watch?v=xoazZ1bFYi4 (the more complex things Final Cut X has are definitely out the picture for now)

If have avoided timeline contents sensitive cursor for the ergonomic reason that when editing long sessions having constantly position the mouse precisely causes a lot of issues with prolonged muscle tension. Therefore I always preferred to make all initial selection areas the whole clip.

But it just may be that for trimming and just dragging clip ends in move modes users prefer this, so this will be worked on. Final Cut, Avid and Premiere all have quite elaborate mouse sensitivity designs and they all probably have the usability research to prove that this is what users prefer.

 > And surely there must be a keyboard shortcut to do the same edge switching thing.

There should be, it just can't be arrows or even arrows with modifiers because ARROW + CTRL makes pointer move 10 frames at a time. Using  ARROW + ALT to do completely different action (switch trommed edge) would be confusing to users. It could be TAB and SHIFT +TAB but I have TAB already switching between monitoring Timelie clip so that would need to changed or some other key selected. This is not clear to me what is correct thing to do here.

**Comment by jliljebl** [comment]
This is now fixed and feature will be in 1.16.

**Comment by Efenstor** [comment]
I confirm, it works great! Thanks!
