### ISSUE TITLE
Major issue: Anomalous behaviour while using the Slip tool

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#426]
Here is the screencast: https://youtu.be/ppj9fbyp1cU

P.S.: Thank you Janne, we all really value your efforts on making such a great video editing tool! Especially after Dan Dannedy practically abandoned his work on Shotcut.

**Comment by jliljebl** [comment]
Ok, I was able to reproduce this so it is a bug.

Thanks for the support. I think Shotcut will also start again moving forward sometime in the future but maybe at a slower pace.

The problem with all these projects is that there just is not enough interest in video editing among people capable of contributing code. The projects will move forward slowly and developers will eventually burn out and get tired of pushing the boulder up the hill.

Flowblade has been getting more contributions in the last year or so, but if we wish to compete toe-to-toe with the commercial applications in the near future,  a much larger amount of quality contributions would be needed.

**Comment by jliljebl** [comment]
I *think* I fixed it and will close as fixed.

* the issue was that sometimes we got -1 for the index of clip being edited
* MLT gives this value when it is asked for index of clip at a frame that is after the end of material on track
* I added some safeguards to stop getting value -1 
* I did a five minute furious clicking test and did not see the issue again
* it wasn't clear why this happened only sometimes and I'm still not 100% that I understood the issue fully, but I believe it is quite probably fixed now
* I will reopen  if needed

**Comment by Efenstor** [comment]
Looks like it's fixed indeed! Thanks. I'll test it more thoroughly a bit later.

**Comment by Efenstor** [comment]
Yes, it is fixed! The only issue that still bugs my editing workflow is https://github.com/jliljebl/flowblade/issues/404
