### ISSUE TITLE
Request for composition, rotopaint and planar tracker?

### ISSUE THREAD

**Issue by Shonanqn** [jliljebl/flowblade#433]
there is the possibility of having a planar tracker or rotopaint within flowblade?

**Comment by Efenstor** [comment]
Why not use Natron for this? Currently it would be much better to make Flowblade rock-stable, precise and convenient for basic editing of any source material, rather than spending time on stuffing it with new features.

**Comment by jliljebl** [comment]
Planar tacker and rotopaint are features belonging in a compositor tool rather than in an editor tool.

We will be adding rotoscoping tool sometimes and some more advanced compositing methods like luma compositing with two sources and alpha source producing a single output, but these are not part of the immediate road map.

I'm closing this as *wontfix* even some similar feature additions are considered in future.
