### ISSUE TITLE
plugin Red Giant???

### ISSUE THREAD

**Issue by Shonanqn** [jliljebl/flowblade#438]
it is possible to have plugin color correction filters. like those of giant giant filters ???

**Comment by jliljebl** [comment]
I'm closing this as *invalid* because:
* plugin/tool authors deside for themselves which applications to support, e.g. Flowblade project cannot bring Red Giant to Flowblade, Red Giant authors can bring Red Giant to Flowblade
* bringong commercial plugins as part of Flowvblade is currently not a project goal. It is conceivable that this could change, but for now this is not a something that is worked on
