### ISSUE TITLE
1.14 - Keyboard shortcut don't work

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#442]
When trying to get up the keyboard shortcut page it doesn't come up with anything. 
Error message:
Shortcut file in editorpersistance.pref.shortcuts not found!

I'll have a closer look at it tomorrow.

The program recognizes the shortcut files but doesn't seem to load any. Also no option to select the shortcut file.
It looks like because of this many keyboard shortcuts no longer work. Haven't tested them all, but the ones I tried don't work.

**Comment by jliljebl** [comment]
I tested this on 3 virtual machines with installation from .deb 1.14. It is
possible that your development installation does not work but .deb
installations does. Keep me posted, thanks.

5.10.2017 12.10 ap. "dvdlvr" <notifications@github.com> kirjoitti:

When trying to get up the keyboard shortcut page it doesn't come up with
anything.
Error message:
Shortcut file in editorpersistance.pref.shortcuts not found!

I'll have a closer look at it tomorrow.

The program recognizes the shortcut files but doesn't seem to load any.
Also no option to select the shortcut file.
It looks like because of this many keyboard shortcuts no longer work.
Haven't tested them all, but the ones I tried don't work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jliljebl/flowblade/issues/442>, or mute the thread

**Comment by dvdlvr** [comment]
Ok, this is due to my 'prefs' file from 1.12.
Once I renamed my old prefs file in ~/.flowblade it created a new one and the shortcuts worked properly.

So anyone with the same problem can just remove or rename the prefs file in their $HOME/.flowblade directory to bypass it. Current preference settings will be lost, then, obviously.

**Comment by jliljebl** [comment]
It should work going from installation 1.12 to 1.14, but I did some changes
to prefs file that can cause issue with prefs file from mid-cycle.

5.10.2017 12.27 ap. "dvdlvr" <notifications@github.com> kirjoitti:

**Comment by dvdlvr** [comment]
Ok.
I'll check it out today to see if I can find what caused my problem.
