### ISSUE TITLE
Clip uneditable after replacing a source file

### ISSUE THREAD

**Issue by apienk** [jliljebl/flowblade#474]
**Steps to reproduce:**

1. Prepare two video clips with same names but markedly different durations (e.g., 30 seconds and 15 seconds).
2. Put the longer clip on timeline in Flowblade.
3. Make a cut in the long clip near its end (at timecode bigger than the total duration of the shorter clip, e.g., at 00:00:20:00).
4. Save the project and close Flowblade.
5. Replace the long clip with the short clip.
6. Open the project again in Flowblade.

**Observed result:**

1. The cut is still present on the timeline despite the file being too short.
2. The cut cannot be selected, moved or deleted.
3. The viewport is out of sync with timeline.

**Expected result:**

Either:
- The cut contains the last frame of the current clip or a black frame, and can be edited.
- The cut is removed and the clip is truncated on the timeline to match current duration.

**Environment:**

Flowblade 14.0
MLT 6.0
Ubuntu 16.04 LTS

**Comment by jliljebl** [comment]
Only possible way to fix this without turning this into a major undertaking would be to a) save media file contents hashes, and b) flat out refuse to load projects if contents have changed. This will not be done because this would break media relinking and sometimes careful users may wish to try to change media contents if they make sure that clips have at least the same length.

Replacing longer file with a shorter one and being surprised that this is not handled gracefully is analogous to pouring gasoline on floor, throwing a match after it and being surprised that the house burns down. Some kind of fire proof floors could be build with great care and cost, but in general it is just better to not do any gasoline and matches related activities inside the house.

**Comment by jliljebl** [comment]
BTW this a great example of feature that a commercial package with tens of developers might implement but cannot be justfied resource wise wise mostly single developer application.

Suggested workaround is obviously to create longer clip by hand with additional black after existing media.
