### ISSUE TITLE
the transitions do not mix with the composer

### ISSUE THREAD

**Issue by hefistion** [jliljebl/flowblade#475]
**Steps to reproduce:
[flowblade-transitions.zip](https://github.com/jliljebl/flowblade/files/1700046/flowblade-transitions.zip)

**

1. Put a color clip on track V1
2. Put a still image clip (JPG) on track V2
3. Put another  still image clip (JPG) on track V2
3. Add Blend Affine compositor to V2, image 1 and image2
4. Edit the composer's properties of both images on V2
5. Add Rendered Trransition 2 clips selected

**Expected result:**

a transition between the two images while preserving the effects

**Observed result:**

there's a jump in the video, it's not linear

**Please include the following information.**
1) Flowblade version (Help->About):
1.14.0
2) MLT version (Help->Runtime Environment):
MLT: 6.6.0
GTK: 3.22.26
3) Your distribution (Ubuntu, Debian, Mint etc.):
Antergos

**Comment by jliljebl** [comment]
Ok, I get it. Without the video clip I would have said that cannot be reproduced.

The good news is that there is a easy workaoround and the bad news is that this absolutely cannot be fixed.

**Workaroud**
1. Lift the later clip on track V3. Make clips overlap as much as you want to the dissolve to last that you tried to do.
2. Add compositor for second clip in track V3 and do the same animation you did previously. Make target track on this compositor V1 instead of default V2.
3. Select compositor for image on track V2.
   * go to frame where clips' overlap starts
   * set opacity key frame here and set value to 100
   *  go to frame where clips' overlap ends
   * set opacity key frame here and set value to 0

Image of needed arrangement: https://i.imgur.com/977eM40.png

**Why this can't be fixed**
1) Clips and compositors are separate objects and rendered single track transitions are done between *clips*. Taking Compositors into account here would complicate the code a lot and would be very difficult to make work reliably.
2) the intended workflow is the the multitrack one described above
