### ISSUE TITLE
Auto following the composer for the clip, it seems broken

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#481]
Earlier, when the checkbox (Obey Auto Follow) was set, I could not move the composer, now it's done easily.
![2018-02-27 12-20-04](https://user-images.githubusercontent.com/26217756/36720704-dedd0e08-1bb9-11e8-82d7-bf87e39d0c7e.png)

**Comment by jliljebl** [comment]
Thanks. Will check.

27.2.2018 11.29 ap. "Николай Смольянинов" <notifications@github.com>
kirjoitti:

**Comment by smolnp** [comment]
I understood where the mistake was. The function has been moved to another location, but the orphaned record has not yet been erased from the compositors context menu.
![2018-03-02 17-47-15](https://user-images.githubusercontent.com/26217756/36905178-aebce7b6-1e43-11e8-8b41-382217395cf2.png)

**Comment by jliljebl** [comment]
No, this is working as designed.

1) Auto follow is OFF by default. As long as it is off "Obey Auto Follow" has no effect because auto follow is off.
2) When autofollow is turned on with "Compositors Auto Follow" compositors with "Obey Auto Follow" checked will do ("Obey") auto follow, those with it off will not.

What is it that you do not understand here? Should we drop autofollow feature because it is too  complicated for users?

**Comment by jliljebl** [comment]
"Obey Auto Follow" checkbox exists so that users can have some compositors doing auto follow and some  can be freely moved, as user chooses. Is this too complicated?

**Comment by smolnp** [comment]
Thanks, I already figured out (1:12) - https://www.youtube.com/watch?v=kV0X6pjbi9Y&t16.04.2018, 18:22, "jliljebl" <notifications@github.com>:I made the "Obey Auto Follow" checkbox active only when auto follow is on, maybe that helps users understand the intention of the grayed out until users puts auto follow on.
