### ISSUE TITLE
Batch render queue application issues abort message

### ISSUE THREAD

**Issue by berniz95** [jliljebl/flowblade#488]
Hello,
I use Flowblade 0.14, MLT 0.9.2 under Linux Bunsenlabs Hydrogen which is Debian. GTK is 2.24.25.
Many thanks for that software which is quite stable indeed, even though I find the autosaves very useful !
I've pushed several renderings in the batch queue, resulting in proper acknowledgement messages but when I select Render > Batch render queue, the batch queue application doesn't start and a traceback is displayed on the console :

```
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/launch/flowbladebatch", line 15, in <module>
    batchrendering.main(modules_path)
  File "/usr/share/flowblade/Flowblade/tools/batchrendering.py", line 280, in main
    mltfilters.load_filters_xml(mltenv.services)
  File "/usr/share/flowblade/Flowblade/mltfilters.py", line 375, in load_filters_xml
    if editorstate.mlt_version_is_equal_or_greater(filter_info.mlt_drop_version):
  File "/usr/share/flowblade/Flowblade/editorstate.py", line 132, in mlt_version_is_equal_or_greater
    mlt_parts = mlt_version.split(".")
AttributeError: 'NoneType' object has no attribute 'split'
```
I don't think I can get a newer release of Flowblade on that distro. I'm rather looking for a workaround of some kind.

**Comment by jliljebl** [comment]
HI, this is practical impossibility to fix or even offer helpful info because the versions of application, MLT etc are so old.

Maybe you can try to function make  *mlt_version_is_equal_or_greater* in *editorstate.py* to just return True or False but that could make things even worse.

You could always ask your distro to update to latest version or even latest GTK2 version which is 1.0.

Closing as *invalid* because this is not about current release.
