### ISSUE TITLE
Keep original media size

### ISSUE THREAD

**Issue by m-dp** [jliljebl/flowblade#501]
When I add a media clip to a timeline track - a 1920x1080 video to a track in a 1440x1080 profile - the media get resized to fit the profile. 
What I intend to do, instead, is to keep the size of the 1920x1080 as is, and show part of it in the final 1440x1080 rendering. 
All subsequent effects (e.g. Affine) operate on shrunk media, not on the original. 

Flowblade should be able to manage different media sizes. 
Either an option should exist to transform the clip (scale and position) before it is placed in the track, or nesting timelines (create a timeline B with profile 1920x1080, place 16:9 media clip, apply Affine filter, create timeline A with profile 1440x1080, place timeline B in track of timeline A). 

Currently, to do what I need, I have to pre-operate on the clips, or re-operate on flowblade renderings - e.g. crop with `avconv` then edit in flowblade, or edit in flowblade then crop the rendering. 

Am I missing anything? 

(Flowblade 1.16.0; MLT 6.0.0; XUbuntu 16.04 LTS)

**Comment by jliljebl** [comment]
My initial hunch is that this is not doable because:

- mlt operates on  *mlt_frame* data structures on all image data flow
- when *mlt_frame* is created its width and height is aquired from a *mlt_profile* struct, see line 56, 57  here: https://github.com/mltframework/mlt/blob/master/src/framework/mlt_frame.c
- you can only use one profile in sequence: all clips and transitions need to be using the same profile or their data cannot be modified to create are single output.
- this necessitates initial scaling when reading image data that does not match project profile

Only possible way to do this would be to create a new  MLT producer that does the x/y offset translation  before creating *mlt_frame* objects, and I do not see myself working that. I can look into this a bit during the dev cycle to see if there are some tricks available, but I'm closing this as *wontfix* because that is the probable outcome for now.
