### ISSUE TITLE
Don't hard code prefix /usr

### ISSUE THREAD

**Issue by eszlari** [jliljebl/flowblade#513]
At the moment the prefix `/usr` is hard coded in the source code of flowblade. Ideally the prefix that is passed to setup.py would be used:
```
$ python2 setup.py install --prefix=/myprefix
```
This a problem for flatpak, because there the standard prefix is `/app`.

**Comment by jliljebl** [comment]
From these lines:

    - sed -i 's|"/usr|"/app|g' /app/bin/flowblade /app/share/flowblade/Flowblade/tools/gmic.py
      - sed -i 's|/usr/share/locale|/app/share/flowblade/Flowblade/locale|g' /app/share/flowblade/Flowblade/translations.py

in  https://github.com/flathub/io.github.jliljebl.Flowblade/blob/master/io.github.jliljebl.Flowblade.yaml  I guessed that the problem is with these files and paths.

I pushed this patch https://github.com/jliljebl/flowblade/commit/a1774343c90485c04e6830c477464fee0c6db145 to make code work with Flatpak as is with hardcoded Flatpak paths, without sed replacement.

Setup.py and Flatpak installs are always going to have differences in paths in just exactly these files because they put translations into different places, they look for gmic binary in different places and the relative paths from launch script to app.py are going to be different.

We can reopen this anytime later if Issue needs further consideration.
