### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by fratcn** [jliljebl/flowblade#523]
FLOWBLADE MOVIE EDITOR 1.16
MLT found, version: 6.8.0
OS: Arch Linux

`MLT detection succeeded, 167 formats, 103 video codecs and 72 audio codecs found.
552 MLT services found.
Loading render profiles...
Loading filters...
Brightness dropped, MLT version too low for this filter.
Loading transitions...
RGB Adjustment dropped for Color Adjustment
Hue dropped for Color Adjustment
Gamma dropped for Lift Gain Gamma
G'MIC found
Natron not found
Player initialized with profile:  HD 1080p 25 fps
Selected color NOT detected
BG color detected
Create SDL1 consumer...
zsh: segmentation fault (core dumped)  flowblade
`

**Comment by martinkg** [comment]
please have a look at the discussion on this [thread](https://github.com/jliljebl/flowblade/issues/508)

**Comment by jliljebl** [comment]
Ok, thanks. A gdb output there showed that it is not probably a MLT build issue, but more likely a threading issue in SDL audio caused by a a patch in MLT. There are some patches that work on this area, so the cause is probably in on on them. I'll get back in this in next few weeks after I have completed my current workflow update work. The probable patches causing this:

https://github.com/mltframework/mlt/commit/b199c89fddf6490a707f78c5147d2bbd72c37ead

https://github.com/mltframework/mlt/commit/f06a6dfaed85c3f30e38f4cd263efc154002a5aa

https://github.com/mltframework/mlt/commit/e647ae3e7f74a663bfe87171383a4e6c6247311f

**Comment by jliljebl** [comment]
I decided that I need a summer break from the project. When I get back we need to somehow get some patches in MLT to fix it to work with Flowblade again.

For the time being running MLT 6.6.0 fixes Flowblade, but you may need to compile and install it yourself if Debian is running later a version of MLT that breaks Flowblade.

**Comment by Efenstor** [comment]
It's strange but everything works fine for me under Debian Stretch (with the backports enabled). If you still have the issue I suggest you using the Flatpak version.

**Comment by jliljebl** [comment]
This should work now, see last comments here: https://github.com/jliljebl/flowblade/issues/508
I'm 987% sure this is the same issue. I'm leaving this open for possible further info until next release.
