### ISSUE TITLE
High CPU usage when previewing 4K video

### ISSUE THREAD

**Issue by LemarinelNet** [jliljebl/flowblade#527]
Hi,

I'm running flowblade 1.16 on fresh ubuntu 18.04.
MLT version is 6.6.0
GTK is version 3.22.30
Computer is a core i5 with intel HD graphics.
I've installed "intel quicksync video" "drivers", and can play a 4K video with mpv with almost no cpu usage (4 cores on htop show between 10-15% usage while playing).
When I load just the same clip on flowblade and press play, 4 cpus runs at 100%

Is flowblade using libva or similar hardware acceleration to play media ?
If yes, I might miss something to enable it ?

Thanks !

**Comment by Efenstor** [comment]
I am no Flowblade developer but think the MLT library just cannot use hardware acceleration, at least not on Intel HD graphics. Playing H264/AVC video forward is one thing, playing it frame by frame from any frame in any direction with any speed is another. That's why the Proxy feature was made in Flowblade. My previous PC (six-core AMD Athlon and a Radeon card with free drivers) could not manage 4K editing as well, only when I have recently upgraded it to a 8-core Ryzen 7 2700 it is able to do the thing without proxy. I suggest you to use the proxy feature, it worked fine for me. Other video editors I tried (Kdenlive, Shotcut, OpenShot, Pitivi) besides being outrageously buggy either rely purely on CPU as well or seemingly use only some GPU acceleration so editing is still far from being comfortable.

**Comment by Efenstor** [comment]
Hello LemarinelNet, I have just tried the .deb version and it really lags with 4K even on my Ryzen 7 2700, while the flatpak version works smoothly! I suggest you to try the flatpak. The flatpak version includes the newer version of MLT (6.8.0) which obviously supports hardware acceleration (or has some bug fixed) while, for example, my Debian stable includes the outdated 6.4.1. Your Ubuntu has 6.6.0 which is outdated as well.

**Comment by LemarinelNet** [comment]
Thanks for the tip !
I'll try flatpak version so !

**Comment by LemarinelNet** [comment]
Hi,A followup : on the same laptop, I've installed a fresh ubuntu 18.04. Installed flatpak + flatpak version of flowblade.
previewing a 1080p video takes +180% cpu usage, but almost 0% in VLC (I think vlc uses the gpu for decoding ?)
Any clues ?
