### ISSUE TITLE
save question always shown

### ISSUE THREAD

**Issue by miniskipper** [jliljebl/flowblade#530]
When exiting the application the save question is always show - even if there was not any change in the project.

Flowblade version: 1.16
MLT version: 6.10
Distribution: Arch Linux

**Comment by Efenstor** [comment]
I double that.

**Comment by jliljebl** [comment]
Because not all edits effecting timeline (like keyframe edits) are covered by the undo/redo mechanism we would need to edit multiple code points and the *work/payoff ratio* would be quite bad here.

I might get around to doing this myself eventually, but I would much prefer a contribution.

**Comment by dvdlvr** [comment]
I've got something in the pipeline which I use in development for my own preference changes, but since I don't know which 'standard' preferences actually need a restart and which don't I haven't put it in as a pull request (yet).

It works like this: If a dev makes a change to preferences that needs a restart (s)he sets a flag. This flag is detected when the prefs are saved and a restart is proposed. This will then actually restart the application, so the user won't have to manually do that.
If the flag is NOT detected the current message and dialog will appear.

If that's a good intermediate solution for now then I can extract it and post a pull request for it.
If not, I will need time and/or info on which pref settings actually need restarting the application and which don't.

**Comment by jliljebl** [comment]
We had to implement the the needed machinery for timeline rendering and got this for free.

Feature in repo, will be in 2.6.
