### ISSUE TITLE
Incorrect display of blending mode.

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#534]
When you place a duplicate graphic image on the source track and on the destination track using "Dodge", it produces the wrong result.
![_2018-08-12_23-27-53](https://user-images.githubusercontent.com/26217756/44006231-5aa6900c-9e89-11e8-9f1b-5eca30e25e61.png)

**Comment by Efenstor** [comment]
Flowblade version (Help->About): 1.16.0
MLT version (Help->Runtime Environment): 6.8.0
Your distribution (Ubuntu, Debian, Mint etc.): Debian Stretch

Confirmed. The problem is present only with JPEG images, not with videos, not with PNG images.

**Comment by jliljebl** [comment]
Will look into this before release, I have no immediate idea on the issues or fixes.

**Comment by smolnp** [comment]
In the composer "Blend" Blend mode: "Saturate" displays only the destination frame
![1](https://user-images.githubusercontent.com/26217756/45044687-82652c00-b079-11e8-94c9-45c54223dace.png)
Instead of performing the proper operation, such as in "saturation"
![2](https://user-images.githubusercontent.com/26217756/45044706-8d1fc100-b079-11e8-8614-538996d4f62b.png)

**Comment by jliljebl** [comment]
Confirmed, still no idea cause unless it is some real dumb slip-up on my part.

**Comment by jliljebl** [comment]
This is mysterious, I just looked at frei0r code (which I wrote myself years ago) and I'm inputting the right value.

https://github.com/dyne/frei0r/blob/master/include/frei0r_cairo.h

"saturate" it wants and "saturate" Flowblade gives.

**Comment by jliljebl** [comment]
We have 2 confirmed issues

1. Compositor "Blend" with value "Saturate" does not work at all
2. Compositor "Dodge" produces wrong output with clear color artifacts.

**Comment by jliljebl** [comment]
This is fixed by dropping both features.

Cairo "Saturate" operator is not listed in "Blending Modes" category, instead it is it listed under "Operators", see https://www.cairographics.org/operators/ and we can assume that it does not function similarly to other Blend Modes and it is best to just drop it.

As replacement for Compositor "Dodge" using a Cairo blender with blend mode  "ColorDodge" is recommended as a workaround, we won't attempt a fix here.
