### ISSUE TITLE
Minor issue: Dragging in/out points resets the filters window

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#537]
Flowblade version (Help->About): 1.16.0
MLT version (Help->Runtime Environment): 6.8.0
Your distribution (Ubuntu, Debian, Mint etc.): Debian Stretch

When editing clips with keyframes it's very inconvenient that after dragging an in or out point the effects window is reset, so I always need to double-click the clip again and again to move the keyframes.

I have also noted that clip focus is always lost after every action. Any professional video editing always requires making a great number of subtle modifications to one and the same clip, as it's all about finding ideally timed places for frames and transitions, so that workflow should be fast and convenient.

**Comment by jliljebl** [comment]
This could be difficult since a lot of data needed to get keyframes editing going depends on In and Out points of clips, it may be possible to do, but it will require more investigation and will probably not get done for the next release.

I agree that it would be more convenient to not have to re-init filter editing after clip edit. I'll leave this open and revisit later.

**Comment by jliljebl** [comment]
I found a way to do it, patch is in repo now, fix/feature will be in next release. Filter editors will remain open for all edits that do not move clips to a different tracks.

Needs testing still as missing any detail here will cause crashes.
