### ISSUE TITLE
Minor issue: Displaying the keyframe timeline resets the cursor position

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#538]
Flowblade version (Help->About): 1.16.0
MLT version (Help->Runtime Environment): 6.8.0
Your distribution (Ubuntu, Debian, Mint etc.): Debian Stretch

It is very inconvenient that the cursor resets its position to the beginning of a clip if that clip (or compositor) contains keyframes. I often use the cursor position as a sort of temporary marker, so to see how that particular frame in the timeline changes when I am moving or resizing different clips so I could find the best position for each. Editing keyframes is a different stage of work and it should not disrupt such actions as moving or resizing. I think there is absolutely no need for the first keyframe to be selected when showing the keyframe line, as well as to the red cursor to be inside the timeline.

**Comment by jliljebl** [comment]
This can easily be made a user preference and there is no clear reason not to do it here, so i'll add a preference for this.

**Comment by jliljebl** [comment]
Fixed in repo.

We needed to do 2 playhead seeks to get editors inited correctly, but during testing this did not cause any user visible effects. It is possible that on some circumstances this may cause monitor to flash on kf edit inits, but the programming was much easier like this, so we will go with this for now.
