### ISSUE TITLE
"%" sign should be escaped in flowblade.po

### ISSUE THREAD

**Issue by JeanLucCoulon** [jliljebl/flowblade#551]
Flowblade version : 1.16.0, git trunk
Debian sid

in ./Flowblade/tools/gmic.py
there is the following line:
update_info = _("Rendering video, ") + str(int(fraction * 100)) + _("% done")

the % at the end should be escaped doubling it:
update_info = _("Rendering video, ") + str(int(fraction * 100)) + _("%% done")

otherwise, there is a compilation error of the po file:
msgfmt -c --statistics flowblade.po -o flowblade.mo
flowblade.po:6782: format specifications in 'msgid' and 'msgstr' for argument 1 are not the same
msgfmt: found 1 fatal error
1609 translated messages, 36 fuzzy translations, 90 untranslated messages.

msgfmt is looking for a %d, %<something>, and <something> should be the same in the msgstr and msgid.

Regards 
Jean-Luc

**Comment by jliljebl** [comment]
I've always used:

    msgfmt --output-file=$MO_FILE $PO_FILE

and it continues to work fine. Command

    msgfmt -c --statistics flowblade.po -o flowblade.mo

seems to do *--check-format, --check-header, --check-domain*. Flowblade is not using any formatted strings. There was an issue #160 filed 3 years ago and I haven't done anything about it yet, and I just marked it  *contributions hoped* because I have to admit that I'm not planning to spend development time on it.

If that gets done I will reopen this, but for now I'm marking this *wontfix*.

The workaround is to not use switch *-c* when compiling Flowblade *.mo* files.
