### ISSUE TITLE
[Feature request] Color Picker a.k.a Eyedropper

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#596]
This tool will simplify the "color selection". When the user needs to remove the selected color, he will simply click on it on the monitor using the "Eyedropper". This tool is carried in Gimp, Kdenlive and other image and video editors. The Eyedropper tool would also speed up work in Flowblade.
Kdenlive
![_2019-02-03_22-51-55](https://user-images.githubusercontent.com/26217756/52181961-f95d4700-2808-11e9-90f9-c88364476c49.png)
Pinta
![_2019-02-03_23-11-50](https://user-images.githubusercontent.com/26217756/52181972-2c9fd600-2809-11e9-8e01-a2c027d427cb.png)

**Comment by jliljebl** [comment]
I agree that this would be improvement, but last I checked the widget wasn't available for GTK3 color selector, this is (should be) part of GTK toolkit not Flowblade application.

The worst part is that Wayland doesn't let applications even get any information outside application window so for Wayland this cannot even be done in a way that lets user get color from outside of the application.

Doing this in app would require direct programming on both X11 and Wayland a big, big project.

I'll look how other apps do htis, particularly how Gimp does this with Gtk3 but I don't expect quick progress.

**Comment by jliljebl** [comment]
It just occurred to me that:
  *  if we are willing to accept the restriction of *only being able to pick colors from current monitor frame*
  * so we would not be able pick colors from *other applications*

then we can do this relatively easily because we have access to displayed video frames.

This should cover most cases and user can pick colors from other applications by creating a screenshot.

This will get done after Python 3 port, but should not present any difficulties if done this way.

**Comment by jliljebl** [comment]
I added color picker for all color select editors. 

User can only pick colors from monitor but that is probably a 95% use case so that's fine. One thing that was not possible to do was to display color picker cursor because SDL controls cursor over monitor area and we do not have API to set it from Python side. The alternative solution was to use standard cursor and an info text, seemed quite good when testing.

Will be in 2.8.
