### ISSUE TITLE
Feature request: button to add clips to timeline

### ISSUE THREAD

**Issue by welon68** [jliljebl/flowblade#605]
Hello, 
Please add new button ( or shortcut )
"a" - add clip  to timeline 
"ctrl + a"  add all clips from bin to timeline 

:-)
please, please, please :-)
best regards
Welon ;-)

**Comment by jliljebl** [comment]
I think this would be useful. I remember thinking about adding a menu item for something like "Add Selected Media items into Timeline",. Some points:

  * we can't use Ctrl + A because that already selects all media items (if media panel has keyboard focus) and has a very established semantics of "select all"
  *  we should probably add both timeline keyboard shortcut and media panel menu item
  * single character keyboard shortcuts (like 1-9, "t","y"..etc) require timeline to have keyboard  focus because otherwise we could be trying to write something so this needs to be the case here too
  * "A" could be a candidate for "Add Selected Media items to Timeline" timeline keyboard shortcut as suggested.

This is quite easy, so we can get this done for 2.2.

**Comment by Godtec** [comment]
Shortcut Keys in general would be great idea!
Here is a link below for the Final Cut Pro keys. Just an idea...

[https://support.apple.com/kb/PH12724?locale=en_CA&viewlocale=en_US](url)

Thanks for All the Hard work... Looking GOOD!
Mikek

**Comment by jliljebl** [comment]
This is in repo now, will be in 2.2.

We added menu items "Append All Media to Timeline", "Append Selected Media to Timeline" and timeline keyboard shortcut "A" which does "Append Selected Media to Timeline".
