### ISSUE TITLE
Composers cut background image

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#644]
With added any composer (for example, “Picture in Picture”). The background image is cropped to the size of the source image (screen 1). When I add any Alpha filter, even if I do not change the parameters of this alpha filter, the background image in the frame again acquires its boundaries (screen 2).
Screen 1.
![flowblade](https://user-images.githubusercontent.com/26217756/55158057-0c3c2a00-516f-11e9-8570-44adfe311aa2.png)
Screen 2.
![flowblade2](https://user-images.githubusercontent.com/26217756/55158086-1eb66380-516f-11e9-8c63-cf2fbcd62691.png)

**Comment by jliljebl** [comment]
I'll give this a look after I get the rotomask editor done next week.

**Comment by jliljebl** [comment]
So, does clicking on "Align" checkbox help? See image:
![prfess_align](https://user-images.githubusercontent.com/1823444/56312619-3626b200-6159-11e9-96e1-cac7d0cd4483.png)

**Comment by jliljebl** [comment]
You will need to move the image to different position to get the same position as before "Align" but you should be able to do it.

**Comment by smolnp** [comment]
Yes I can check the box "Align" and move the image in the frame by taking another Composer, for example "Region".

![Снимок экрана_2019-04-17_22-22-15](https://user-images.githubusercontent.com/26217756/56315091-886ad180-615f-11e9-93b9-686e67eb6415.png)
But still faster and easier to turn on any alpha filter.

**Comment by jliljebl** [comment]
Yeah, this is how MLT has always worked and I don't think we can change how existing stuff works. There are 2 things that can be done:

1) Make "Align" on by default on those Compositors that has it.
2) Add Documentation here: http://jliljebl.github.io/flowblade/webhelp/compositor.html and in the docs that come with the app

Do you think 1) is a good idea?

I've always thought that Compositors are a bit of a usability mess in Flowblade (and all KDEnlive too) but with Python 3, SDL thing and many others still needing to done we will need to live with this for quite some time still.

**Comment by smolnp** [comment]
I did two video tutorials, one on Flowblade https://www.youtube.com/watch?v=iaP_oHIpbKc, the other on Kdenlive https://www.youtube.com/watch?v=EPVnhuNMo74. Kdenlive lacks this problem today.
p.s. Yes, a good idea to display known Issues in the documentation. Now a lot of work, in the winter I will definitely translate the section "Known Issues" into Russian for Russian-speaking users. https://smolnp.github.io/flowblade/index.html.

**Comment by smolnp** [comment]
If I'm not mistaken, in Kdenlive, they solved this problem by adding compositing tracks https://userbase.kde.org/Kdenlive/Manual/Timeline/Editing#Track_Compositing_-_None

**Comment by jliljebl** [comment]
They have hidde always on  "qtblend" compositor arranged in order that you get the layered thing, not the the order Flowlblade does:

<transition id="transition6">
   <property name="a_track">0</property>
   <property name="b_track">4</property>
   <property name="compositing">0</property>
   <property name="distort">0</property>
   <property name="rotate_center">0</property>
   <property name="mlt_service">qtblend</property>
   <property name="always_active">1</property>
   <property name="internal_added">237</property>
  </transition>

Shotcut has "cairoaffineblend" that i made in -12 doing basically the same thing. I can use "qtblend" because any Qt related will crash Flowblade, these will always run Qt main loop which cannot be combined with Gtk applications.

This will get revisited some time, but not immediately, its a big change.

**Comment by smolnp** [comment]
The problem remained, only in one composer "Wipe / Translate". I think this problem can be closed.
