### ISSUE TITLE
Feature Request: Adjust clip speed beyond 600%

### ISSUE THREAD

**Issue by mjones129** [jliljebl/flowblade#648]
I'm running:
1.) Flowblade version 2.0
2.) MLT version 6.6.0
3.) Ubuntu 18.04 LTS

I love flowblade so much. Seriously, you guys have done some amazing work. Today I ran into a limitation with the speed adjustment when I right click on a clip and select Export To Tool > Slow/Fast motion. I'd love to be able to adjust the speed of a clip beyond 600% and/or input a desired runtime that adjusts the playback speed to match. I've got 10.5 hours of screen recordings I need to speed up and squish into about 10.5 minutes. 

Thanks guys!

**Comment by jliljebl** [comment]
Thanks for the encouragement.

Seems the max speedup available in "timewarp" producer is 2900%, so we can this easily.

This is now a GUI problem, if this is represented by a slider it will be very inaccurate around the 100% makr and when doing slow-mo. 

We need to change the GUI somehow but otherwise should be quite easy.

**Comment by jliljebl** [comment]
This is now in repo, will be in 2.2.

We had to drop the slider and provide only text input to give speed.
