### ISSUE TITLE
Subtitles in Flowblade.

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#653]
I recently learned that with ffmeg you can add subtitles to a video file (https://trac.ffmpeg.org/wiki/ExtractSubtitles). But of all the free video editors on GNU linux, subtitles can only be stitched in Avidemux.
![avidemux](https://user-images.githubusercontent.com/26217756/57034906-6726dc80-6c59-11e9-871f-99206b519d67.png)
Is it possible in the future to add subtitles to video clips in Flowblade?
p.s. Ideally, create and edit subtitles in Flowblade.

**Comment by jliljebl** [comment]
I fully agree that this would be a useful feature. Question as usual on the required time investment and what other stuff there is on the agenda.

Since subtitles can be stitched with *ffmpeg* from text files onto video stream using ffmped we would need to add a interactive GUI editor.

Unfortunately *ffmpeg subtitles* filter seems to be on MLT blacklist so we can't use that
https://github.com/mltframework/mlt/blob/master/src/modules/avformat/blacklist.txt

Other approach could be:
  * create GUI editor that allows creting timed subtitle items so that
     * user can interactively select timecodes from video file
     * create items with text and length
     * parse out a supported text file format like : https://en.wikipedia.org/wiki/SubStation_Alpha 
  * provide possibility to render output video file

However, there seems to be dedicated subtitling tools available. 
https://lintut.com/best-subtitle-editors-for-linux/

Gnome Subtitles had last source commit  7 days ago so it seems to an (at least somewhat) active project and SubtitleEdit had last commit day ago so the projects are alive.

I believe it would be best to not compete with a dedicated tools at this point and fully focus on more relevant features for a video editor so I unfortunately have to close this as *wontfix*. Looking at the  screenshots in the list in the link I don't believe I can do much better then those programs do.

**Comment by dvdlvr** [comment]
I am actually working on subtitle support for Flowblade.
This is not an easy task and it's slow progress, because I have to try and find the best of several solutions.
The big advantage to my current approach is that it can extract subtitles from clips you add (If present - and only text subs, not graphic subs) and you can edit or add subs to clips, as well as independently edit subs on the timeline.
The subs will be saved in separate files for both the clips and the project.
When the project is rendered, a separate sub file will also be generated - so not merged with the video. Any decent player will be able to use the subfiles.

This is not something that will happen in the immediate future. Maybe not even this year, but this functionality, for me, has multiple advantages over the separate subtitle editors that I've worked with. Especially that you can move subs from your clips to the timeline and that it becomes a more integrated environment.

**Comment by jliljebl** [comment]
Great, I will definitely accept contributions on this and reopened the issue. I haven't done any subtitles myself so it is difficult for me asses what would be best approach but if we can get comparable or better GUI interactivity then we have definitely something valuable to offer.

Hopefully you find a working solution and we can add this feature and have something unique on this area.

**Comment by jliljebl** [comment]
If you have some specific problems with Flowblade code base comment here and I will give pointers if I can.

**Comment by jliljebl** [comment]
Closing this as *not active* for now, maybe we get new developments later.
