### ISSUE TITLE
Proxy files not created in v2.0.0

### ISSUE THREAD

**Issue by Efenstor** [jliljebl/flowblade#660]
Please include the following information.
1) Flowblade version (Help->About): 2.0.0 (latest git clone)
2) MLT version (Help->Runtime Environment): 6.12.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Debian 10 (Buster)
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
1. Import any video file
2. Right click > Render Proxy File
3. Nothing happens, and no wonder: here's what I see in the terminal:

```
Traceback (most recent call last):
  File "/home/olaf/bin/flowblade/flowblade-trunk/Flowblade/projectaction.py", line 1945, in media_file_menu_item_selected
    proxyediting.create_proxy_menu_item_selected(media_file)
  File "/home/olaf/bin/flowblade/flowblade-trunk/Flowblade/proxyediting.py", line 538, in create_proxy_menu_item_selected
    _do_create_proxy_files(media_files)
  File "/home/olaf/bin/flowblade/flowblade-trunk/Flowblade/proxyediting.py", line 543, in _do_create_proxy_files
    proxies_dir = _get_proxies_dir()
  File "/home/olaf/bin/flowblade/flowblade-trunk/Flowblade/proxyediting.py", line 614, in _get_proxies_dir
    return userfolders.get_render_dir() + "/proxies"
NameError: global name 'userfolders' is not defined
```
And indeed: as far as I remember v1.x had some variable in the Preferences for defining location of user files, v2.0 has it not.

Also when I click Edit > Disk Cache Manager, I get this:
```
Traceback (most recent call last):
  File "/home/olaf/bin/flowblade/flowblade-trunk/Flowblade/editorwindow.py", line 229, in <lambda>
    ('DiskCacheManager', None, _('Disk Cache Manager'), None, None, lambda a:diskcachemanagement.show_disk_management_dialog()),
  File "/home/olaf/bin/flowblade/flowblade-trunk/Flowblade/diskcachemanagement.py", line 152, in show_disk_management_dialog
    _panels = _get_disk_dir_panels()
  File "/home/olaf/bin/flowblade/flowblade-trunk/Flowblade/diskcachemanagement.py", line 170, in _get_disk_dir_panels
    panels.append(DiskFolderManagementPanel(appconsts.AUDIO_LEVELS_DIR, _("Audio Levels Data"), RECREATE_WARNING))
NameError: global name 'appconsts' is not defined
```

**Comment by dvdlvr** [comment]
This works fine for me.
Maybe there's a problem because you haven't selected the default render 
folder. Obviously that shouldn't happen, but I don't know at the moment 
why this is.

If you go to the Preferences and select your prefered 'Render' folder, 
then the proxies folder will be created underneath that directory and 
proxy rendering should work.

**Comment by Efenstor** [comment]
> If you go to the Preferences and select your prefered 'Render' folder, then the proxies folder will be created underneath that directory and proxy rendering should work.

But I don't see such a field in Preferences: https://yadi.sk/d/dc5r_I6uRjmqkQ

**Comment by dvdlvr** [comment]
That's weird. I have it under the general tab. I'll have a look, unless someone else knows what's happening. Sent from my Huawei tablet-------- Original Message --------Subject: Re: [jliljebl/flowblade] Proxy files not created in v2.0.0 (#660)From: Efenstor To: jliljebl/flowblade CC: dvdlvr ,Comment 
If you go to the Preferences and select your prefered 'Render' folder, then the proxies folder will be created underneath that directory and proxy rendering should work.

But I don't see such a field in Preferences: https://yadi.sk/d/dc5r_I6uRjmqkQ

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jliljebl/flowblade/issues/660#issuecomment-491519173",
"url": "https://github.com/jliljebl/flowblade/issues/660#issuecomment-491519173",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Efenstor** [comment]
Here is my prefs file, may be it helps somehow. My installation is a clean new installation of the latest master branch snapshot, not an upgrade from v1.x. I tried the flatpak version from flathub.org and the Preferences dialog is the same: no way to define the user files location. I don't know what else... I use a hidpi monitor, 192 dpi in Gnome Settings. May be that's related?

[prefs.zip](https://github.com/jliljebl/flowblade/files/3169276/prefs.zip)

**Comment by jliljebl** [comment]
Not sure yet what is going on but will look for 2.2.

**Comment by jliljebl** [comment]
The patch rtomj fixed this, so Proxy rendering should keep working for 2.2
