### ISSUE TITLE
Easier text insertion

### ISSUE THREAD

**Issue by liquid600pgm** [jliljebl/flowblade#667]
Please include the following information.
1) Flowblade version (Help->About): 2.0
2) MLT version (Help->Runtime Environment): 6.12.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Fedora 30
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

I think Flowblade would benefit from a way of adding text without having to use the titler.
The titler is pretty annoying because you have to export the text into a PNG first. I've seen a "Text" filter in other applications, which worked pretty well, but in my opinion, the approach MAGIX Vegas takes is the best one (a Media Generator, it's similar to the titler but you don't have to save a file to use the text)

**Comment by jliljebl** [comment]
I agree that some feature like this could be an improvement in some cases, having always to create files and composite them will be slower adding text using a filter.

I will look  the MAGIX Vegas thing from Youtube etc. It may be that e.g KDEnlive is using some Qt based solution which would necessitate creating my own filter.

I'm not adding this into feature queue yet because there are some more urgent tasks and the required effort is not know yet, but something like 2.8 could be possible for this, I will comment later with additional info.

**Comment by jliljebl** [comment]
I read MLT source code a bit and unfortunately it seems that this is not doable at the moment.

Qt was required for *dynamictext* filter and *pango* producer did basically the same as current Titler but required gtk2 which we are looking to replace in year or two.

Once we have image producer ported to Gtk3 we can give this another look, maybe create  *dynamictext* variant not depending on Qt.

Closing as *wontfix* for now because there is no clear timetable for when any additional work will done on this.
