### ISSUE TITLE
NVENC ISSUE

### ISSUE THREAD

**Issue by AV11D724** [jliljebl/flowblade#677]
Please include the following information.
1) Flowblade version (Help->About):
2) MLT version (Help->Runtime Environment):
3) Your distribution (Ubuntu, Debian, Mint etc.):
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

1. Flowblade Version 2.0.0
2. MLT Version 6.13.0
3. Linux Mint 19.1(Based on Ubuntu 18.04 LTS)
4. Cuda 10.1 update 1
5. Nvidia Drivers 430.26

NVENC issue: When having a video or multiple videos in the timeline, going into render args,  and typing h264_nvenc in the vcodec option, video renders successfully but only with audio, no video(black screen(or no visual video) after pressing play) and  a black thumbnail. I have compiled FFmpeg successfully with nvenc, cuda, etc. And for other applications it(nvenc) seems to work just fine but not this one. I am using the flathub version of the package. An indication that nvenc is working properly(in any program) is usually you will see at least to some extent activity in  Video Engine Utilization percentage part using nvidia-settings but there is no reported activity when using this codec in flowblade. 

That being said I really do love this program and you guys did a great job with 2.0.0 it is one of the most stable & intuitive video editors i have used to date!! It seems as if there is only a few tweaks away from getting flowblade to be able to recognize the system-installed ffmpeg(or not I could be massively wrong) and being able to accelerate gpu renders using nvidia gpus. Wheter or not theres a fix I just hope this helps.. 

Thank You

**Comment by dvdlvr** [comment]
Hi, Flowblade uses mlt to render, not ffmpeg. Although the parameters are similar to and related to the ffmpeg parameters they are not 1-to-1 the same. The nvenc parameter is not (currently) implemented in mlt. You can see all parameters in the mlt doc: https://www.mltframework.org/plugins/ConsumerAvformat/-------- Original Message --------Subject: [jliljebl/flowblade] NVENC ISSUE (#677)From: AV11D To: jliljebl/flowblade CC: Subscribed Please include the following information.
Flowblade version (Help->About):MLT version (Help->Runtime Environment):Your distribution (Ubuntu, Debian, Mint etc.):If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:
Flowblade Version 2.0.0MLT Version 6.13.0Linux Mint 19.1(Based on Ubuntu 18.04 LTS)Cuda 10.1 update 1Nvidia Drivers 430.26
NVENC issue: When having a video or multiple videos in the timeline, going into render args,  and typing h264_nvenc in the vcodec option, video renders successfully but only with audio, no video(black screen(or no visual video) after pressing play) and  a black thumbnail. I have compiled FFmpeg successfully with nvenc, cuda, etc. And for other applications it(nvenc) seems to work just fine but not this one. I am using the flathub version of the package. An indication that nvenc is working properly(in any program) is usually you will see at least to some extent activity in  Video Engine Utilization percentage part using nvidia-settings but there is no reported activity when using this codec in flowblade.
That being said I really do love this program and you guys did a great job with 2.0.0 it is one of the most stable & intuitive video editors i have used to date!! It seems as if there is only a few tweaks away from getting flowblade to be able to recognize the system-installed ffmpeg(or not I could be massively wrong) and being able to accelerate gpu renders using nvidia gpus. Wheter or not theres a fix I just hope this helps..
Thank You

**Comment by AV11D724** [comment]
Thank you for the very quick and detailed answer!! Just a curious question though, since flowblade uses and depends on mlt, What would a parameter in mlt like -enable-opengl do for flowblade? Im guessing nothing?

> Hi, Flowblade uses mlt to render, not ffmpeg. Although the parameters are similar to and related to the ffmpeg parameters they are not 1-to-1 the same. The nvenc parameter is not (currently) implemented in mlt. You can see all parameters in the mlt doc: https://www.mltframework.org/plugins/ConsumerAvformat/-------- Original Message --------Subject: [jliljebl/flowblade] NVENC ISSUE (#677)From: AV11D To: jliljebl/flowblade CC: Subscribed Please include the following information. Flowblade version (Help->About):MLT version (Help->Runtime Environment):Your distribution (Ubuntu, Debian, Mint etc.):If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: Flowblade Version 2.0.0MLT Version 6.13.0Linux Mint 19.1(Based on Ubuntu 18.04 LTS)Cuda 10.1 update 1Nvidia Drivers 430.26 NVENC issue: When having a video or multiple videos in the timeline, going into render args, and typing h264_nvenc in the vcodec option, video renders successfully but only with audio, no video(black screen(or no visual video) after pressing play) and a black thumbnail. I have compiled FFmpeg successfully with nvenc, cuda, etc. And for other applications it(nvenc) seems to work just fine but not this one. I am using the flathub version of the package. An indication that nvenc is working properly(in any program) is usually you will see at least to some extent activity in Video Engine Utilization percentage part using nvidia-settings but there is no reported activity when using this codec in flowblade. That being said I really do love this program and you guys did a great job with 2.0.0 it is one of the most stable & intuitive video editors i have used to date!! It seems as if there is only a few tweaks away from getting flowblade to be able to recognize the system-installed ffmpeg(or not I could be massively wrong) and being able to accelerate gpu renders using nvidia gpus. Wheter or not theres a fix I just hope this helps.. Thank You —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by dvdlvr** [comment]
I don't know the ins and outs of every parameter. If a parameter is in the list then you can try it and see if it does anything. Basically the parameters you can use without problems is whatever influences the render quality. Sent from my Huawei tablet-------- Original Message --------Subject: Re: [jliljebl/flowblade] NVENC ISSUE (#677)From: AV11D To: jliljebl/flowblade CC: dvdlvr ,Comment Thank you for the very quick and detailed answer!! Just a curious question though, since flowblade uses and depends on mlt, What would a parameter in mlt like -enable-opengl do for flowblade? Im guessing nothing?



Hi, Flowblade uses mlt to render, not ffmpeg. Although the parameters are similar to and related to the ffmpeg parameters they are not 1-to-1 the same. The nvenc parameter is not (currently) implemented in mlt. You can see all parameters in the mlt doc: https://www.mltframework.org/plugins/ConsumerAvformat/-------- Original Message --------Subject: [jliljebl/flowblade] NVENC ISSUE (#677)From: AV11D To: jliljebl/flowblade CC: Subscribed Please include the following information. Flowblade version (Help->About):MLT version (Help->Runtime Environment):Your distribution (Ubuntu, Debian, Mint etc.):If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: Flowblade Version 2.0.0MLT Version 6.13.0Linux Mint 19.1(Based on Ubuntu 18.04 LTS)Cuda 10.1 update 1Nvidia Drivers 430.26 NVENC issue: When having a video or multiple videos in the timeline, going into render args, and typing h264_nvenc in the vcodec option, video renders successfully but only with audio, no video(black screen(or no visual video) after pressing play) and a black thumbnail. I have compiled FFmpeg successfully with nvenc, cuda, etc. And for other applications it(nvenc) seems to work just fine but not this one. I am using the flathub version of the package. An indication that nvenc is working properly(in any program) is usually you will see at least to some extent activity in Video Engine Utilization percentage part using nvidia-settings but there is no reported activity when using this codec in flowblade. That being said I really do love this program and you guys did a great job with 2.0.0 it is one of the most stable & intuitive video editors i have used to date!! It seems as if there is only a few tweaks away from getting flowblade to be able to recognize the system-installed ffmpeg(or not I could be massively wrong) and being able to accelerate gpu renders using nvidia gpus. Wheter or not theres a fix I just hope this helps.. Thank You —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by AV11D724** [comment]
> I don't know the ins and outs of every parameter. If a parameter is in the list then you can try it and see if it does anything. Basically the parameters you can use without problems is whatever influences the render quality. Sent from my Huawei tablet-------- Original Message --------Subject: Re: [jliljebl/flowblade] NVENC ISSUE (#677)From: AV11D To: jliljebl/flowblade CC: dvdlvr ,Comment Thank you for the very quick and detailed answer!! Just a curious question though, since flowblade uses and depends on mlt, What would a parameter in mlt like -enable-opengl do for flowblade? Im guessing nothing? Hi, Flowblade uses mlt to render, not ffmpeg. Although the parameters are similar to and related to the ffmpeg parameters they are not 1-to-1 the same. The nvenc parameter is not (currently) implemented in mlt. You can see all parameters in the mlt doc: https://www.mltframework.org/plugins/ConsumerAvformat/-------- Original Message --------Subject: [jliljebl/flowblade] NVENC ISSUE (#677)From: AV11D To: jliljebl/flowblade CC: Subscribed Please include the following information. Flowblade version (Help->About):MLT version (Help->Runtime Environment):Your distribution (Ubuntu, Debian, Mint etc.):If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: Flowblade Version 2.0.0MLT Version 6.13.0Linux Mint 19.1(Based on Ubuntu 18.04 LTS)Cuda 10.1 update 1Nvidia Drivers 430.26 NVENC issue: When having a video or multiple videos in the timeline, going into render args, and typing h264_nvenc in the vcodec option, video renders successfully but only with audio, no video(black screen(or no visual video) after pressing play) and a black thumbnail. I have compiled FFmpeg successfully with nvenc, cuda, etc. And for other applications it(nvenc) seems to work just fine but not this one. I am using the flathub version of the package. An indication that nvenc is working properly(in any program) is usually you will see at least to some extent activity in Video Engine Utilization percentage part using nvidia-settings but there is no reported activity when using this codec in flowblade. That being said I really do love this program and you guys did a great job with 2.0.0 it is one of the most stable & intuitive video editors i have used to date!! It seems as if there is only a few tweaks away from getting flowblade to be able to recognize the system-installed ffmpeg(or not I could be massively wrong) and being able to accelerate gpu renders using nvidia gpus. Wheter or not theres a fix I just hope this helps.. Thank You —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread. —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.



Thanks for the help! Much appreciated!!
