### ISSUE TITLE
Flatpak: Vectorscope and RGBParade not working

### ISSUE THREAD

**Issue by jliljebl** [jliljebl/flowblade#701]
Issue brought up in Forum: https://github.com/jliljebl/flowblade-forum/issues/17

**Comment by DroWnThePoor** [comment]
MLT 6.17
Flowblade 2.2.0 from Flatpak
Ubuntu 18.04
It may not even be a bug, but under the monitor in the far right corner you can select Image/VectorScope/RGB Parade, I've switched to them all and I'm wondering what I have to do for the Vectorscope or RGBparade to appear?

**Comment by jliljebl** [comment]
Confirmed, on Flatpak Vectorscope and RGBParade do not work. The fix will probably come with Flatpak for 2.4, there isn't really man power to do point releases for bug fixes.

**Comment by jliljebl** [comment]
The reason for this bug is real simple: filters **fre0r.vectorscope** and **frei0r.rgbparade** are missing from Flatpak.

We need to update the build manifest in some way. I don't know why these filters are currently  not included along with all the other frei0r filters.

**Comment by DroWnThePoor** [comment]
Okay man thank you for letting me know, that's a good enough reason for me to switch to a Deb package. Also wanted to say thank you for the amazing software. I did a favorable review on my YouTube channel when you released 2.0.

Sent from BlueMail<http://www.bluemail.me/r?b=15635>
On Sep 16, 2019, at 3:22 PM, jliljebl <notifications@github.com<mailto:notifications@github.com>> wrote:

The reason for this bug is real simple: filters fre0r.vectorscope and frei0r.rgbparade are missing from Flatpak.

We need to update the build manifest in some way. I don't know why these filters are currently not included along with all the other frei0r filters.

**Comment by eszlari** [comment]
This is fixed now for the flatpak by bundling gavl (http://gmerlin.sourceforge.net/), which is a build dependency of these two filters.

**Comment by jliljebl** [comment]
@eszlari Thank you for the fix, tested and works here great too.

**Comment by eszlari** [comment]
@jliljebl It would be nice, if you could open flatpak specific bugs under Flathub's bug tracker in the future, so I could see them sooner:

https://github.com/flathub/io.github.jliljebl.Flowblade/issues

**Comment by jliljebl** [comment]
OK, will do.
