### ISSUE TITLE
Clip/Compositor Linked Movement

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#705]
Flowblade 2.2 (MLT 6.6.0) on xubuntu 18.04

Moving a media element does not move a compositor along with it. Which means that making any changes after compositors have been applied rather cumbersome and error prone.

Ideally I'd like to see compositors being moved along with their parent clip by default, possibly with a modifier key to only move the clip leaving the compositor where it is (presuming there is a reason to want that in the first place).

**Comment by jliljebl** [comment]
There will be developments on this aspect of the application the for next release.

Using "Move" tool, Multitrack ripple delete and "Edit"->"Sync All Compositors" edit action from menu make it at least for me quite easy to  work with free moving compositors but there can be differing opinions on this for sure.

I'm closing with out this without label because once the work  that is in progress lands this will outdated, you will be able to select if you wish to move compositors with clips by default.
