### ISSUE TITLE
Flowblade 2.2.1 point release

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#713]
Over the next few days I'll probably file a few more trivial PRs fixing some other minor nitpicks.

However, as far as I can tell there aren't yet any scary big changes in master, mostly just some bugfixes and polish...

I'm wondering how you would feel about doing a point release in the next week or two or so?

Keeping these changes stuck in git master until bigger changes happen and settle down won't benefit anybody...

**Comment by jliljebl** [comment]
Since 2.2 we have had the move from Python 2 to Python 3, maybe the biggest possible change from release point of view. There will be still some undiscovered regressions still in the code base and just doing the Flatpak port and testing will take who knows how many hours.

Overall I have found doing the releases the least fun part of the process (with release notes, testing etc.) and have decided to to move to 2 releases a year. Also, keeping total control over release schedule so that I can approach it in a relaxed and non-stressful way is something I'm absolutely not willing to negotiate in any way, shape or form.

Next release is coming sometime in December, at my convenience, date depending  on many factors, including a lot of stuff not visible on this list, such as my life here in Helsinki, Finland.

**Comment by pmjdebruijn** [comment]
Just as a matter of FYI, I'm "maintaining" a backport of Flowblade 2.2 (including MLT 6.16) for Ubuntu 18.04 here:

https://launchpad.net/~pmjdebruijn/+archive/ubuntu/flowblade

The Flowblade includes a bunch of cherrypicks from git master.
