### ISSUE TITLE
I want to write a guide, can you give me some information?

### ISSUE THREAD

**Issue by classenu** [jliljebl/flowblade#716]
I want to write a "Getting Started Guide" in Chinese(zh-cn) and English, but I don't fully understand the function of Flowblade. Can you give me some information? Such as the function of the filter options, etc.

Here are some free Flowblade support I have provided:
- 1. https://bbs.archlinuxcn.org/viewtopic.php?id=10007
- 2. https://forums.debiancn.org/t/topic/2035
- 3. https://forum.suse.org.cn/t/topic/11727

Please include the following information.
1) Flowblade version (Help->About):2.2.0
2) MLT version (Help->Runtime Environment):6.17.0
3) Your distribution (Ubuntu, Debian, Mint etc.):Debian
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.: No.

**Comment by jliljebl** [comment]
Hi, the best thing to do would be to post specific questions here: https://github.com/jliljebl/flowblade-forum/issues

This Issues list for bug reports and feature requests so, I'll close this issue here, please post questions on forum.

I can't answer an overly broad question such as functionality of *all* filter options, but I can give info a specific filters.
