### ISSUE TITLE
Can I denoise the sound within flowblade?

### ISSUE THREAD

**Issue by yichuang-zh** [jliljebl/flowblade#719]
The mp4 video improted into flowblade is noisy. Now my solution to reduce noise is: 
1. After finishing all the editing work, rendered a mp4 file and import this mp4 file into audacity
2. In audacity, run "Effect > Noise Reduction" to reduce the noise and export a clean mp3 file
3. In flowblade, import the clean mp3 file to the same sequence 
4. Mute the mp4 track, click the "Render" button

I did not found a noice reduction menu within flowblade, even in the "Add Filter > Audio" or "Add Filter > Audio Filter".

Is noise reduction necessary to use another software to achieve?
 

Please include the following information.
1) Flowblade version (Help->About): 2.2.0
2) MLT version (Help->Runtime Environment): 6.17.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Debian/Stretch
4) If possible, try to provide step-by-step instructions on how to reproduce the issue. From developer point of view this is the easieast way to understand what is happening.:

**Comment by jliljebl** [comment]
I looked at Audacity source code.

Their *Noise Reduction* filter seems to be their own code, not a Ladspa or Sox filter, so there is no easy way to have that exact filter in Flowblade.

In Flowblade we have *Noise Gate* and *Equalize - Multiband* filters in "Audio Filters" group that can be used for similar purposes.

Closing as *wontfix* because there won't be any immediate developments on this.
