### ISSUE TITLE
Film style editing

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#726]
Flowblade 2.2 (MLT 6.16)

At first glance I liked the concept of film style editing, given you'd always want continuous content for your main movie track (V1).

However, I noticed this auto-placement is also being done for the other tracks, which makes little sense to me. When I want to composite something on my main video it is going to be at a specific location, and there's no reason why any other track should have continuous content.

Does this make sense? Or do I misunderstand how film style editing should be done?

**Comment by jliljebl** [comment]
This behavior is tool dependent, it happens when you use "Insert" tool. Use "Move" tool when you wish to not have auto placement.

"Film Style" is just preset that makes "Insert" tool the default (first) tool. It is offered as preset because this was the way Flowblade worked pre-2.0. Default tool was changed to "Move" in 2.0 because most users referred this that way.

"Insert" is at its most useful when arranging clips on timeline to create a rough cut, changing clips  order to quickly test different ways to tell a story is  the first phase of workflow for most professional editors with non-linear editors. Most beginner editors do not do this rough cut, they just start to edit clip by clip right away and in that case "Move" is better default.

You can freely change order of tools with the menu you get from "Flowblade" icon.

**Comment by pmjdebruijn** [comment]
Right, though the point I'm trying to make is, in my tiny amount of experience, it would seem, that the insert tool is nice for ==V1 and the move tool is nice for !=V1, which makes me wonder how many people prefer Move, simply because Insert ""misbehaves"" on other tracks.

I would probably really enjoy an intelligent tool, which behaves like insert on ==V1, and behaves like move on !=V1

I'm guessing this stands out to me, because as a beginner, my workflow is probably much more chaotic (to put it mildly) as opposed to experienced video editors, in which case tool switching feels more cumbersome.

**Comment by jliljebl** [comment]
There are many ways to do this but this is from older Avids which I found quite to my liking at the time. Current Avid has some positioning dependent thing which offers different "tool" depending on where cursor is. similar to "Multitrim" tool in Flowblade . It is obviously possible to do a "Move/insert" tool in a same way (e.g. clip bottom half giving move, clip top half giving Insert) but don't really fancy spending time on that.
