### ISSUE TITLE
seems regression in the interface

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#744]
screen resolution 1368x768
there are no stand-alone tools on the middle panel
![Снимок экрана от 2019-10-16 22-31-27](https://user-images.githubusercontent.com/26217756/66953601-87135680-f067-11e9-82d3-6ed86048d508.png)
but there is a wonderful function to select the "encoding format", which disappears at higher screen resolutions, for example 1600x900 
![Снимок экрана от 2019-10-16 22-33-10](https://user-images.githubusercontent.com/26217756/66953678-a6aa7f00-f067-11e9-8f26-e7b726714a35.png)
in the Project panel, the Project Events area is located
![Снимок экрана от 2019-10-16 22-38-44](https://user-images.githubusercontent.com/26217756/66953722-b629c800-f067-11e9-8e3e-f125b70b3b34.png)
which cannot be found when choosing a mode with 3 panels (1450px +)

**Comment by jliljebl** [comment]
Alright, I'll look into this.

**Comment by smolnp** [comment]
I missed something, but I don’t remember exactly what ... unfortunately now I have little time for a hobby I will wait for a vacation, then I will definitely find :-)

**Comment by jliljebl** [comment]
Project Events feature got dropped from higher resolution GUI, I'm looking to remove it from smaller resolutions too.

**Comment by smolnp** [comment]
the "open file in bin" function seems to be missing at a resolution below 1450px +

**Comment by jliljebl** [comment]
> screen resolution 1368x768
there are no stand-alone tools on the middle panel

Yes, there is no space below 1400px width for those, those can be accessed from tools menu.

**Comment by jliljebl** [comment]
> but there is a wonderful function to select the "encoding format", which disappears at higher screen resolutions, for example 1600x900

This is a regression and a quite bad one, needs to be fixed, thanks.

**Comment by smolnp** [comment]
" I'm looking to remove it from smaller resolutions too." And there will be no replacement? Sometimes it’s not bad to be able to return to the right time point.

**Comment by jliljebl** [comment]
There is no undo, it is just an event log that gives information.

I will data available via Project menu later, but you are the first one noticing that its gone, so it has not been a much missed functionality.

**Comment by smolnp** [comment]
To be honest, I don’t notice many things, they write to me on the forums and if I don’t understand something, I write about this problem here

**Comment by jliljebl** [comment]
> the "open file in bin" function seems to be missing at a resolution below 1450px +

Yes, another space issue, this time maybe more of the vertical space problem, I'll look if there is anything that can done about this but it could be that the pixels just ain't there.

We have dropped some secondary functionality to get GUI working on all possible resolutions. This is a difficult problem that keeps causing problems because I have refused to make render panel scrollable for design reasons, a scrollable panel would look very amateurish in my view.

**Comment by jliljebl** [comment]
The 1600 x 900 rendering issue was fixed, 900px height screens fell through my quite complex adaptations code for different screen sizes.

Project Events are now accessible with *Project->View Project Events...* on all screen sizes, the smaller screens render panel also looks better with Project Events panel removed.

"Open file in bin" feature cannot be put back on smaller screens due to space restrictions, but it is just a small convenience feature, no absolute capability is lost.
