### ISSUE TITLE
Technical Question: Where is the clip dictionary updated?

### ISSUE THREAD

**Issue by dvdlvr** [jliljebl/flowblade#769]
1) Flowblade version (Help->About): 2.2 and above
2) MLT version (Help->Runtime Environment): 6.17.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu

Hi,

In order to be able to select audio tracks in multi-track source files (I have a ton) I need to update the clip.__dict__ with the correct value (Or this info is lost when rendering or saving).
I have found the append_clip functions (In both edit.py and persistance.py) to be good places to do this, but are there other places where the clip properties in the dictionary are modified?
It would help if you could give some pointers as to what I should be looking for.
Searching for clip_in/out in the .py files gives soooo many results.

As a note, so far, this works fine for my simple use-case tests. Projects can be saved and retrieve the selected audio index and projects without audio_index setting can still be loaded and rendered without a problem.
(I got a bit sidetracked from my subtitle project with this, but that is also well on its way)

Thanks.
Steven.

**Comment by jliljebl** [comment]
> In order to be able to select audio tracks in multi-track source files (I have a ton) I need to update the clip.dict

After reading this several times I still don't get how *selecting* audio tracks has anything to do with clip__dict__. 

We may have hit on of the few areas of code where I'm not willing to negotiate on the 
Clips are created in sequence.Sequence objects with  create_file_producer_clip() and other methods starting with 




> I have found the append_clip functions (In both edit.py and persistance.py) to be good places to do this, but are there other places where the clip properties in the dictionary are modified?

THe only modification

**Comment by jliljebl** [comment]
It would be much easier to give answers to if you described what you are trying to do in more detail. This is even more important since you may be doing code modifications that will not be acceptable to me.

> In order to be able to select audio tracks in multi-track source files (I have a ton) I need to update the clip.dict with the correct value 

I didn't quite get what selecting  audio tracks has to do clip.__dict__ We may have hit an area where exists some design decisions that I'm really not willing to negotiate on:

**Clips do not have any information on which tracks they are on and they will not be allowed to.**

Why? Because clips can move from one tracḱ to another and it is much easier to write bug free code if this restriction is enforced.

Clips get their attributes on sequence.Sequence.add_clip_attr(producer) method.

> I have found the append_clip functions (In both edit.py and persistance.py) to be good places to do this, but are there other places where the clip properties in the dictionary are modified?

Again, this is likely not acceptable to me, first 276 lines of edit.py are basically off-limits. Not 100%, but I need to fully understand what and why you doing to accept any code here. 

Reason here is that we maintain two completely synced datasrtuctures at all times and the code related to this task will be as short and clear as possible.

If you need to update some data structure after every edit, the solution is to compute the needed data fully by iterating through every clip on on every track after every edit. This is not a performance problem, since typical dataset is tesns or hundreds of clips and practical maximum about 20000, anythin can be caculated quicly enough.

We are already doing this e.g. lines 59, 69, 86 in edit.py

     resync.clip_added_to_timeline(clip, track)

and e.g. line 396, 397, 398 in edit.py

        _consolidate_all_blanks_redo(self)
        _remove_trailing_blanks_redo(self)
        resync.calculate_and_set_child_clip_sync_states()

If you give more info on what you are trying to do I can give more info on how to do it in way that fits in the existing framework.

If you didn't read  https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/codeoverview/CodebaseOverview.md reading it could be helpful.

**Comment by jliljebl** [comment]
BTW if your feature requires info on which clip is on which track or some up-to-date data on relational positions of clips on timeline a good starting place is to read *resync.py*, it does this feature: https://vimeo.com/163160546

**Comment by dvdlvr** [comment]
Thanks. I'll try to explain as clearly as possible why I think this is needed.

Many of my _source_ files have multiple audio tracks.
ffmpeg -i output would give something like this:
    Stream #0:0[0x1388]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, top first), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x138a](NAR): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 224 kb/s
    Stream #0:2[0x1389](eng): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 224 kb/s
    Stream #0:3[0x138b](eng,eng): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
    Stream #0:4[0x138c](eng): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)

flowblade currently only uses audio_index 1 which is stream 0.1. In the above example I want to add the stream 0.2 soundtrack from the source into the edit.

The code I added allows me to change the audio_index on each clip to select the soundtrack I need by just setting the audio_index property of the mlt.producer. The audio_index is already used to get the clip info data in the popup menu. It's part of the xml object linked to the producer.
Once I change the audio_index I can export the MLT XML and it will show the appropriate audio_index in the XML for each clip.
So that's fine.

The problem arises with the render process. As you know, when Flowblade start rendering a project it will first save the project, then reopen it for the render.
Since the audio_index is not included in the saved project, it is lost.
If you want to preserve the audio_index when saving a project you need to somehow include it in the saved data. The clip dict, where clip_in/out properties are, seems like the best place to do it, since the clip dict already contains the clip_in and clip_out properties. It seems like a natural fit and the necessary code change is minimal.
But I'm open to suggestions to save it using any other means.

Since selecting the audio track is a user choice it cannot simply be re-applied when you reload a clip. It needs to be saved somewhere.

The changes are fairly straightforward as such:
1) Make something where the user can select the audio track for each clip. Easy enough.
2) Change the mlt.producer attribute of the audio_index to that choice. Easy.
3) Save the choice for each clip when you save the project. This is where the clip dict (Or any other means, if there is one) comes in.
4) Restore the audio_index from the dict into the mlt.producer object when opening a project. Easy enough.

This is **not** about which audio or video track the clip is on in Flowblade. This will work in Flowblade regardless of the position.
The V/A track positions are properly saved with the project, so no need to do anything with that.
This is about being able to render the audio from _source_ that I need to use.

The only problem I have is making sure and testing that all edits on a clip object will maintain the audio_index properly. So I need to know where the clip dict (or any other method we decide to use) is handled in the code so I can do functionality and regression testing.

BTW: This is something that 'melt' does properly with the right XML file. If I use 'melt' to render the output with the audio_index=2 it will render the file with the right audio track. I just want to have Flowblade do the same thing so I don't, each time, as I do now, have to export the XML file, manually edit it to get the right audio_index, and use 'melt' for the render. I'ld prefer to do everything with Flowblade.

I hope this is clear. If you have any questions I'ld be happy to answer them.

**Comment by jliljebl** [comment]
> The only problem I have is making sure and testing that all edits on a clip object will maintain the audio_index properly.

*I think the best test is feature that changes tracks count, that may be a problem.*

If I understood all correctly here is what I think needs to be done.

I'm assuming that you have added a new module to implement most of your functionality, let's call it **subtitles.py** since this is what this seems related to.

 1) Add new clip attribute in method  *sequence:Sequence.add_clip_attr(self, clip):*
* if only data you need is audio_index then:
```python
clip.audio_index = None
```
* if you need more then one piece of data then:
```python
clip.audio_index = None
clip.subtitles_data = None
```
  with subtitles_data being an object described in **subtitles.py**, all additional data goes there. But no *clip.subtitles_data.track*, this is the one thing not allowed.

Now every **new** clip created will have this data available. It will not get destroyed on save/load as destryed attributes are specified separately.

2) Clips get cloned with *multiple* edit operations, you will need to update *edit._create_clip_clone(clip)* with something like
```python
    if clip.media_type != appconsts.PATTERN_PRODUCER:
        new_clip = current_sequence().create_file_producer_clip(clip.path, None, False, clip.ttl)
        if clip.audio_index != None:
            new_clip.audio_index = clip.audio_index
            new_clip.set("audio_index", clip.audio_index)
```

2) To maintain backward compatibility with earlier project files add into method *persistance.fill_track_mlt()*

        # Add audio index data if not available.
        if not hasattr(clip, "audio_index"):
            clip.audio_index = None

Now your code can assume that *clip.audio_index* always exists. (Obviously stuff same for maybe existing *clip.subtitles_data*.)

3) On load init mlt.producer attribute of the audio_index for every clip in *persistance.fill_track_mlt()*. Value *clip.audio_index = None* means no-op on load.

**Comment by jliljebl** [comment]
Ok, don't do 2), do just 1) and 3) first

We are currently not doing 2) even for filters so the established pattern is not to do it.

**Comment by jliljebl** [comment]
Ok, **don't do 2)**, do just 1), 3) and 4). The established pattern is to not to do 2) for clip properties such as filters.

**Comment by dvdlvr** [comment]
Ok, thanks, that helps a lot. You are right, this did come up while I was working on the subtitles. And yes, I did create a subtitle.py 😊

**Comment by jliljebl** [comment]
Closing this as this more of discussion, not actionable item. I will update the code overview with some of the info here sometime in the future.
