### ISSUE TITLE
No obvious way to manage proxy files of different resolutions

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#782]
I have a project sitting on a USB HDD, for which I rendered 19GB of full-resolution mpeg-4 proxy files (these were obviously stored locally, not on the external HDD).

When I switched the HDD to another computer and opened flowblade, I went into the proxy manager and rendered the same files again using the "rerender all possible" option (but this time at half-resolution, because it's a less-powerful computer).
![Screenshot from 2019-12-01 12-38-00](https://user-images.githubusercontent.com/25953969/69908144-ef5fa100-1437-11ea-9e41-2652024c583d.png)

When I then tried to switch flowblade into proxy mode, I got the following error:

`Loading Project, SAVEFILE_VERSION: 5`
`file does not exist`
`did not find file: '/home/thennicke/.var/app/io.github.jliljebl.Flowblade/data/flowblade/rendered_clips/proxies/e8cb2494b4c459c58edda3e48f6c9735.mp4'`
`Exception in thread Thread-7:`
`Traceback (most recent call last):
  File "/app/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/app/share/flowblade/Flowblade/proxyediting.py", line 768, in run
    project.c_seq.tractor.mark_in = self.mark_in`
`UnboundLocalError: local variable 'project' referenced before assignment`

I couldn't find a file called `e8cb2494b4c459c58edda3e48f6c9735.mp4` in either the original proxies directory on the other computer (strangely), or in the new one on the less powerful computer.

Is there a way to relink the media? I can't really see one. Ideally flowblade would be able to switch between the two sets of proxy files, and display whether each exist, and allow the user to select which one to use.

It would also be nice to be able to delete proxy files in the disk cache manager, just like we can with thumbnails and audio levels data.

**Comment by jliljebl** [comment]
> It would also be nice to be able to delete proxy files in the disk cache manager, just like we can with thumbnails and audio levels data.

Well, absolutely. I'll add this into 2.6 must-do feature list, 2.4 is in already in feature freeze . I thought that "Rendered Files" item would delete proxies,  but no, it does not. I have no idea how I missed this.

I will look at bug report part here too early in the next development cycle.

**Comment by jliljebl** [comment]
I did the following on this:

1) Proxy files can now be deleted using the Disk Cache dialog.
2) Projects with missing proxy files should now load successfully. The amount of testing was limited but everything seemed to work.

On the feature request of being able to run Flowblade on one machine to render proxy files to be used for editing on another machine: this cannot be done (without ugly hacks) because of issues relating to getting media files uniquely identified. We are now indentifying files by absolute paths and this prevents using proxy files rendered on other machines.

The correct solution is to create small remote rendering server. This would indeed be a useful feature but it will take sometime before we can spend development resources on this so I'm closing this now as *feature added* after having done the other two things.

**Comment by thennicke** [comment]
Thank for you adding these. Your second addition is especially important for my uses.
