### ISSUE TITLE
Rendering 96khz audio results in no audio track

### ISSUE THREAD

**Issue by kellen** [jliljebl/flowblade#812]
Flowblade version: 2.0.0
MLT version: 6.16.0
Distro: Ubuntu 19.10

When rendering to e.g. H.264/mp4 with 96khz audio, no audio track is rendered. If I reduce the audio rendering settings to 48khz, audio renders w/ no problems. Audio track is a 44.1khz mp3 on A1, so no real reason to render to 96khz output but expected behavior is that the audio is correctly rendered.

**Comment by jliljebl** [comment]
Ok, will look into this sometime during this development cycle.

**Comment by pmjdebruijn** [comment]
I cannot reproduce this issue on Ubuntu 20.04, Flowblade 2.4.0.1, MLT 6.20.0. ffprobe verifies that the output was indeed 96kHz, and parole outputs the audio just fine.

@kellen what does ffprobe say about your output file? Are you sure your problem doesn't occuring in playback of the file... What happens if you play the suspect file using ffplay...

**Comment by jliljebl** [comment]
I rendered two files with 96kHz that playback fine but Totem reported audio sample rate in the files to be 48kHz, not 96kHz.

I'm removing the option to render audio with 96kHz sample rate if it is not doing that anyway.
