### ISSUE TITLE
Flowblade should throw error when attempting to render after file name change

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#813]
Not a major bug here but this fix should help people to work out why their rendering isn't working.

Steps to reproduce:
* Import video
* Place video on timeline
* Change video's filename in file manager
* Click render

Expected behaviour:
* Error thrown -- file moved or missing

Actual behaviour:
* Program just hangs until render window is closed

**Comment by jliljebl** [comment]
I agree that we should give user info on how to fix issue. 

This is also not super critical as I believe users rarely move files in middle of session and we have missing file detection on project load. 

This is one of those 'dot-the-i's-and-cross-the-t's" features, there is no solid excuse not to do this once the issue has been identified.

**Comment by thennicke** [comment]
Thanks, yes it's very much a 'dot-the-i's-and-cross-the-t's' thing, as you say.

Speaking of which, I have a document where I'm compiling a list of those kinds of small bugs (for example, hotkeys that should be added). Would you mind if I just dump them somewhere in bullet point form?

**Comment by jliljebl** [comment]
You can leave them in a single Issue and then we can work out what are we going to do about individual Issues and maybe open separate issues for items that need more through discussion.

**Comment by dvdlvr** [comment]
Since Linux does not delete a file that is open (unless I'm mistaken) . maybe the right solution would be to make sure all files in a project remain open until the project is closed? Sent from my Huawei tablet-------- Original message --------From: jliljebl <notifications@github.com>Date: Sun, 16 Feb 2020, 17:54To: jliljebl/flowblade <flowblade@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [jliljebl/flowblade] Flowblade should throw error when attempting to render after file name change (#813)You can leave them in a single Issue and then we can work out what are we going to do about individual Issues and maybe open separate issues for items that need more through discussion.

**Comment by jliljebl** [comment]
I'm thinking that MLT has the ownership of files on timeline and must be able to open and close files at will, so a better approach is just simply check all files before rendering.

**Comment by jliljebl** [comment]
There is coming a major change on how files and projects are saved for 2.12. This feature may be resolved in that coming new context, but as a separate development issue we are not going to pursue it.
