### ISSUE TITLE
development version freezes

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#828]
Please include the following information.
1) Flowblade version (Help->About):commit/81e5b2b5c0324b17f8459d4b6867c2edd3c02368
2) MLT version (Help->Runtime Environment):6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): fedora 31
Create SDL1 consumer...
Launching flowblade.movie.editor.tlinerenderserver dbus service
Autosave started...
Saving project...
No user folders actions needed.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/user/flowblade-master/flowblade-trunk/Flowblade/diskcachemanagement.py", line 211, in run
    panels = _get_disk_dir_panels()
  File "/home/user/flowblade-master/flowblade-trunk/Flowblade/diskcachemanagement.py", line 241, in _get_disk_dir_panels
    panels.append(DiskFolderManagementPanel(userfolders.get_render_dir(), "/" + appconsts.PROXIES_DIR, _("Proxy Files"), PROJECT_DWARNING))
  File "/home/user/flowblade-master/flowblade-trulowblade/diskcachemanagement.py", line 57, in __init__
    self.size_info.set_text(self.get_folder_size_str())
  File "/home/user/flowblade-master/flowblade-trulowblade/diskcachemanagement.py", line 108, in get_folder_size_
    size = self.get_folder_size()
  File "/home/user/flowblade-master/flowblade-trulowblade/diskcachemanagement.py", line 95, in get_folder_size
    return self.get_folder_sizes_recursively(self.get_disk_fold)
  File "/home/user/flowblade-master/flowblade-trulowblade/diskcachemanagement.py", line 98, in get_folder_sizes_rsively
    files = os.listdir(folder)
FileNotFoundError: [Errno 2] No such file or directory: '/home/a/.local/share/flowblade/rendered_clips/proxies/'
Killed

**Comment by smolnp** [comment]
Immediately after launch, it does not respond to any action. We have to force a close.

**Comment by smolnp** [comment]
flowblade 2.4 no problem

**Comment by jliljebl** [comment]
Confirmed and fixed, thanks. This had some real changes of slipping through my release testing, I need make sure to do full clean installs too when testing from now on.

**Comment by smolnp** [comment]
Everything works. Thanks for the quick feedback.
I have a couple of questions:
What is a "Container Clip"?
What tasks are performed in the tab "Jobs"?

**Comment by jliljebl** [comment]
> What is a "Container Clip"?

Yeah, this needs a chapter in Help docs, coming in next two weeks. Here is some initial info, I can use this stuff to create Help docs.
.
A "Container Clip" is a new concept. It is a Media Item and the timeline Clip made from it that has 3 items packed together as a single entity:

**1, Unrendered Media.** This is what is displayed on timeline if container clip media is not rendered.
**2. Program** This data is used to to render a  media on timeline, sometimes using unrendered media as input.
**3. Rendered Media** This what is displayed on timeline when Container Clip is rendered.

The point of "Container Clip" can be a bit different for every type of container clip, I'll give give use case for each type of  "Container Clip" below

We currently 3 different types *Container Clips*:

1. G'Mic Script Container Clips:
**Unrendered Media.** Video Clip
**Program** G'Mic script created and saved from G'Mic tool
**Rendered Media** A clip rendered with G'mic effect

**Use Case:** To render G'Mic effects only on clip ranges used on timeline , G'mic effects are very slow to render and this will save a lot of time. Also we will ada apoosiblity to turn any clip into G'Mic effect container clip so users can add thse effect without long renders.

2. Blender Project Container Clips:
**Unrendered Media.** A Video Clip rendered on Media item creation showing that project is unrendered.
**Program** Blender Project file with ***blend** extension.
**Rendered Media** Blender render from project file.

**Use Case:**  
  * To manage Blender projects by having handles for them in Flowblade.
  * To create editors for Blender projects so that users can edit their properies on Flowblade
  * Make possible to contribute and shear interesting Blender Projects for e.g. so nice text effects.

2. MLT XML Container Clips:
**Unrendered Media.** A MLT XML vdieo clip created from selection or sequence like Compound clips previously.
**Program** * A MLT XML vdieo clip cerated from selection or sequence like Compound clips previously. Here Program is the same as unrendered media
**Rendered Media** Rendered Clip from 

These are the same as current *Compound Clips* We will drop Compound Clip nomenclature and call these *Container Clips*  we go from  "Create Compound Clip" ->"From Selection" to  "Create Container Clip" ->"From Selection".

**Use Case:**  
  * Give better timeline performance for complex multitrack container clips by pre-rendering them on timeline.Container Clip,

To test these now
1. Create Compound Clip 
2. Drag it on timeline
3. Render it with mouse *Container Clip Actions* -> *Render Clip Length..." 

>What tasks are performed in the tab "Jobs"?

Currently only container clips on timeline are rendered, later we will add Proxy Clip rendering and Slow/Fast Motion Clip rendering two
