### ISSUE TITLE
Position Scale feature requests

### ISSUE THREAD

**Issue by thennicke** [jliljebl/flowblade#834]
Flowblade 2.4.0 (flatpak, on Fedora 31)
MLT 6.18.0

Position scale has a significant number of bugs; probably the most annoying issue with flowblade for me at the moment.

- Add image to timeline, add position scale filter, and for some reason the whole image is offset on both the x and y axes.
- Trying to manually input coordinates and then hitting enter doesn't do anything
- Moving keyframes doesn't work correctly; it acts as though the previous location of the keyframe is still existing.
- Changing between 100%, 66% and 33% scale doesn't do anything; it's stuck at the default.
- Filter often automatically resets and locks up, preventing use. Haven't yet found a way to reliably replicate this yet but I will keep trying.
- Aspect ratios that differ from the project need an option to fill the screen, like a wallpaper program has the same option "centered". For example, if my project is in 16:9 but my image is in 4:3, I need a way to quickly set the image to fill the whole screen.
- Images with aspect ratios that differ from the project should be centered by default. Currently they are squished to the left side.
- Speaking of which, it would be good to have options similar to [GIMP's "Align tool"](https://docs.gimp.org/2.10/en/gimp-tool-align.html) in order to quickly and accurately position images.

**Comment by thennicke** [comment]
BTW after fiddling around with the filter I got this error in the terminal; don't know if it's related to one of the bugs.
`Traceback (most recent call last):`
`File "/app/share/flowblade/Flowblade/keyframeeditor.py", line 835, in <lambda>`
`size_select.connect("changed", lambda w,e: editor_parent.view_size_changed(w.get_active()), `
`AttributeError: 'FilterRectGeometryEditor' object has no attribute 'view_size_changed'`

**Comment by jliljebl** [comment]
Since 2.4 we have now three fixes in:
- patch to fix numerical input
- patch to fix the non-working size selector
- patch to fix the original offset for images

This should sort out  the issues, but I'll do more tests for 2.6.

> Moving keyframes doesn't work correctly; it acts as though the previous location of the keyframe is still existing.

Here the output works just fine, the panel GUI updates only to keyframes, need to improve that. This is a bit bigger issue, we're not updating sliders for filter value changes so we don't probably have the code paths in place to update GUI positions here.

I'll get back on the feature requests part later.

**Comment by thennicke** [comment]
Thanks very much, that's great to hear

**Comment by jliljebl** [comment]
Changed item title, bugs are now fixed.

**Comment by jliljebl** [comment]
Closing because bugs fixed, I'll give info on other items here.

> Aspect ratios that differ from the project need an option to fill the screen, like a wallpaper program has the same option "centered". For example, if my project is in 16:9 but my image is in 4:3, I need a way to quickly set the image to fill the whole screen.

Ok, this I'll add on  my own lists, we will get this eventually.

> Images with aspect ratios that differ from the project should be centered by default. Currently they are squished to the left side.

This goes *wontfix* now that action menu on the left side works there are items *center horizontally* and *center vertically* that make getting this quick.

> Speaking of which, it would be good to have options similar to GIMP's "Align tool" in order to quickly and accurately position images.

These we got already, the actions menu is just broken for 2.4
