### ISSUE TITLE
Moving of multiple clips to a different bin via drag&drop only moves one clip

### ISSUE THREAD

**Issue by jose1711** [jliljebl/flowblade#892]
1. Add several clips (videos) into the project
2. Create a new bin
3. Select multiple clips and try to move them to the newly created bin by drag&drop
4. Observe the result - only one clip is moved, expected: all selected clips are moved

Please include the following information.
1) Flowblade version (Help->About): 2.6.0
2) MLT version (Help->Runtime Environment): MTL 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Arch Linux

**Comment by jliljebl** [comment]
Flowblade currently  works as follows:

1. Select multiple clips with *Control + Left Mouse*
2. Press on one the clips while still holding down *Control* key
3. Drag all clips to new Bin

The difference to most applications is that in step 2. holding down *Control* is not required, but in Flowblade it currently is.

We will look to change that for 2.8 because Flowblade currently has non-standard behavioiur, but you can in fact drag multiple clips in one go if keep *Control* down all the time.

**Comment by jliljebl** [comment]
Application has been changed to work similarly as most applications on multiple selection. Previously selected items are only de-selected on mouse release, will be in 2.8.
