### ISSUE TITLE
Allow setting the proxy clips folder

### ISSUE THREAD

**Issue by dadaromeo** [jliljebl/flowblade#894]
Hi,
Please can you add a feature in the Proxy Manager dialogue that helps set the desire folder where the proxy files will be rendered? In that case, you can specify your project folder so that proxy files and original files can be moved together, to avoid some inconsistencies when moving project around and keep things a little bit transparent. Or at least, the proxy clips can be rendered in the project folder by default.

![Screenshot_2020-07-31_02-12-23](https://user-images.githubusercontent.com/5675732/88993667-783c1e80-d2de-11ea-8732-57200fe18d5a.png)

**Comment by jliljebl** [comment]
Ok, I will look onto this for 2.8. I have sort of decided that everything goes into XDG folders but maybe there is case for making it possible to set proxy files folder by user if there is a perceived need for such an functionality. Maybe user has larger disk that they would like to use for proxý files instead of the disk that XDG folders are on or something like that.

**Comment by jliljebl** [comment]
For 2.12 there will new 'Data Store' feature which allows selecting the place to save project data - including proxies - differently for every project. This feature covers the requested use case here, although not directly in the exact way requested, but I'm closing this completed.
