### ISSUE TITLE
All timecodes below the viewer

### ISSUE THREAD

**Issue by jep-fa** [jliljebl/flowblade#896]
**Proposal**

Flowblade 2.6.0
MLT 6.21.0
GTK 3.24.18
Ubuntu Studio 20.04

To make easy to look at the timecodes (sequence, marks and time position), I added a box in which the sequences times at the right top are moved in this box. The time position is moved from the middle bar.

I can pull a request.
![timecode](https://user-images.githubusercontent.com/61981966/89037459-caad2780-d33e-11ea-9b62-ab4a846f9d47.png)

**Comment by jliljebl** [comment]
This needs to optional, but should be easy enough to do on editorwindow.py.

This is one of those that some user will like it, some users will not and in these cases we will always keep the existing behavior available and in most cases keep it default, too.

**Comment by jep-fa** [comment]
OK. It seems to me that is the more ergonomic and constant place : to know the duration of the sequence you have to look at the right top ; the timecode position is different depending on the middlebar layout. I gathered this information in the same unchanged place where the look is most often.

To make optional this feature, I have to put conditions in editorwindow.py, gui.py, updater.py, middlebar.py, guicomponents.py.
I can do it but this unnecessarily complicates the program and I think you can close this proposal.

**Comment by jliljebl** [comment]
I'm going to decline this design.

This is a major conceptual change and needs to be fully assessed before accepting.

I have a list of points-of-view when accepting GUI changes that are in the (rough) order of importance:

1) **Current conventions on major commercial and FLOSS applications.** I believe the time for "originality" is over in desktop applications and users mostly desire instant familiarity for new UX.
* Avid has fundamentally same thing as Flowblade
* Final Cut X has timecode in center which is optionally available in Flowblade.
* Premiere has position and under similarly but not in and out points.

 Inconclusive or against for this particular design.

2) **Well conducted usability research with A/B testing of the proposed change** This unfortunately is not realistically available for most FLOSS projects.

3) **Existing UX** I need to be strongly convinced on UX changes being quite big improvements before doing changes. This is much less enforced for optional non-default changes changes as they not affect out-of-box UX.

5) **A clear signal by multiple indendent users on preference for the change that I have come to agree with** This is poor mans version of point **2)**

6) **Measurable or very clear changes on sizes and notability of GUI elements** This one has the major down side here that available area is display quite a lot because of the loss of vertical space that is magnified by the logically following loss of  horizontal display area because we need to maintain aspect ratio. On 768px height screens the effects would be disastrous I think.

 6) **Visual considerations** I don't think this one looks good to be honest, too busy and cramped for me.

7) **Logical arguments based on (or not) on general usability research** This one has the locality argument going for it quite well but I think other considerations are stronger.

There are some hints in point 1 that Flowblade desing on this  could be made more mainstream and locality argument has brought up before, the In/Out/Selection length displays are not very discoverable. It may be possible to present a design that could be much more strongly argued to be improvement but this particular one in does not meet these requirements so I'm declining this fully, we should not make this optional but rather look for a clearly better design.

**Comment by jep-fa** [comment]
All right.
It's only for my use. 

Of course, this addition reduces the lower part of tline_pane. I tried to include tline_pane in a scrolled window (this would be an interesting improvement) without being able to make all the tracks visible . So, I placed the render_panel in a scrolled window and lowered the minimum height of the vumeter. Now, I can lower the top_row_hbox and save space for the tracks or more generally adjust the two panels tline_pane and top_row_hbox to the optimal size of the display when there is no more black stripes on top/bottom or right/left.

We don't have the same selection criteria. While I agree to be consistent with existing software, I think that there is no consensus yet and each has its particularities. I'm looking for software ergonomics to save time and fatigue during assembly.

1. First principle: **reduce eye fatigue for sessions of several hours**:

- reduce eye movements; 
- avoid that the most often watched parts are on the right, left, top or bottom (= centered viewer for example); 
- dark background; 
- easy location of clips (= start icon, track height 75 px), 
- grouping of similar information (here timecode), 
- immediate location of icons.

2. Second principle: **easy access to operations or data**

- The most frequent operations for me are in the middlebar, accessible with a mouse click as trim ripple and spacer that I placed there . I have created others: 
cut the end or the beginning of a clip, make a title transparent, adjust several clips to the same sound level (too noisy scene for example), search if there is not a blank in the sequence, fade in/out video + audio, cut, copy and paste a cut clip at the bar position, ...

- Timeline duration and position in the timeline must be close to the viewer and timeline position near the play button.

3. Third principle: **The mouse remains constantly in my right hand** (I am right-handed) and the left hand can use the left hand keys of the keyboard. If I have to let go of the mouse and/or take my eyes off the screen to find the key to press, I consider that I lose comfort and efficiency. By reflex or habit, I still use the left and right arrows.

4. Fourth principle: **I **perform all the operations on the timeline**** unlike professionals who cut out the clip before placing it in the timeline. This way, I can simply check my editing by immediately launching playback to view the fitting and correct it if necessary.

5. Fifth principle: **I prefer frequently used functions**. I'm not interested in the multitude of effects that I'm going to use exceptionally as long as the most common operations are not readily available.

6. Sixth principle: **I need complete and up-to-date user documentation** or knowledge of the program's modules.

ALL these facilities together, I couldn't find them in any software. I gave up on Pinnacle, which was crashing a lot. I practiced for more than 15 years Magix Video de luxe which is a very good, practical and stable editing software, unfortunately under Windows. But some functions required several clicks in menus. I tried Vegas which was not practical. I created plugins for Bjender but the lack of clip icon on the timeline made it difficult to locate the clips easily. Recently, I tried Da Vinci, which is very complex, not intuitive and requires the conversion of files to .mov. I added plugins to Pitivi for a year, unusable with my .mts files and difficult to maintain because python Gtk3 examples are non-existent on the Net.  Shotcut, Kdenlive don't have the desired functions and I don't have the ability to modify them. With Flowblade, I finally found the editing software under Linux that I can adapt to my use although I needed some time to learn like any new software. It's a complete and stable software.


If the functions I propose don't fit your objectives, I regret it because they make Flowblade easier to use for me, but I respect your choices. For the next proposals, I will use your criteria.

**Comment by jliljebl** [comment]
I will post some additional thoughts here during this development cycle, maybe I can have some counter proposals on this particular idea. There may very well be approaches that satisfy all points made here. Design is always an ongoing process and by no means I mean to communicate that discussion is ended on this, at this poin I just don't t find the exact design proposed something we should move forward with.
