### ISSUE TITLE
Most G'MIC effects do not work.

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#900]
Launch script dir: /home/user/flowblade-master/flowblade-trunk
Running from filesystem...
MLT found, version: 6.20.0
numpy version: 1.18.4
Application version: 2.6.0
OS: Fedora 32 (Cinnamon)
Python 3.8.3 (default, May 29 2020, 00:00:00) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
GTK+ version: 3.24.21
XDG user data exists.
prefs updated to new version, new param count: 87
Locale: ru_RU
Found translations at /home/user/flowblade-master/flowblade-trunk/Flowblade/locale/, using those.
Use OS locale language.
Valid shortcut files found: ['flowblade.xml', 'premiere.xml']
Keyboard shortcuts file: flowblade.xml
Loading shortcuts: Flowblade
Gtk version is 3.24.21, Flowblade theme is available.
Using Full Screen size for layout: 1366 x 768
Small height: True
Small width: True
ladspa_dsp: error: no config files found
Detecting environment...

Some work, but more scripts produce something like this:
"[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file '/home/user/.cache/flowblade/gmic/session_1596456819969/clip_frames/frame0.png' at position 0 (1 image 1280x720x1x3).
[gmic]-1./ Input file '-fx_emulate_film_print' at position 1
[gmic]-1./ [0;31;59m[1m*** Error *** Unknown command or filename '-fx_emulate_film_print'.[0;0;0m

Return code:255"

**Comment by jliljebl** [comment]
This one does not reproduce on my Ubuntu 20.04. Leaving open to discover more information.

**Comment by jliljebl** [comment]
Last time I looked what happened was that for film emulation filters G'Mic downloads a 3D LUT file from, well, somewhere, don't know where exactly, and these are not distributed with packages. That could be an issue, but print out seems to indicate that Fedora 32 G'Mic just does not have *-fx_emulate_film_print* command available which Ubuntu 20.04 G'Mic certainly does.

Both have same versions 2.9.1 of G'Mic available but maybe Fedora has disabled the film emulation filters because of the behind-users-back downloading behavior which might be considered to be a security issue, don't know.

**Comment by jliljebl** [comment]
I got this when doing Flatpak fixes:

    [gmic]-1./ [0;31;59m[1m*** Error *** Unknown command or filename '-fx_8bits 25,800,16,0'.[0;0;0m

The cause was that I stopped using *shell=True* in Popen and arguments got delivered to *gmic* command line program with space inside an argument. Maybe this will also get fixed now that *shell=True* is no longer used, we will see after 2.6.1 point release.

**Comment by jliljebl** [comment]
Confirmed. I tested this on Fedora 33 WM and in loaded old command *-gimp_8bits 25,800,16,0* instead of the correct new *-fx_8bits 25,800,16,0* command which worked.

**Comment by jliljebl** [comment]
Somehow my heuristics on Fedora 33 loaded the wrong G'Mic scripts file. I fixed this by dropping support for G'Mic version 1, now the wrong commands cannot be loaded.
