### ISSUE TITLE
Add pause/continue button to render dialogue

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade#909]
Please add a `Pause Render` / `Continue Render` button to the render dialogue. At the moment, there is only a `Stop Render` button. Pausing a rendering can  be needed when processing power is needed by another application and it would be costly to completely stop a rendering which takes hours.

1) Flowblade version (Help->About): 2.4.0
2) MLT version (Help->Runtime Environment): 6.20.0
3) Your distribution (Ubuntu, Debian, Mint etc.): Ubuntu 20.04

**Comment by jliljebl** [comment]
If I can pull this out of MLT by simply pausing render we can get this for next release. 

If not then we are unfortunately out of luck, there is no feasible way to do this otherwise and patching MLT to get this feature will likely be too difficult or maybe not feasible at all.

I'll test if this works in the coming months before 2.8.

**Comment by jliljebl** [comment]
I looked at MLT source code and pausing rendering will just abort and lose all state. Freezing process could in principle be used but that is going to crash GUI even if MLT process could be paused. Closing as *wontfix* because I do not believe this to be possible.
