### ISSUE TITLE
very  slow rendering

### ISSUE THREAD

**Issue by welon68** [jliljebl/flowblade#918]
50-minute movie renders 12-14h!

lossless h264 25 FPS 1080p 
intel i5 3330 8GB ram

I think it's way too long. Is there a chance for improvement?

**Comment by dvdlvr** [comment]
On my i7 rendering takes about 1.5 times the length of the video.  On my i3 about 2x.So your rendering times are abnormally long. Did you change anything in the performance settings? Can you export the project file to MLT XML and share it? Do you render to and from the same hard drive? (If so, render to a different hard drive if possible - that might improve performance). Do you use an internal or external hard drive for rendering or source video? That can dramatically slow down the process.

**Comment by jliljebl** [comment]
There have been reports on slow rendering and some memory consumption problems on rendering, but so far I haven't been able to come up with any theories on possible causes, rendering seems fine on my system.

I will do comparison testing with other MLT based editors since we are rendering from build mlt.Tractor objects and I think Shotcut might render from XML producers, there is a possible source for performance differences there. This is probably going to be in 2.10 timeframe as doing this properly will take some effort. I'll keep all these open until I have additional info.

**Comment by dvdlvr** [comment]
For info: I regularly render from xml, exported from Flowblade, using melt and I don't see any major time difference.

**Comment by jliljebl** [comment]
Merged with #924.
