### ISSUE TITLE
GTK themes in Flowblade

### ISSUE THREAD

**Issue by smolnp** [jliljebl/flowblade#955]
When choosing a dark theme, if any light theme (except Arc) is installed on the system, the Flowblade will be decorated in light colors and vice versa. With the Arc theme, everything works as expected.
Example:
Mint-Y
![mintgrey](https://user-images.githubusercontent.com/26217756/104063386-242e5200-520d-11eb-961e-f63954d92334.png)
Now choose Mint-Y-Dark
![mitdarc](https://user-images.githubusercontent.com/26217756/104063583-74a5af80-520d-11eb-99b8-47d027d8759c.png)
Flowblade will be dark even if the Arc light theme is selected
![arctheme](https://user-images.githubusercontent.com/26217756/104063795-cc441b00-520d-11eb-8b2b-e641bf3b342a.png)
Is this the correct behavior?

**Comment by smolnp** [comment]
Also, I think the neutral theme is more gray than gray. Maybe the names are confused?
![grey](https://user-images.githubusercontent.com/26217756/104063925-16c59780-520e-11eb-9024-69df0c10c064.png)
![neytral](https://user-images.githubusercontent.com/26217756/104064064-47a5cc80-520e-11eb-8dda-80ce42d9e5e2.png)

**Comment by jliljebl** [comment]
> When choosing a dark theme, if any light theme (except Arc) is installed on the system, the Flowblade will be decorated in light colors and vice versa. With the Arc theme, everything works as expected.

"Adwaita" works too. The issue here that I have this line of code:

     Gtk.Settings.get_default().set_property("gtk-application-prefer-dark-theme", True)

to set the decoration color and *GTK theme has to support this feature for this to work*. "Arc" and "Adwaita" support this, many others don't.  GTK CSS does not give me access to this property unless I use the GtkHeaderBar but that is designed to hold widgets and is much too high for Flowblade which wants the traditional "small titlebar with application menu" UX.

> Also, I think the neutral theme is more gray than gray. Maybe the names are confused?

Neutral means that all RGB values are exactly the same on all tones (e.g. 55,55,55) where as "Grey" has lightly bluish tint but is still grey in my view, not "Blue" like the current theme. I'll be probably making the "Neutral" the default theme from now as Final Cut X and Premier have both neutral themes and that seems to be the convention now.

I'm closing this with some label because right now there isn't anything I think I can do about these.
