### ISSUE TITLE
Issue with aac encoded audio track 

### ISSUE THREAD

**Issue by bonnefoi** [jliljebl/flowblade#982]
1) Flowblade version: 2.6.3
2) MLT version: 6.20.0
3) Linux distribution: Ubuntu 20.04

I've added an audio track in my timeline and it's **automatically** played, can't be stopped and can't be randomly accessed.

 ```
Input #0, aac, from 'son_cours.aac':
  Duration: 02:54:06.72, bitrate: 68 kb/s
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 68 kb/s
```

**Comment by jliljebl** [comment]
Can you make the audio file available? This seems impossible but if I can the file I can try to reproduce,

**Comment by jliljebl** [comment]
Holy hell, I got it reproduced. This is...interesting.

**Comment by jliljebl** [comment]
So if you get this transcoding file into some other format should fix this.

**Comment by jliljebl** [comment]
Ok:

* MLT refuses to place the file I got the the production from because it is 'not seekable'
* KDEnlive does not show aac files as 'Supported files'
* Someone else said: *"Raw aac streams don't support sample exact seeking (without parsing the whole file first), so foobar disables seeking. Programs that let you seek in the file are not sample exact. To enable seeking in foobar, put the raw aac file in a mp4 container. You can do this with mp4box as far as I know."*

Seems clear that AAC files will not play well with editors, so I'm going to diasable loading them. The autoplay thing is just some undefined behaviour, maybe MLT attempts to stream it, it has e.g. following parameter:

*initial_pause*

*description: do not start playing the stream immediately (rtsp)*

**Comment by jliljebl** [comment]
MLT had property "seekable" so we just read that for audio files now and disallow allowing opening them.
